<?php
declare(strict_types=1);
$status=is_string($_GET['status']??null)?$_GET['status']:'open';
if(!in_array($status,['open','new','in_progress','resolved','closed','all'],true))$status='open';
$category=is_string($_GET['category']??null)?$_GET['category']:'';
if(!in_array($category,['','gameplay','interface','performance','account','other'],true))$category='';
$conditions=['b.world_id=?'];$params=[$selectedWorld];
if($status==='open')$conditions[]="b.status IN ('new','in_progress')";elseif($status!=='all'){$conditions[]='b.status=?';$params[]=$status;}
if($category!==''){$conditions[]='b.category=?';$params[]=$category;}
$rows=$db->query('SELECT b.*,p.username,a.username AS handled_by_name FROM bug_reports b JOIN players p ON p.id=b.player_id LEFT JOIN admin_users a ON a.id=b.handled_by WHERE '.implode(' AND ',$conditions).' ORDER BY FIELD(b.priority,\'urgent\',\'high\',\'normal\',\'low\'),FIELD(b.status,\'new\',\'in_progress\',\'resolved\',\'closed\'),b.created_at DESC LIMIT 200',$params)->fetchAll();
$counts=[];foreach($db->query('SELECT status,COUNT(*) count FROM bug_reports WHERE world_id=? GROUP BY status',[$selectedWorld])->fetchAll() as $count)$counts[$count['status']]=(int)$count['count'];
$statusNames=['new'=>'Neu','in_progress'=>'In Bearbeitung','resolved'=>'Gelöst','closed'=>'Geschlossen'];
$priorityNames=['low'=>'Niedrig','normal'=>'Normal','high'=>'Hoch','urgent'=>'Dringend'];
$categoryNames=['gameplay'=>'Spielablauf','interface'=>'Anzeige & Bedienung','performance'=>'Leistung & Absturz','account'=>'Konto & Anmeldung','other'=>'Anderer Bereich'];
$severityNames=['minor'=>'Kleiner Fehler','normal'=>'Störend','blocking'=>'Blockierend'];
?>
<section class="card bug-report-inbox"><form method="get" class="toolbar"><input type="hidden" name="world_id" value="<?= $selectedWorld ?>"><label>Status<select name="status"><?php foreach(['open'=>'Offen (neu + in Arbeit)','new'=>'Nur neu','in_progress'=>'In Bearbeitung','resolved'=>'Gelöst','closed'=>'Geschlossen','all'=>'Alle'] as $key=>$label): ?><option value="<?= ah($key) ?>" <?= $status===$key?'selected':'' ?>><?= ah($label) ?></option><?php endforeach ?></select></label><label>Bereich<select name="category"><option value="">Alle Bereiche</option><?php foreach($categoryNames as $key=>$label): ?><option value="<?= ah($key) ?>" <?= $category===$key?'selected':'' ?>><?= ah($label) ?></option><?php endforeach ?></select></label><button type="submit">Filtern</button></form>
<div class="bug-report-summary"><?php foreach(['new'=>'Neu','in_progress'=>'In Arbeit','resolved'=>'Gelöst','closed'=>'Geschlossen'] as $key=>$label): ?><span><small><?= ah($label) ?></small><strong><?= an($counts[$key]??0) ?></strong></span><?php endforeach ?></div>
<?php if(!$rows): ?><p class="empty">Keine Bugmeldungen in dieser Auswahl.</p><?php endif ?>
<div class="bug-report-list"><?php foreach($rows as $report): $context=is_string($report['client_context'])?json_decode($report['client_context'],true):$report['client_context'];if(!is_array($context))$context=[]; ?>
<article class="bug-report-card" id="meldung-<?= (int)$report['id'] ?>">
  <header><div><span class="bug-status is-<?= ah($report['status']) ?>"><?= ah($statusNames[$report['status']]??$report['status']) ?></span><span class="bug-priority is-<?= ah($report['priority']) ?>"><?= ah($priorityNames[$report['priority']]??$report['priority']) ?></span><span class="pill"><?= ah($categoryNames[$report['category']]??$report['category']) ?></span></div><time datetime="<?= ah($report['created_at']) ?>"><?= ah($report['created_at']) ?> UTC</time></header>
  <h2>#<?= (int)$report['id'] ?> · <?= ah($report['title']) ?></h2>
  <p class="bug-reporter"><a href="<?= APP_BASE ?>/admin/players/<?= (int)$report['player_id'] ?>?world_id=<?= $selectedWorld ?>"><?= ah($report['username']) ?></a> · <?= ah($severityNames[$report['severity']]??$report['severity']) ?> · <?= ah($report['page_path']?:'Bereich nicht angegeben') ?></p>
  <div class="bug-report-copy"><section><h3>Beschreibung</h3><p><?= nl2br(ah($report['description'])) ?></p></section><?php if($report['reproduction_steps']!==''): ?><section><h3>Schritte zum Nachstellen</h3><p><?= nl2br(ah($report['reproduction_steps'])) ?></p></section><?php endif ?><?php if($report['expected_result']!==''): ?><section><h3>Erwartetes Ergebnis</h3><p><?= nl2br(ah($report['expected_result'])) ?></p></section><?php endif ?></div>
  <details><summary>Technische Angaben</summary><dl class="bug-technical"><?php foreach($context as $key=>$value): ?><div><dt><?= ah(str_replace('_',' ',$key)) ?></dt><dd><?= ah((string)$value) ?></dd></div><?php endforeach ?><div><dt>Browser</dt><dd><?= ah($report['user_agent']?:'Nicht verfügbar') ?></dd></div><div><dt>IP</dt><dd><?= ah($report['ip_address']?:'Nicht verfügbar') ?></dd></div></dl></details>
  <form method="post" action="<?= APP_BASE ?>/admin/action/bug-report-update" class="admin-form bug-report-editor"><input type="hidden" name="csrf_token" value="<?= ah($_SESSION['admin_csrf']) ?>"><input type="hidden" name="operation_id" value="<?= bin2hex(random_bytes(16)) ?>"><input type="hidden" name="world_id" value="<?= $selectedWorld ?>"><input type="hidden" name="report_id" value="<?= (int)$report['id'] ?>"><fieldset <?= $canEdit?'':'disabled' ?>><div class="fields"><label>Status<select name="status"><?php foreach($statusNames as $key=>$label): ?><option value="<?= ah($key) ?>" <?= $report['status']===$key?'selected':'' ?>><?= ah($label) ?></option><?php endforeach ?></select></label><label>Priorität<select name="priority"><?php foreach($priorityNames as $key=>$label): ?><option value="<?= ah($key) ?>" <?= $report['priority']===$key?'selected':'' ?>><?= ah($label) ?></option><?php endforeach ?></select></label></div><label>Interne Notiz<textarea name="admin_note" maxlength="4000" rows="3" placeholder="Analyse, Rückfragen oder Lösung …"><?= ah($report['admin_note']) ?></textarea></label><label>Änderungsgrund<input name="reason" minlength="3" maxlength="500" required placeholder="z. B. geprüft und reproduziert"></label><button type="submit">Bearbeitung speichern</button></fieldset></form>
  <?php if($report['handled_by_name']): ?><small class="muted">Zuletzt bearbeitet von <?= ah($report['handled_by_name']) ?><?= $report['handled_at']?' · '.ah($report['handled_at']).' UTC':'' ?></small><?php endif ?>
</article><?php endforeach ?></div></section>
