<?php
declare(strict_types=1);
use Conquer\Game\Locale;
use Conquer\Game\Community\SocialService;
$ct=static fn(string $key):string=>Locale::html('social.'.$key);
$moderation=SocialService::moderationState($selectedWorld);
$messages=$db->query('SELECT id,player_id,username,message,created_at FROM world_chat WHERE world_id=? ORDER BY id DESC LIMIT 100',[$selectedWorld])->fetchAll();
$news=$db->query('SELECT * FROM community_news WHERE world_id=? ORDER BY id DESC LIMIT 20',[$selectedWorld])->fetchAll();
?>
<section class="card"><h2><?= $ct('moderation') ?></h2><h3><?= $ct('reports') ?></h3>
<?php if(!$moderation['reports']): ?><p class="empty"><?= $ct('no_reports') ?></p><?php endif ?>
<?php foreach($moderation['reports'] as $report): ?>
<article class="card"><h3>#<?= (int)$report['id'] ?> · <span data-user-content><?= ah($report['player_name']) ?></span></h3><p><?= $ct('reporter') ?>: <span data-user-content><?= ah($report['reporter_name']) ?></span> · <?= ah($report['created_at']) ?> UTC</p><p><?= $ct('reason_'.$report['reason']) ?></p><p data-user-content><?= nl2br(ah($report['details'])) ?></p>
<?php if(!empty($report['snapshot']['message'])): ?><blockquote data-user-content><?= nl2br(ah($report['snapshot']['message'])) ?></blockquote><?php endif ?>
<?php adminForm('community-report-update',$selectedWorld); ?><input type="hidden" name="report_id" value="<?= (int)$report['id'] ?>"><label><?= $ct('status') ?><select name="status"><?php foreach(['new','reviewing','resolved','dismissed'] as $status): ?><option value="<?= ah($status) ?>" <?= $report['status']===$status?'selected':'' ?>><?= $ct('status_'.$status) ?></option><?php endforeach ?></select></label><label><?= $ct('internal_note') ?><textarea name="admin_note" rows="3" maxlength="2000"><?= ah($report['admin_note']) ?></textarea></label><?php adminSubmit(Locale::t('social.save')); ?>
</article><?php endforeach ?></section>
<section class="card"><h2><?= $ct('restrict_chat') ?></h2><?php adminForm('community-chat-ban',$selectedWorld); ?><label><?= $ct('player_id') ?><input type="number" name="player_id" min="1" required></label><label><?= $ct('duration_minutes') ?><input type="number" name="minutes" min="1" max="43200" value="60" required></label><?php adminSubmit(Locale::t('social.restrict_chat')); ?><h3><?= $ct('active_bans') ?></h3>
<?php if(!$moderation['bans']): ?><p class="empty"><?= $ct('no_bans') ?></p><?php endif ?>
<?php foreach($moderation['bans'] as $ban): ?><article class="card"><strong data-user-content><?= ah($ban['username']) ?></strong><p><?= $ct('expires') ?>: <?= ah($ban['expires_at']) ?></p><p data-user-content><?= ah($ban['reason']) ?></p><?php adminForm('community-chat-unban',$selectedWorld,(int)$ban['player_id']);adminSubmit(Locale::t('social.lift_ban')); ?></article><?php endforeach ?></section>
<section class="card"><h2><?= $ct('publish_news') ?></h2><?php adminForm('community-news-save',$selectedWorld); ?><input type="hidden" name="news_id" value="0"><label><?= $ct('title') ?><input name="title" minlength="3" maxlength="160" required></label><label><?= $ct('body') ?><textarea name="body" rows="5" minlength="3" maxlength="6000" required></textarea></label><label><?= $ct('status') ?><select name="published"><option value="1"><?= $ct('published') ?></option><option value="0"><?= $ct('draft') ?></option></select></label><?php adminSubmit(Locale::t('social.saved_notice')); ?>
<h3><?= $ct('recent_news') ?></h3><?php foreach($news as $post): ?><?php adminForm('community-news-save',$selectedWorld); ?><input type="hidden" name="news_id" value="<?= (int)$post['id'] ?>"><label><?= $ct('title') ?><input name="title" value="<?= ah($post['title']) ?>" minlength="3" maxlength="160" required></label><label><?= $ct('body') ?><textarea name="body" rows="4" minlength="3" maxlength="6000" required><?= ah($post['body']) ?></textarea></label><label><?= $ct('status') ?><select name="published"><option value="1" <?= $post['published']?'selected':'' ?>><?= $ct('published') ?></option><option value="0" <?= !$post['published']?'selected':'' ?>><?= $ct('draft') ?></option></select></label><?php adminSubmit(Locale::t('social.saved_notice')); ?><?php endforeach ?></section>
<section class="card"><h2><?= $ct('world_log') ?></h2><div class="table-wrap"><table><tbody><?php foreach($messages as $m): ?><tr><td><?= ah($m['created_at']) ?> UTC</td><td><a data-user-content href="<?= APP_BASE ?>/admin/players/<?= (int)$m['player_id'] ?>?world_id=<?= $selectedWorld ?>"><?= ah($m['username']) ?></a></td><td data-user-content><?= ah($m['message']) ?></td></tr><?php endforeach ?></tbody></table></div></section>
