<?php
declare(strict_types=1);
$search=is_string($_GET['q']??null)?trim($_GET['q']):'';$filter=$_GET['filter']??'all';$page=max(1,min(100000,(int)($_GET['page']??1)));$where='c.world_id=?';$args=[$selectedWorld];
if($search!==''){$where.=' AND (p.username LIKE ? OR p.email LIKE ? OR p.id=?)';$args[]='%'.$search.'%';$args[]='%'.$search.'%';$args[]=(int)$search;}
if($filter==='banned')$where.=' AND p.is_banned=1';elseif($filter==='active')$where.=' AND p.last_active_at>DATE_SUB(UTC_TIMESTAMP(),INTERVAL 7 DAY)';
$total=(int)$db->query('SELECT COUNT(*) FROM players p JOIN cities c ON c.player_id=p.id WHERE '.$where,$args)->fetchColumn();
$rows=$db->query('SELECT p.id,p.username,p.email,p.is_banned,p.last_active_at,p.lord_level,p.gems,c.name AS city_name,c.castle_level,c.power FROM players p JOIN cities c ON c.player_id=p.id WHERE '.$where.' ORDER BY p.id DESC LIMIT 50 OFFSET '.(($page-1)*50),$args)->fetchAll();
?>
<section class="card"><form method="get" class="toolbar"><input type="hidden" name="world_id" value="<?= $selectedWorld ?>"><label>Spieler suchen<input name="q" value="<?= ah($search) ?>" placeholder="Name, E-Mail oder Spieler-ID"></label><label>Status<select name="filter"><?php foreach(['all'=>'Alle Spieler','active'=>'In 7 Tagen aktiv','banned'=>'Gesperrte Spieler'] as $key=>$name): ?><option value="<?= $key ?>" <?= $filter===$key?'selected':'' ?>><?= $name ?></option><?php endforeach ?></select></label><button>Suchen</button></form><div class="split"><h2><?= an($total) ?> Spieler</h2><span class="muted">50 Einträge pro Seite</span></div><div class="table-wrap"><table><thead><tr><th>Spieler</th><th>Stadt</th><th>Stufe</th><th>Macht</th><th>Edelsteine</th><th>Letzte Aktivität</th><th></th></tr></thead><tbody><?php foreach($rows as $p): ?><tr><td><strong><?= ah($p['username']) ?></strong><br><span class="subtle">#<?= (int)$p['id'] ?> · <?= $p['is_banned']?'Gesperrt':'Aktiv' ?></span></td><td><?= ah($p['city_name']) ?></td><td>Burg <?= (int)$p['castle_level'] ?></td><td><?= an($p['power']) ?></td><td><?= an($p['gems']) ?></td><td><?= ah($p['last_active_at']??'—') ?></td><td><a href="<?= APP_BASE ?>/admin/players/<?= (int)$p['id'] ?>?world_id=<?= $selectedWorld ?>">Verwalten →</a></td></tr><?php endforeach ?></tbody></table></div><?php if(!$rows): ?><p class="empty">Keine passenden Spieler gefunden.</p><?php endif ?><div class="pagination"><?php if($page>1): ?><a href="?<?= ah(http_build_query(['world_id'=>$selectedWorld,'q'=>$search,'filter'=>$filter,'page'=>$page-1])) ?>">← Zurück</a><?php endif ?><?php if($page*50<$total): ?><a href="?<?= ah(http_build_query(['world_id'=>$selectedWorld,'q'=>$search,'filter'=>$filter,'page'=>$page+1])) ?>">Weiter →</a><?php endif ?></div></section>
