<?php
declare(strict_types=1);
$player=$db->query('SELECT id,username,email,is_banned,gems,lord_level,vip_level,created_at,last_active_at FROM players WHERE id=?',[$playerId])->fetch();
if(!$player){http_response_code(404);echo '<p class="empty">Spieler nicht gefunden.</p>';return;}
$city=$db->query('SELECT * FROM cities WHERE player_id=? AND world_id=?',[$playerId,$selectedWorld])->fetch();
if(!$city){echo '<div class="notice">Dieser Spieler hat in der ausgewählten Welt keine Stadt. Bitte wähle oben seine Welt aus.</div>';return;}
$cid=(int)$city['id'];$buildings=$db->query('SELECT building_code,level FROM city_buildings WHERE city_id=?',[$cid])->fetchAll(PDO::FETCH_KEY_PAIR);
$research=$db->query('SELECT research_code,level FROM player_research WHERE player_id=? AND world_id=?',[$playerId,$selectedWorld])->fetchAll(PDO::FETCH_KEY_PAIR);
$troops=$db->query('SELECT troop_code,count FROM city_troops WHERE city_id=?',[$cid])->fetchAll(PDO::FETCH_KEY_PAIR);
$queue=$db->query('SELECT building_code,level_to,finishes_at FROM building_queue WHERE city_id=? AND is_processed=0',[$cid])->fetchAll();
$rqueue=$db->query('SELECT research_code,level_to,finishes_at FROM research_queue WHERE player_id=? AND world_id=? AND is_processed=0',[$playerId,$selectedWorld])->fetchAll();
$gifts=$db->query('SELECT * FROM admin_gifts WHERE player_id=? AND world_id=? ORDER BY id DESC LIMIT 20',[$playerId,$selectedWorld])->fetchAll();
?>
<div class="profile-head"><div class="inline"><span class="avatar"><?= ah(mb_strtoupper(mb_substr($player['username'],0,1))) ?></span><div><h2><?= ah($player['username']) ?></h2><span class="muted">#<?= $playerId ?> · <?= ah($player['email']) ?> · <?= ah($city['name']) ?> (<?= (int)$city['coord_x'] ?>, <?= (int)$city['coord_y'] ?>)</span></div></div><span class="pill <?= $player['is_banned']?'closed':'open' ?>"><?= $player['is_banned']?'Gesperrt':'Aktiv' ?></span></div>
<div class="stats"><div class="stat"><small>BURGSTUFE</small><strong><?= (int)$city['castle_level'] ?></strong><span><?= ah($world['name']) ?></span></div><div class="stat"><small>MACHT</small><strong><?= an($city['power']) ?></strong><span>Gebäudemacht</span></div><div class="stat"><small>EDELSTEINE</small><strong><?= an($player['gems']) ?></strong><span>Kontoweit</span></div><div class="stat"><small>LORD / VIP</small><strong><?= (int)$player['lord_level'] ?> / <?= (int)$player['vip_level'] ?></strong><span>Seit <?= ah(substr($player['created_at'],0,10)) ?></span></div></div>
<div class="grid"><section class="card"><h2>Ressourcen ändern</h2><p>Setzt den absoluten Stadtbestand. Produktion läuft anschließend ab diesem Zeitpunkt weiter.</p><?php adminForm('set-resources',$selectedWorld,$playerId); ?><div class="fields"><?php foreach(['food'=>'Nahrung','lumber'=>'Holz','stone'=>'Stein','gold'=>'Gold'] as $r=>$label)adminNumber($label,$r,$city[$r]); ?></div><?php adminSubmit('Ressourcen setzen'); ?></section><section class="card"><h2>Kontozugang & Schutz</h2><p>Eine Sperre gilt kontoweit und beendet alle Spielsitzungen.</p><?php adminForm($player['is_banned']?'unban':'ban',$selectedWorld,$playerId);adminSubmit($player['is_banned']?'Spieler entsperren':'Spieler sperren'); ?><hr><?php adminForm('grant-shield',$selectedWorld,$playerId);adminNumber('Zusätzlicher Stadtschutz (Stunden)','hours',24,1,720);adminSubmit('Schutz verlängern'); ?><p class="subtle">Aktueller Stadtschutz: <?= ah($city['shield_expires_at']??'Keiner') ?></p></section>
<section class="card"><h2>Gebäude aufwerten</h2><p>Alle 13 echten Gebäudetypen. Eine aktive Bauwarteschlange verhindert Änderungen am betroffenen Gebäude.</p><?php if($queue): ?><div class="hint"><?php foreach($queue as $q): ?><?= ah($q['building_code']) ?> → <?= (int)$q['level_to'] ?> · <?= ah($q['finishes_at']) ?> UTC<br><?php endforeach ?></div><?php endif ?><?php adminForm('set-building',$selectedWorld,$playerId); ?><div class="fields"><label>Gebäude<select name="building_code" onchange="this.form.elements.level.value=this.selectedOptions[0].dataset.level"><?php foreach(\Conquer\Game\City\CityState::BUILDING_NAMES as $code=>$label): ?><option value="<?= ah($code) ?>" data-level="<?= (int)($buildings[$code]??1) ?>"><?= ah($label) ?> · Stufe <?= (int)($buildings[$code]??1) ?></option><?php endforeach ?></select></label><?php adminNumber('Neue Stufe','level',$buildings['castle']??1,1,30); ?></div><?php adminSubmit('Gebäudestufe setzen'); ?></section>
<section class="card"><h2>Forschung verwalten</h2><p>Die Stufengrenzen stammen aus dem aktuellen Forschungskatalog. Laufende Forschung ist geschützt.</p><?php if($rqueue): ?><div class="hint"><?php foreach($rqueue as $q): ?><?= ah($q['research_code']) ?> → <?= (int)$q['level_to'] ?> · <?= ah($q['finishes_at']) ?> UTC<br><?php endforeach ?></div><?php endif ?><?php $nodes=\Conquer\Game\Research\ResearchData::allNodes();$first=array_key_first($nodes);adminForm('set-research',$selectedWorld,$playerId); ?><div class="fields"><label>Forschungsprojekt<select name="research_code" onchange="this.form.elements.level.value=this.selectedOptions[0].dataset.level;this.form.elements.level.max=this.selectedOptions[0].dataset.max"><?php foreach($nodes as $code=>$def): ?><option value="<?= ah($code) ?>" data-level="<?= (int)($research[$code]??0) ?>" data-max="<?= (int)$def['max_level'] ?>"><?= ah($def['name']) ?> · <?= (int)($research[$code]??0) ?>/<?= (int)$def['max_level'] ?></option><?php endforeach ?></select></label><?php adminNumber('Neue Stufe','level',$research[$first]??0,0,$nodes[$first]['max_level']); ?></div><?php adminSubmit('Forschungsstufe setzen'); ?></section>
<section class="card"><h2>Garnison verwalten</h2><p>Setzt verfügbare Truppen in dieser Stadt. Marschierende, verwundete und noch ausgebildete Truppen bleiben in ihren jeweiligen Warteschlangen.</p><?php $defs=\Conquer\Game\City\TroopData::all();$firstTroop=array_key_first($defs);adminForm('set-troops',$selectedWorld,$playerId); ?><div class="fields"><label>Truppentyp<select name="troop_code" onchange="this.form.elements.count.value=this.selectedOptions[0].dataset.count"><?php foreach($defs as $code=>$def): ?><option value="<?= (int)$code ?>" data-count="<?= (int)($troops[$code]??0) ?>"><?= ah($def['name']??$def['code']) ?> · <?= an($troops[$code]??0) ?></option><?php endforeach ?></select></label><?php adminNumber('Neuer Garnisonsbestand','count',$troops[$firstTroop]??0,0,1000000); ?></div><?php adminSubmit('Garnison setzen'); ?></section>
<section class="card"><h2>Geschenk senden</h2><p>Direkte Belohnung mit Nachricht und dauerhafter Empfangsbestätigung.</p><?php $giftPlayerId=$playerId;require ROOT_DIR.'/views/admin/gift_form.php'; ?></section>
<section class="card wide"><h2>Geschenkbelege</h2><?php if(!$gifts): ?><p class="empty">Noch keine Geschenke in dieser Welt.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Beleg</th><th>Zeit (UTC)</th><th>Geschenk</th><th>Inhalt und Bestände</th></tr></thead><tbody><?php foreach($gifts as $gift): ?><tr><td>#<?= (int)$gift['id'] ?></td><td><?= ah($gift['delivered_at']) ?></td><td><?= ah($gift['title']) ?><br><span class="muted"><?= ah($gift['message']) ?></span></td><td><details><summary>Belohnungen / Vorher / Nachher</summary><pre><?= ah(json_encode(['rewards'=>json_decode($gift['rewards_json'],true),'before'=>json_decode($gift['before_json'],true),'after'=>json_decode($gift['after_json'],true)],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)) ?></pre></details></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section></div>
