<?php
declare(strict_types=1);
$player=$db->query('SELECT id,username,email,is_banned,gems,lord_level,vip_level,vip_points,created_at,last_active_at FROM players WHERE id=?',[$playerId])->fetch();
if(!$player){http_response_code(404);echo '<p class="empty">Spieler nicht gefunden.</p>';return;}
$city=$db->query('SELECT * FROM cities WHERE player_id=? AND world_id=?',[$playerId,$selectedWorld])->fetch();
if(!$city){echo '<div class="notice">Dieser Spieler hat in der ausgewählten Welt keine Stadt. Bitte wähle oben seine Welt aus.</div>';return;}
$cid=(int)$city['id'];$buildings=$db->query('SELECT building_code,level FROM city_buildings WHERE city_id=?',[$cid])->fetchAll(PDO::FETCH_KEY_PAIR);
$research=$db->query('SELECT research_code,level FROM player_research WHERE player_id=? AND world_id=?',[$playerId,$selectedWorld])->fetchAll(PDO::FETCH_KEY_PAIR);
$troops=$db->query('SELECT troop_code,count FROM city_troops WHERE city_id=?',[$cid])->fetchAll(PDO::FETCH_KEY_PAIR);
$queue=$db->query('SELECT building_code,level_to,finishes_at FROM building_queue WHERE city_id=? AND is_processed=0',[$cid])->fetchAll();
$rqueue=$db->query('SELECT research_code,level_to,finishes_at FROM research_queue WHERE player_id=? AND world_id=? AND is_processed=0',[$playerId,$selectedWorld])->fetchAll();
$gifts=$db->query('SELECT * FROM admin_gifts WHERE player_id=? AND world_id=? ORDER BY id DESC LIMIT 20',[$playerId,$selectedWorld])->fetchAll();
$activityMinutes=(int)$db->query('SELECT COUNT(*) FROM player_activity_minutes WHERE player_id=? AND world_id=?',[$playerId,$selectedWorld])->fetchColumn();
$messageCount=(int)$db->query('SELECT (SELECT COUNT(*) FROM world_chat WHERE world_id=? AND player_id=?)+(SELECT COUNT(*) FROM private_chat_messages WHERE world_id=? AND sender_id=?)',[$selectedWorld,$playerId,$selectedWorld,$playerId])->fetchColumn();
$buildingHistory=$db->query('SELECT building_code,level_to,started_at,finishes_at,is_processed FROM building_queue WHERE city_id=? ORDER BY started_at DESC LIMIT 50',[$cid])->fetchAll();
$researchHistory=$db->query('SELECT research_code,level_to,started_at,finishes_at,is_processed FROM research_queue WHERE player_id=? AND world_id=? ORDER BY started_at DESC LIMIT 50',[$playerId,$selectedWorld])->fetchAll();
$trainingHistory=$db->query('SELECT troop_code,count,started_at,finishes_at,is_processed FROM troop_queue WHERE city_id=? ORDER BY started_at DESC LIMIT 50',[$cid])->fetchAll();
$purchases=$db->query('SELECT shop_mode,rotation,offer_id,quantity,updated_at FROM trading_shop_purchases WHERE player_id=? AND scope_world_id IN (0,?) ORDER BY updated_at DESC LIMIT 50',[$playerId,$selectedWorld])->fetchAll();
$monsterKills=$db->query('SELECT monster_code,monster_level,reward_snapshot_json,created_at FROM monster_kill_receipts WHERE winner_player_id=? AND world_id=? ORDER BY created_at DESC LIMIT 50',[$playerId,$selectedWorld])->fetchAll();
$battles=$db->query('SELECT attacker_id,defender_id,outcome,target_x,target_y,created_at FROM battle_reports WHERE world_id=? AND (attacker_id=? OR defender_id=?) ORDER BY created_at DESC LIMIT 50',[$selectedWorld,$playerId,$playerId])->fetchAll();
$farmRows=$db->query("SELECT haul_json,departure_time,arrival_time,return_time FROM marches WHERE player_id=? AND world_id=? AND march_type=9 AND state='complete' ORDER BY return_time DESC LIMIT 50",[$playerId,$selectedWorld])->fetchAll();
$farmTotals=['food'=>0,'lumber'=>0,'stone'=>0,'gold'=>0,'gems'=>0];foreach($farmRows as $farm){$haul=json_decode((string)$farm['haul_json'],true)?:[];foreach(($haul['loot']??[]) as $key=>$amount)if(isset($farmTotals[$key])&&is_numeric($amount))$farmTotals[$key]+=(int)$amount;}
?>
<div class="profile-head"><div class="inline"><span class="avatar"><?= ah(mb_strtoupper(mb_substr($player['username'],0,1))) ?></span><div><h2><?= ah($player['username']) ?></h2><span class="muted">#<?= $playerId ?> · <?= ah($player['email']) ?> · <?= ah($city['name']) ?> (<?= (int)$city['coord_x'] ?>, <?= (int)$city['coord_y'] ?>)</span></div></div><span class="pill <?= $player['is_banned']?'closed':'open' ?>"><?= $player['is_banned']?'Gesperrt':'Aktiv' ?></span></div>
<div class="stats"><div class="stat"><small>BURGSTUFE</small><strong><?= (int)$city['castle_level'] ?></strong><span><?= ah($world['name']) ?></span></div><div class="stat"><small>MACHT</small><strong><?= an($city['power']) ?></strong><span>Gebäudemacht</span></div><div class="stat"><small>EDELSTEINE</small><strong><?= an($player['gems']) ?></strong><span>Kontoweit</span></div><div class="stat"><small>LORD / VIP</small><strong><?= (int)$player['lord_level'] ?> / <?= (int)$player['vip_level'] ?></strong><span>Seit <?= ah(substr($player['created_at'],0,10)) ?></span></div></div>
<div class="grid"><section class="card"><h2>Ressourcen ändern</h2><p>Setzt den absoluten Stadtbestand. Produktion läuft anschließend ab diesem Zeitpunkt weiter.</p><?php adminForm('set-resources',$selectedWorld,$playerId); ?><div class="fields"><?php foreach(['food'=>'Nahrung','lumber'=>'Holz','stone'=>'Stein','gold'=>'Gold'] as $r=>$label)adminNumber($label,$r,$city[$r]); ?></div><?php adminSubmit('Ressourcen setzen'); ?></section><section class="card"><h2>Konto, VIP & Edelsteine</h2><p>Absolute Kontowerte. Jede Änderung wird mit Vorher-/Nachherwerten protokolliert.</p><?php adminForm('set-account-values',$selectedWorld,$playerId); ?><div class="fields"><?php adminNumber('Edelsteine','gems',$player['gems'],0,2000000000);adminNumber('VIP-Stufe','vip_level',$player['vip_level'],1,15);adminNumber('VIP-Punkte','vip_points',$player['vip_points'],0,2000000000); ?></div><?php adminSubmit('Kontowerte speichern'); ?></section><section class="card"><h2>Kontozugang & Schutz</h2><p>Eine Sperre gilt kontoweit und beendet alle Spielsitzungen.</p><?php adminForm($player['is_banned']?'unban':'ban',$selectedWorld,$playerId);adminSubmit($player['is_banned']?'Spieler entsperren':'Spieler sperren'); ?><hr><?php adminForm('grant-shield',$selectedWorld,$playerId);adminNumber('Zusätzlicher Stadtschutz (Stunden)','hours',24,1,720);adminSubmit('Schutz verlängern'); ?><p class="subtle">Aktueller Stadtschutz: <?= ah($city['shield_expires_at']??'Keiner') ?></p></section>
<section class="card"><h2>Gebäude aufwerten</h2><p>Alle 13 echten Gebäudetypen. Eine aktive Bauwarteschlange verhindert Änderungen am betroffenen Gebäude.</p><?php if($queue): ?><div class="hint"><?php foreach($queue as $q): ?><?= ah($q['building_code']) ?> → <?= (int)$q['level_to'] ?> · <?= ah($q['finishes_at']) ?> UTC<br><?php endforeach ?></div><?php endif ?><?php adminForm('set-building',$selectedWorld,$playerId); ?><div class="fields"><label>Gebäude<select name="building_code" onchange="this.form.elements.level.value=this.selectedOptions[0].dataset.level"><?php foreach(\Conquer\Game\City\CityState::BUILDING_NAMES as $code=>$label): ?><option value="<?= ah($code) ?>" data-level="<?= (int)($buildings[$code]??1) ?>"><?= ah($label) ?> · Stufe <?= (int)($buildings[$code]??1) ?></option><?php endforeach ?></select></label><?php adminNumber('Neue Stufe','level',$buildings['castle']??1,1,30); ?></div><?php adminSubmit('Gebäudestufe setzen'); ?></section>
<section class="card"><h2>Forschung verwalten</h2><p>Die Stufengrenzen stammen aus dem aktuellen Forschungskatalog. Laufende Forschung ist geschützt.</p><?php if($rqueue): ?><div class="hint"><?php foreach($rqueue as $q): ?><?= ah($q['research_code']) ?> → <?= (int)$q['level_to'] ?> · <?= ah($q['finishes_at']) ?> UTC<br><?php endforeach ?></div><?php endif ?><?php $nodes=\Conquer\Game\Research\ResearchData::allNodes();$first=array_key_first($nodes);adminForm('set-research',$selectedWorld,$playerId); ?><div class="fields"><label>Forschungsprojekt<select name="research_code" onchange="this.form.elements.level.value=this.selectedOptions[0].dataset.level;this.form.elements.level.max=this.selectedOptions[0].dataset.max"><?php foreach($nodes as $code=>$def): ?><option value="<?= ah($code) ?>" data-level="<?= (int)($research[$code]??0) ?>" data-max="<?= (int)$def['max_level'] ?>"><?= ah($def['name']) ?> · <?= (int)($research[$code]??0) ?>/<?= (int)$def['max_level'] ?></option><?php endforeach ?></select></label><?php adminNumber('Neue Stufe','level',$research[$first]??0,0,$nodes[$first]['max_level']); ?></div><?php adminSubmit('Forschungsstufe setzen'); ?></section>
<section class="card"><h2>Truppen hinzufügen</h2><p>Erhöht die verfügbare Garnison dieser Stadt. Marschierende, verwundete und noch ausgebildete Truppen bleiben unverändert.</p><?php $defs=\Conquer\Game\City\TroopData::all();$firstTroop=array_key_first($defs);adminForm('add-troops',$selectedWorld,$playerId); ?><div class="fields"><label>Truppentyp<select name="troop_code"><?php foreach($defs as $code=>$def): ?><option value="<?= (int)$code ?>"><?= ah($def['name']??$def['code']) ?> · aktuell <?= an($troops[$code]??0) ?></option><?php endforeach ?></select></label><?php adminNumber('Hinzufügen','count',1,1,1000000); ?></div><?php adminSubmit('Truppen hinzufügen'); ?></section>
<section class="card"><h2>Geschenk senden</h2><p>Direkte Belohnung mit Nachricht und dauerhafter Empfangsbestätigung.</p><?php $giftPlayerId=$playerId;require ROOT_DIR.'/views/admin/gift_form.php'; ?></section>
<section class="card wide"><h2>Kingdom-Aktivität</h2><div class="stats"><div class="stat"><small>PROTOKOLLIERTE SPIELZEIT</small><strong><?= ah(number_format($activityMinutes/60,1,',','.')) ?> h</strong><span>aktive Minuten seit Telemetrie-Start</span></div><div class="stat"><small>GESENDETE NACHRICHTEN</small><strong><?= an($messageCount) ?></strong><span>Welt und Privat</span></div><div class="stat"><small>MONSTERKILLS</small><strong><?= an(count($monsterKills)) ?></strong><span>letzte 50 geladen</span></div><div class="stat"><small>FARMMÄRSCHE</small><strong><?= an(count($farmRows)) ?></strong><span>letzte 50 geladen</span></div></div><div class="split"><span>Nahrung / Holz / Stein / Gold</span><strong><?= an($farmTotals['food']) ?> / <?= an($farmTotals['lumber']) ?> / <?= an($farmTotals['stone']) ?> / <?= an($farmTotals['gold']) ?></strong></div><p class="subtle">Konto erstellt: <?= ah($player['created_at']) ?> UTC · zuletzt aktiv: <?= ah($player['last_active_at']??'nicht bekannt') ?> UTC</p></section>
<?php $historyGroups=[['Ausbau-Historie',$buildingHistory,fn($r)=>$r['building_code'].' → Stufe '.$r['level_to']],['Forschungs-Historie',$researchHistory,fn($r)=>$r['research_code'].' → Stufe '.$r['level_to']],['Trainings-Historie',$trainingHistory,fn($r)=>'Truppe '.$r['troop_code'].' · '.an($r['count'])]];foreach($historyGroups as [$title,$rows,$describe]): ?><section class="card"><h2><?= ah($title) ?></h2><?php if(!$rows): ?><p class="empty">Noch keine Einträge.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Vorgang</th><th>Start (UTC)</th><th>Ende (UTC)</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><?= ah($describe($row)) ?></td><td><?= ah($row['started_at']) ?></td><td><?= ah($row['finishes_at']) ?></td><td><?= $row['is_processed']?'Beendet':'Läuft' ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section><?php endforeach ?>
<section class="card"><h2>Kauf-Historie</h2><?php if(!$purchases): ?><p class="empty">Keine Shopkäufe gespeichert.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Shop / Angebot</th><th>Menge</th><th>Letzte Änderung (UTC)</th></tr></thead><tbody><?php foreach($purchases as $row): ?><tr><td><?= ah($row['shop_mode'].' · '.$row['offer_id']) ?><br><span class="muted"><?= ah($row['rotation']) ?></span></td><td><?= an($row['quantity']) ?></td><td><?= ah($row['updated_at']) ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section>
<section class="card"><h2>Monster & Drops</h2><?php if(!$monsterKills): ?><p class="empty">Keine bestätigten Monsterkills.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Monster</th><th>Drop-Snapshot</th><th>Zeit (UTC)</th></tr></thead><tbody><?php foreach($monsterKills as $row): ?><tr><td>#<?= (int)$row['monster_code'] ?> · Stufe <?= (int)$row['monster_level'] ?></td><td><code><?= ah($row['reward_snapshot_json']) ?></code></td><td><?= ah($row['created_at']) ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section>
<section class="card"><h2>Angriffe auf Spieler</h2><?php if(!$battles): ?><p class="empty">Keine PvP-Berichte.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Rolle</th><th>Ergebnis / Ziel</th><th>Zeit (UTC)</th></tr></thead><tbody><?php foreach($battles as $row): ?><tr><td><?= (int)$row['attacker_id']===$playerId?'Angreifer':'Verteidiger' ?></td><td><?= ah($row['outcome']) ?> · <?= (int)$row['target_x'] ?>, <?= (int)$row['target_y'] ?></td><td><?= ah($row['created_at']) ?></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section>
<section class="card wide"><h2>Geschenkbelege</h2><?php if(!$gifts): ?><p class="empty">Noch keine Geschenke in dieser Welt.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Beleg</th><th>Zeit (UTC)</th><th>Geschenk</th><th>Inhalt und Bestände</th></tr></thead><tbody><?php foreach($gifts as $gift): ?><tr><td>#<?= (int)$gift['id'] ?></td><td><?= ah($gift['delivered_at']) ?></td><td><?= ah($gift['title']) ?><br><span class="muted"><?= ah($gift['message']) ?></span></td><td><details><summary>Belohnungen / Vorher / Nachher</summary><pre><?= ah(json_encode(['rewards'=>json_decode($gift['rewards_json'],true),'before'=>json_decode($gift['before_json'],true),'after'=>json_decode($gift['after_json'],true)],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE)) ?></pre></details></td></tr><?php endforeach ?></tbody></table></div><?php endif ?></section></div>
