<?php
declare(strict_types=1);
use Conquer\Game\Rewards\RewardCatalog as R;
// Included by reward_admin.php inside its disposable feature database.
$batch=static function(string $type,array $updates,string $scope='global',?string $op=null,int $admin=1)use($db):array {
    return \Conquer\Admin\AdminService::execute($admin,'reward-batch-save',['source_type'=>$type,'world_id'=>1,'reward_scope'=>$scope,'updates_json'=>json_encode($updates,JSON_THROW_ON_ERROR),'reason'=>'Isolated batch reward check','operation_id'=>$op??bin2hex(random_bytes(16))]);
};
$revision=static fn(string $key,int $world=0):int=>(int)$db->query('SELECT revision FROM '.($world?'reward_world_overrides':'reward_overrides').' WHERE '.($world?'world_id=? AND ':'').'source_type=? AND source_key=?',$world?[$world,'farm',$key]:['farm',$key])->fetchColumn();
$patch=static fn(string $key,int $revision,int $quantity=2,float $chance=12.3456,int $parent=0):array=>['source_key'=>$key,'revision'=>$revision,'parent_revision'=>$parent,'config'=>['fragment_rows'=>[['target'=>'fragment:rare','quantity'=>$quantity,'chance'=>$chance]]]];
$first='20100101.1';$second='20100101.2';$untouched='20100101.3';
$beforeItems=R::effective('farm',$first)['drops'];$other=R::effective('farm',$untouched);
$op=bin2hex(random_bytes(16));$updates=[$patch($first,$revision($first)),$patch($second,$revision($second),3,25)];
$result=$batch('farm',$updates,'global',$op);$replay=$batch('farm',$updates,'global',$op);
ck(!$result['duplicate']&&$replay['duplicate']&&count($result['after'])===2,'Batch saves multiple mine sources and replays the receipt');
ck($revision($first)===$updates[0]['revision']+1&&$revision($second)===$updates[1]['revision']+1,'Batch replay never creates another revision');
ck((int)$db->query("SELECT COUNT(*) FROM admin_audit_log WHERE target_type='reward_batch'")->fetchColumn()===1,'Batch has one durable audit with all source changes');
ck(R::effective('farm',$first)['drops']===$beforeItems&&R::effective('farm',$untouched)===$other,'Fragment-only batch preserves item drops and untouched sources');
ck(R::effective('farm',$first)['fragment_drops'][0]['probability']===.123456,'Batch preserves fractional chances');
$saved=R::effective('farm',$first);$rev=$revision($first);
reject(fn()=>$batch('farm',[$patch($first,$rev,9),$patch($second,$revision($second),2,101)]),'A late invalid batch row rejects the whole operation');
ck($revision($first)===$rev&&R::effective('farm',$first)===$saved,'Failed batch rolls back earlier rows, revisions and runtime cache');
reject(fn()=>$batch('farm',[$patch($first,$rev,9),$patch($second,0)]),'A stale source prevents a partial batch save');
ck($revision($first)===$rev&&R::effective('farm',$first)===$saved,'Stale batch rollback preserves the complete configuration');
reject(fn()=>$batch('farm',[$patch($first,$rev)],'global',null,2),'Moderator cannot save a batch');
$forbidden=$patch($first,$rev);$forbidden['config']['resources']=['gold'=>999];
reject(fn()=>$batch('farm',[$forbidden]),'Batch rejects fields outside independent drop tables');
reject(fn()=>$batch('farm',[$patch($first,$rev),$patch($first,$rev)]),'Batch rejects duplicate sources');
reject(fn()=>$batch('farm',[]),'Batch rejects an empty update list');
reject(fn()=>$batch('farm',array_fill(0,\Conquer\Admin\RewardEditor::MAX_BATCH_SOURCES+1,$patch($first,$rev))),'Batch rejects an oversized source list');
reject(fn()=>$batch('chest',[$patch($first,$rev)]),'Weighted chest rules cannot use the independent-chance editor');
$batch('farm',[$patch($first,0,7,50,$rev)],'world');
ck(R::effective('farm',$first,1)['fragment_drops'][0]['count']===7&&R::effective('farm',$first,0)['fragment_drops'][0]['count']===2,'World batch creates its own rule without changing the global one');
$parent=$revision($second);$batch('farm',[$patch($second,$parent,4,25)]);
$worldBefore=R::effective('farm',$first,1);$worldRev=$revision($first,1);
reject(fn()=>$batch('farm',[$patch($first,$worldRev,9),$patch($second,0,8,25,$parent)],'world'),'Changed inherited global rule rejects a world batch');
ck($revision($first,1)===$worldRev&&R::effective('farm',$first,1)===$worldBefore,'Inherited-rule conflict rolls back earlier world changes');
$monsterKey='20209901';$monsterBefore=R::effective('monster',$monsterKey);$monsterRev=(int)$db->query("SELECT revision FROM reward_overrides WHERE source_type='monster' AND source_key=?",[$monsterKey])->fetchColumn();
$batch('monster',[$patch($monsterKey,$monsterRev,1,4)]);
$monsterAfter=R::effective('monster',$monsterKey);unset($monsterBefore['fragment_drops'],$monsterAfter['fragment_drops']);
ck($monsterBefore===$monsterAfter,'Monster batch preserves direct resources, crystals, charms and items');
$relicPatch=static fn(string $key,int $revision):array=>['source_key'=>$key,'revision'=>$revision,'parent_revision'=>0,'config'=>['relic_rows'=>[['target'=>'relic:60100001','quantity'=>2,'chance'=>12.3456]]]];
$relicBefore=R::effective('farm',$first,0);$relicOp=bin2hex(random_bytes(16));$relicUpdate=$relicPatch($first,$revision($first));
$batch('farm',[$relicUpdate],'global',$relicOp);$relicReplay=$batch('farm',[$relicUpdate],'global',$relicOp);$relicAfter=R::effective('farm',$first,0);
ck($relicAfter['relic_drops']===[['treasure_code'=>60100001,'count'=>2,'probability'=>.123456]]&&$relicReplay['duplicate'],'Whole relic batch preserves exact chance and replays without another save');
ck($relicAfter['drops']===$relicBefore['drops']&&$relicAfter['fragment_drops']===$relicBefore['fragment_drops'],'Whole relic-only edit preserves items and relic fragments');
$relicRevision=$revision($first);$invalidRelic=$relicPatch($second,$revision($second));$invalidRelic['config']['relic_rows'][0]['target']='relic:60500101';
reject(fn()=>$batch('farm',[$relicPatch($first,$relicRevision),$invalidRelic]),'Unavailable whole relic rejects the entire multi-source batch');
ck($revision($first)===$relicRevision&&R::effective('farm',$first,0)===$relicAfter,'Invalid whole relic batch rolls back rules and cache');
$worldRelic=$relicPatch($first,$revision($first,1));$worldRelic['config']['relic_rows'][0]['quantity']=5;
$batch('farm',[$worldRelic],'world');
ck(R::effective('farm',$first,1)['relic_drops'][0]['count']===5&&R::effective('farm',$first,0)['relic_drops'][0]['count']===2,'World whole relic selection is isolated from global rules');
$batch('farm',[['source_key'=>$first,'revision'=>$revision($first),'parent_revision'=>0,'config'=>['relic_rows'=>[]]]]);
ck(R::effective('farm',$first,0)['relic_drops']===[]&&R::effective('farm',$first,0)['fragment_drops']===$relicBefore['fragment_drops'],'Removing whole relic rows clears only the complete relic drops');
