'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-alliance-panel-'));
const catalog=JSON.parse(fs.readFileSync(root+'/data/i18n/en.json','utf8'));
const fixture={world_id:1,player_id:1,power:100,alliance:{id:1,tag:'QA',name:'Alliance',description:'',member_count:1,max_members:30,recruitment_mode:'open',recruitment_language:'en',play_style:'casual',activity_time:'flexible',activity_timezone:'UTC',minimum_power:0},role:'leader',can_manage:true,can_plan:true,notices:[],events:[],polls:[],applications:[],recent_members:[],open_help:[],research:[],pending_applications:[],search:{items:[],next_cursor:null},poll_next:null};
fs.writeFileSync(dir+'/index.html',`<!doctype html><meta charset="utf-8"><main id="content"></main><script>window.ConquerLocale={locale:'en',t:(k,p={})=>(${JSON.stringify(catalog).replaceAll('<','\\u003c')}[k]||k).replace(/\\{(\\w+)\\}/g,(_,n)=>p[n]??'')};</script><script>${fs.readFileSync(root+'/assets/js/alliance-ranks.js','utf8')+'\n'+fs.readFileSync(root+'/assets/js/alliance-community.js','utf8')}</script><script>
window.fixture=${JSON.stringify(fixture)};window.currentWorld=1;window.calls=[];window.writes=[];window.failNext=false;window.clockShift=0;const realNow=Date.now;Date.now=()=>realNow()+clockShift;window.deferNext=false;
window.panel=ConquerAllianceCommunity({esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt:String,getState:()=>({city:{world_id:currentWorld}}),toast:()=>{},api:async(p,b)=>{calls.push(p);if(b){writes.push(b);if(failNext){failNext=false;throw new Error('Lost connection');}fixture.notices.push({id:1,kind:b.kind,title:b.title,body:b.body,pinned:1,completed:0});return {message:'Saved'};}if(deferNext){deferNext=false;const old=structuredClone(fixture);await new Promise(r=>window.releaseRead=r);return old;}return structuredClone(fixture);}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)panel.onClick(b.dataset.action,b);});document.addEventListener('submit',e=>{e.preventDefault();panel.onSubmit(e.target);});panel.render('alliance-community');
</script>`);
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(dir+'/index.html').href);await page.locator('.alliance-social-create summary').click();await page.locator('[name="title"]').fill('A preserved draft');await page.locator('[name="body"]').fill('With details');await page.evaluate(()=>panel.render('alliance-community'));
 assert.equal(await page.locator('.alliance-social-create').getAttribute('open'),'');assert.equal(await page.locator('[name="title"]').inputValue(),'A preserved draft');
 await page.evaluate(()=>window.failNext=true);await page.locator('[data-form="alliance-social-notice"] button[type="submit"]').click();await page.getByRole('alert').filter({hasText:'Lost connection'}).waitFor();await page.locator('[data-form="alliance-social-notice"] button[type="submit"]').click();await page.getByRole('heading',{name:'A preserved draft'}).waitFor();
 const writes=await page.evaluate(()=>window.writes);assert.equal(writes.length,2);assert.equal(writes[0].request_id,writes[1].request_id);
 await page.evaluate(()=>{currentWorld=2;fixture={...fixture,world_id:2,alliance:null,can_manage:false,can_plan:false,notices:[]};panel.render('alliance-community');});await page.locator('[data-form="alliance-social-search"]').waitFor();assert.match(await page.locator('.alliance-social-heading').innerText(),/Find an alliance/);assert.equal(await page.locator('[data-action="alliance-create"]').count(),1);
 await page.locator('[data-form="alliance-social-search"] [name="search"]').fill('World two draft');await page.evaluate(()=>{deferNext=true;clockShift+=20000;panel.render('alliance-community');});await page.waitForFunction(()=>typeof releaseRead==='function');
 await page.evaluate(()=>{currentWorld=3;fixture={...fixture,world_id:3};panel.render('alliance-community');releaseRead();});await page.waitForFunction(()=>calls.some(p=>p.includes('world_id=3')));await page.locator('[data-form="alliance-social-search"]').waitFor();assert.equal(await page.locator('[name="search"]').inputValue(),'','world switch cannot copy another world draft');assert.equal(await page.locator('.alliance-social-error:not(:empty)').count(),0);
 assert.deepEqual(errors,[]);console.log('PASS alliance panel draft/expanded form preservation, lost-response receipt, automatic discovery, cache refresh and pending world-switch read.');
 }finally{await browser.close();fs.unlinkSync(dir+'/index.html');fs.rmdirSync(dir);}})().catch(e=>{console.error(e);process.exitCode=1;});
