'use strict';
require('./fixtures/browser_locale.cjs')('de'); // This suite asserts the explicit German UI.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.BUG_REPORT_URL||'http://127.0.0.1:18976';
assert(/^http:\/\/127\.0\.0\.1:\d+$/.test(base),'Disposable local preview required');
const output=path.resolve(__dirname,'../artifacts/bug-reports');fs.mkdirSync(output,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'}),errors=[];
 try{
  const page=await browser.newPage({viewport:{width:1280,height:800},hasTouch:true});page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);
  await page.goto(base+'/?zugang=login#zugang');await page.locator("[name=identifier], [name=username]").fill('PreviewPlayer');await page.locator('[name="password"]').fill('PreviewFixture!2026');
  await Promise.all([page.waitForURL('**/city'),page.locator("form[action$=\"/auth/local\"] button[type=\"submit\"]").click()]);await page.locator('.painted-village').waitFor();
  assert.equal(await page.locator('[data-action="bug-report-open"]').count(),1,'Only the main screen has a report button');
  assert.equal(await page.locator('#panel-dialog [data-action="bug-report-open"], #game-dialog [data-action="bug-report-open"]').count(),0,'Panel and dialog headers have no report buttons');
  await page.locator('#hud-menu').click();await page.locator('.menu-groups').waitFor();
  assert.equal(await page.locator('.menu-groups [data-action="bug-report-open"], .menu-groups [data-id="bugreport"]').count(),0,'The game menu has no report entry');
  await page.locator('.menu-groups [data-id="settings"]').click();await page.locator('#panel-dialog[data-panel="settings"] form[data-form="settings"]').waitFor();
  assert.equal(await page.locator('#panel-dialog [data-id="bugreport"], #panel-dialog [data-action="bug-report-open"]').count(),0,'Settings have no report entry');
  await page.locator('#panel-dialog .panel-close').click();await page.locator('#hud-report').click();await page.locator('.bug-capture-consent').waitFor();assert.match(await page.locator('.bug-capture-consent').innerText(),/welchen Tab oder Bildschirm/);await page.locator('[data-action="bug-report-without-screenshot"]').click();await page.locator('.bug-report-panel').waitFor();
  for(const [width,height] of [[1280,800],[390,844],[320,700],[568,320]]){
   await page.setViewportSize({width,height});
   const issues=await page.evaluate(()=>{const panel=document.querySelector('#panel-dialog'),form=document.querySelector('.bug-report-panel form'),submit=form?.querySelector('button[type=submit]'),bad=[];if(panel.scrollWidth>panel.clientWidth+2)bad.push('panel overflow');if(form.scrollWidth>form.clientWidth+2)bad.push('form overflow');const r=submit.getBoundingClientRect();if(r.right>innerWidth+2||r.left<0)bad.push('submit horizontal reach');return bad;});
   assert.deepEqual(issues,[],`responsive bug form at ${width}x${height}`);await page.screenshot({path:path.join(output,`player-${width}x${height}.png`)});
  }
  await page.setViewportSize({width:390,height:844});await page.locator('[name="report_type"]').selectOption('idea');await page.locator('[name="category"]').selectOption('interface');await page.locator('[name="severity"]').selectOption('blocking');await page.locator('[name="title"]').fill('Inventarknopf reagiert nicht');await page.locator('[name="description"]').fill('Nach der Auswahl eines Gegenstands bleibt der Aktionsknopf weiterhin gesperrt.');await page.locator('[name="reproduction_steps"]').fill('Inventar öffnen, Gegenstand antippen und Aktionsknopf prüfen.');await page.locator('[name="expected_result"]').fill('Der Aktionsknopf wird verfügbar.');const submitResponse=page.waitForResponse(r=>r.url().endsWith('/api/bug-reports'));await page.locator('form[data-form="bug-report"] button[type="submit"]').click();const submitted=await submitResponse;assert.equal(submitted.status(),200,(await submitted.text())+'\n'+submitted.request().postData());
  await page.locator('.bug-report-success').waitFor();const receipt='#'+(await submitted.json()).data.id;assert.match(receipt,/^#\d+$/);assert.equal(await page.locator('.bug-report-success p').innerText(),await page.evaluate(reference=>ConquerLocale.t('bugreport.thanks',{reference}),receipt),'Localized receipt contains the exact server report number');await page.screenshot({path:path.join(output,'player-success.png')});
  const admin=await browser.newPage({viewport:{width:1280,height:900}});admin.on('pageerror',e=>errors.push(e.message));await admin.goto(base+'/admin/login');await admin.locator("[name=identifier], [name=username]").fill('PreviewAdmin');await admin.locator('[name="password"]').fill('PreviewFixture!2026');await admin.getByRole('button',{name:'Anmelden',exact:true}).click();await admin.waitForURL(base+'/admin');
  assert.equal(await admin.locator('#admin-nav [data-admin-area="reports"] .admin-nav-count').innerText(),'1');await admin.goto(base+'/admin/bug-reports?world_id=1#meldung-'+receipt.slice(1));const card=admin.locator('.case-detail');await card.waitFor();assert.match(await card.innerText(),/Inventarknopf reagiert nicht/);await admin.getByText('Mitgesendete technische Angaben',{exact:true}).click();assert.match(await admin.locator('.case-context').innerText(),/390x844/);
  const update=admin.locator('[data-case-form]').filter({has:admin.locator('[name="case_action"][value="update"]')});await update.locator('[name="status"]').selectOption('in_progress');await update.locator('[name="priority"]').selectOption('urgent');await update.locator('[name="reason"]').fill('Meldung geprüft');await update.locator('button[type="submit"]').click();await admin.waitForURL('**/admin/cases?source=bug&case_id='+receipt.slice(1));assert.match(await admin.locator('.notice.success').innerText(),/gespeichert/);assert.equal(await admin.locator('.case-context [name="status"]').inputValue(),'in_progress');
  const note=admin.locator('[data-case-form]').filter({has:admin.locator('[name="case_action"][value="note"]')});await note.locator('..').locator('summary').click();await note.locator('[name="body"]').fill('Auf schmalem Bildschirm reproduziert.');await note.locator('[name="reason"]').fill('Interne Analyse ergänzt');await note.locator('button[type="submit"]').click();await admin.waitForURL('**/admin/cases?source=bug&case_id='+receipt.slice(1));assert.match(await admin.locator('.case-message.internal').innerText(),/Auf schmalem Bildschirm reproduziert/);await admin.screenshot({path:path.join(output,'admin-inbox.png'),fullPage:true});
  await admin.setViewportSize({width:320,height:700});assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,'admin inbox has no horizontal overflow at 320px');await admin.screenshot({path:path.join(output,'admin-320x700.png'),fullPage:true});
  assert.deepEqual(errors,[],'No browser errors');console.log('ALL BUG REPORT BROWSER CHECKS PASSED · '+output);
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
