'use strict';
// Real browser rendering and form contracts against a fixture API, never a player account.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-community-panel-'));
const css=[...new Set([...fs.readFileSync(root+'/views/game.php','utf8').matchAll(/assets\/css\/([a-z0-9-]+)\.css/g)].map(m=>m[1]).concat('community-panel'))].map(f=>fs.readFileSync(root+'/assets/css/'+f+'.css','utf8')).join('\n');
const fixture={world_id:1,player_id:1,world_chat:[{id:1,player_id:2,username:'<img src=x onerror="window.xss=1">',message:'<script>window.xss=1</script> & Guten Tag!',shared_report_id:23,created_at:'2026-09-11 12:00:00'}],alliance_chat:[],alliance:{id:1,name:'Die Gemeinschaft',tag:'GEM'},role:'leader',members:[{player_id:1,username:'Anführer',role:'leader',coord_x:50,coord_y:50},{player_id:2,username:'Member Two',role:'member',coord_x:51,coord_y:50},{player_id:3,username:'Member Three',role:'officer',coord_x:52,coord_y:50}],players:[{id:2,username:'Member Two'},{id:3,username:'Member Three'}],mail:[{id:7,sender_id:2,recipient_id:1,sender_name:'Member Two',recipient_name:'Anführer',subject:'Ein Brief <svg onload=window.xss=1>',body:'Hallo!\n<script>window.xss=1</script>',read_at:null,created_at:'2026-09-11 12:00:00'}],unread:1,gifts:[{id:1,title:'Willkommen <img src=x>',message:'Ein Geschenk der Spielleitung.',rewards:{food:5000,gems:100,item_code:1,quantity:2},item_name:'Vorratspaket',delivered_at:'2026-09-11 12:00:00'}],queues:[{id:9,type:'building',label:'farm',finishes_at:'2099-01-01 00:00:00'}],help_requests:[{id:1,player_id:2,username:'Member Two',queue_type:'building',help_count:2,max_helps:30,reduced_seconds:60,finishes_at:'2099-01-01 00:00:00',already_helped:0}],research:{nodes:{ally_food_prod:{code:'ally_food_prod',name:'Gemeinsame Ernte',tree:'economy',level:0,max_level:20,bonus_label:' +{n}% Produktion',bonus_current:0,bonus_next:1,cost_next:{lumber:750,stone:750,gold:750},duration_seconds:900,description:'Ein Prozent mehr Produktion.',in_queue:false}},active_code:null},territory:{structures:[],center_radius:12,outpost_radius:6,outpost_limit:1,outpost_count:0},treasury:{food:5000,lumber:5000,stone:5000,gold:5000},alliances:[{id:2,tag:'NBR',name:'Nachbarallianz'}],treaties:[],proposals:[{id:5,alliance_id:2,target_id:1,alliance_name:'Nachbarallianz',target_name:'Die Gemeinschaft',relation:'nap',expires_at:'2099-01-01 00:00:00'}],shipments:[{id:1,sender_id:1,recipient_id:2,sender_name:'Anführer',recipient_name:'Member Two',resource:'gold',amount:1000,status:'travelling',arrives_at:'2099-01-01 00:00:00'}]};
fs.writeFileSync(out+'/fixture.html',`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}\nbody{display:block!important;overflow:auto!important;background:#e9dbc1;padding:16px}#content{position:static!important;width:100%;max-width:1100px;margin:auto;min-height:400px;overflow:visible!important;box-sizing:border-box}#game-dialog{max-width:700px;width:90%;max-height:85vh}</style><body><main id="content"></main><dialog id="game-dialog"><div id="dialog-content"></div></dialog><script>${fs.readFileSync(root+'/assets/js/community-panel.js','utf8')}</script><script>
window.fixture=${JSON.stringify(fixture).replaceAll('<' , '\\u003c')};window.calls=[];window.failNext=false;window.messages=[];window.openedReports=[];window.xss=0;
window.panel=ConquerCommunity({esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt:n=>Number(n).toLocaleString('de-DE'),date:v=>Date.parse(v.replace(' ','T')+'Z'),countdown:()=>'<span>5 Min.</span>',getState:()=>({city:{world_id:1}}),api:async(path,payload)=>{if(payload){calls.push({path,payload});if(failNext){failNext=false;throw new Error('Fixture connection interrupted');}return {message:'Gespeichert'};}return structuredClone(fixture);},toast:m=>messages.push(m),refresh:async()=>{},openSharedReport:id=>openedReports.push(id),openDialog:html=>{const d=document.querySelector('#game-dialog');document.querySelector('#dialog-content').innerHTML=html;d.showModal();}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b){if(b.dataset.action==='close-dialog')document.querySelector('#game-dialog').close();else panel.onClick(b.dataset.action,b);}});document.addEventListener('submit',e=>{e.preventDefault();panel.onSubmit(e.target)});panel.render('community');</script></body></html>`);
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});try{
    const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(out+'/fixture.html').href);await page.waitForSelector('.community-message');
    assert.equal(await page.evaluate(()=>window.xss),0);assert.equal(await page.locator('.community-message img,.community-message script').count(),0);
    await page.locator('.community-report-link').click();await page.waitForFunction(()=>openedReports[0]===23);
    for(const [width,height]of [[320,568],[390,844],[568,320],[1280,800]]){
        await page.setViewportSize({width,height});for(const tab of ['world','alliance','mail','help','research','buildings','members','diplomacy','shipments']){
            await page.locator('[data-action="community-tab"][data-id="'+tab+'"]').click();
            const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,`${width}×${height} ${tab} has horizontal overflow`);
            assert.equal(await page.evaluate(()=>window.xss),0);assert.ok(await page.locator('.community-heading h2').textContent());
            if((width===1280&&['mail','research'].includes(tab))||(width===390&&['buildings','shipments'].includes(tab)))await page.screenshot({path:out+'/'+width+'-'+tab+'.png',fullPage:true});
        }
    }
    await page.setViewportSize({width:1280,height:800});
    await page.locator('[data-action="community-tab"][data-id="world"]').click();await page.locator('textarea[name="message"]').fill('World draft');
    await page.locator('[data-action="community-tab"][data-id="alliance"]').click();assert.equal(await page.locator('input[name="channel"]').inputValue(),'alliance');await page.locator('textarea[name="message"]').fill('Alliance draft');
    await page.locator('[data-action="community-tab"][data-id="world"]').click();assert.equal(await page.locator('textarea[name="message"]').inputValue(),'World draft');assert.equal(await page.locator('input[name="channel"]').inputValue(),'world');
    await page.evaluate(()=>window.failNext=true);await page.locator('form[data-form="community-chat"] button').click();await page.waitForFunction(()=>messages.includes('Fixture connection interrupted'));await page.locator('form[data-form="community-chat"] button').click();await page.waitForFunction(()=>calls.length===2);
    const retry=await page.evaluate(()=>calls.slice(0,2));assert.equal(retry[0].payload.request_id,retry[1].payload.request_id);assert.equal(retry[1].payload.channel,'world');assert.equal(retry[1].payload.message,'World draft');
    await page.locator('[data-action="community-tab"][data-id="members"]').click();await page.locator('form[data-id="2"] select[name="role"]').selectOption('veteran');await page.locator('form[data-id="3"] select[name="role"]').selectOption('member');
    await page.locator('[data-action="community-tab"][data-id="help"]').click();await page.locator('[data-action="community-tab"][data-id="members"]').click();
    assert.equal(await page.locator('form[data-id="2"] input[name="player_id"]').inputValue(),'2');assert.equal(await page.locator('form[data-id="3"] input[name="player_id"]').inputValue(),'3');assert.equal(await page.locator('form[data-id="2"] select[name="role"]').inputValue(),'veteran');assert.equal(await page.locator('form[data-id="3"] select[name="role"]').inputValue(),'member');
    await page.locator('form[data-id="2"] button').click();await page.waitForFunction(()=>calls.some(c=>c.payload.action==='alliance.role'));const role=await page.evaluate(()=>calls.find(c=>c.payload.action==='alliance.role').payload);assert.equal(role.player_id,2);assert.equal(role.role,'veteran');
    await page.locator('[data-action="community-tab"][data-id="mail"]').click();await page.locator('[data-action="community-mail-open"]').click();await page.waitForFunction(()=>calls.some(c=>c.payload.action==='mail.read'));assert.ok((await page.locator('.community-letter').textContent()).includes('<script>'));assert.equal(await page.locator('.community-letter script').count(),0);assert.equal(await page.evaluate(()=>window.xss),0);
    await page.locator('[data-action="community-mail-reply"]').click();assert.equal(await page.locator('select[name="player_id"]').inputValue(),'2');assert.ok((await page.locator('input[name="subject"]').inputValue()).startsWith('Re: Ein Brief'));
    await page.locator('[data-action="community-tab"][data-id="shipments"]').click();await page.locator('select[name="player_id"]').selectOption('2');await page.locator('select[name="resource"]').selectOption('gold');await page.locator('input[name="amount"]').fill('750');await page.locator('form[data-form="community-shipment"] button').click();await page.waitForFunction(()=>calls.some(c=>c.payload.action==='shipment.send'));const shipment=await page.evaluate(()=>calls.find(c=>c.payload.action==='shipment.send').payload);assert.equal(shipment.player_id,2);assert.equal(shipment.amount,750);assert.equal(shipment.resource,'gold');assert.equal(shipment.world_id,1);assert.ok(shipment.request_id.length>=16);
    await page.locator('[data-action="community-tab"][data-id="buildings"]').click();await page.locator('select[name="structure_type"]').selectOption('center');await page.locator('input[name="coord_x"]').fill('64');await page.locator('input[name="coord_y"]').fill('72');await page.locator('form[data-form="community-structure"] button').click();await page.waitForFunction(()=>calls.some(c=>c.payload.action==='structure.place'));const structure=await page.evaluate(()=>calls.find(c=>c.payload.action==='structure.place').payload);assert.equal(structure.structure_type,'center');assert.equal(structure.coord_x,64);assert.equal(structure.coord_y,72);
    assert.deepEqual(errors,[]);console.log('PASS 36 responsive community layouts, alliance buildings, XSS escaping, private letters/admin gifts, separate drafts, role targets, shipment payloads and retry receipts. '+out);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
