'use strict';
// Isolated modal rendering and action-contract checks. No live account or API.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-congress-panel-'));
const css=[...fs.readFileSync(root+'/views/game.php','utf8').matchAll(/assets\/css\/([a-z0-9-]+)\.css/g)].map(m=>fs.readFileSync(root+'/assets/css/'+m[1]+'.css','utf8')).join('\n');
const js=fs.readFileSync(root+'/assets/js/congress-panel.js','utf8');
fs.writeFileSync(out+'/fixture.html',`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}</style><body class="mobile-game"><dialog id="game-dialog"><button class="dialog-close">×</button><div id="dialog-content"></div></dialog><script>${js}</script><script>
window.g={id:7,coord_x:128,coord_y:128,state:'neutral',own_alliance_id:null,garrison_total:1500000,hold_seconds:3600,my_garrison:{total:0},can_attack:false,can_garrison:false,can_recall:false};window.shrines=[];window.calls=[];window.marches=[];
window.panel=ConquerCongress({base:${JSON.stringify(pathToFileURL(root).href)},esc:s=>String(s??'').replaceAll('<','&lt;'),fmt:n=>Number(n).toLocaleString('de-DE'),duration:s=>Math.ceil(s/60)+' Min.',getState:()=>({congress:g,shrines}),toast:()=>{},action:(path,payload)=>{calls.push({path,payload})},marchPanel:{open:(...args)=>marches.push(args)},openDialog:html=>{const d=document.querySelector('#game-dialog'),c=document.querySelector('#dialog-content');d.querySelector('.popup-heading')?.remove();c.innerHTML=html;const h=document.createElement('header');h.className='popup-heading';h.append(c.querySelector('h2'));d.insertBefore(h,c);d.classList.add('has-popup-heading');if(!d.open)d.showModal();}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)panel.onClick(b.dataset.action,b)});panel.open();</script></body></html>`);
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(out+'/fixture.html').href);
 for(const [width,height]of [[320,568],[390,844],[568,320],[1280,720]])for(const mode of ['visitor','attacker','owner']){
  await page.setViewportSize({width,height});await page.evaluate(mode=>{g.own_alliance_id=mode==='visitor'?null:3;g.alliance_id=mode==='owner'?3:null;g.alliance_name=mode==='owner'?'Wächter des Weltensees':null;g.alliance_tag='SEE';g.state=mode==='owner'?'contested':'neutral';g.contested_until=mode==='owner'?'2030-01-01 00:00:00':null;g.can_attack=mode==='attacker';g.can_garrison=g.can_recall=mode==='owner';g.my_garrison={total:mode==='owner'?12000:0};panel.open();},mode);
  const metrics=await page.evaluate(()=>{const d=document.querySelector('#game-dialog'),r=d.getBoundingClientRect();return {overflow:[...d.querySelectorAll('#dialog-content,.congress-panel,.congress-hero,.congress-rules')].filter(e=>e.scrollHeight>e.clientHeight+2||e.scrollWidth>e.clientWidth+2).map(e=>e.className||e.id),outside:[...d.querySelectorAll('button')].filter(e=>{const b=e.getBoundingClientRect();return b.left<r.left||b.right>r.right||b.top<r.top||b.bottom>r.bottom}).map(e=>e.textContent),viewport:r.bottom>innerHeight||r.right>innerWidth};});
  await page.screenshot({path:out+'/'+width+'x'+height+'-'+mode+'.png'});assert.deepEqual(metrics,{overflow:[],outside:[],viewport:false},JSON.stringify({width,height,mode,metrics}));await page.screenshot({path:out+'/'+width+'x'+height+'-'+mode+'.png'});
 }
 await page.evaluate(()=>{g.can_attack=true;panel.onClick('congress-attack');g.can_attack=false;panel.onClick('congress-attack');g.can_garrison=true;panel.onClick('congress-garrison');panel.onClick('congress-recall');});
 const actions=await page.evaluate(()=>({marches,calls}));assert.equal(actions.marches.length,2);assert.equal(actions.marches[0][1],'congress');assert.equal(actions.marches[1][1],'congress-garrison');assert.equal(actions.calls[0].path,'shrines/7/recall');assert.deepEqual(errors,[]);
 for(const [width,height]of [[320,568],[390,844],[568,320],[1280,720]])for(const mode of ['peace','active','owner','visitor']){
  await page.setViewportSize({width,height});await page.evaluate(mode=>{shrines=[{...g,id:21,name:'Schrein des Lebens',element:'forest',coord_x:101,coord_y:101,own_alliance_id:mode==='visitor'?null:3,alliance_id:mode==='owner'?3:null,can_attack:mode==='active',can_garrison:mode==='owner',can_recall:mode==='owner',event:{name:'Krieg der vier Schreine',active:mode==='active',starts_at:'2020-01-01 16:00:00',ends_at:'2099-01-01 20:00:00',next_starts_at:'2099-01-08 16:00:00'}}];panel.onClick('shrine-open',{dataset:{id:'21'}})},mode);
  const overflow=await page.evaluate(()=>[...document.querySelectorAll('#dialog-content,.congress-panel,.congress-hero,.congress-rules,.congress-actions')].filter(e=>e.scrollHeight>e.clientHeight+2||e.scrollWidth>e.clientWidth+2).map(e=>e.className||e.id));
  await page.screenshot({path:out+'/'+width+'x'+height+'-shrine-'+mode+'.png'});assert.deepEqual(overflow,[],JSON.stringify({width,height,mode,overflow}));
  assert.equal(await page.locator('[data-action="shrine-attack"]').count(),mode==='active'?1:0);
 }
 await page.evaluate(()=>{marches=[];calls=[];shrines[0].can_attack=true;shrines[0].event.active=true;panel.onClick('shrine-attack',{dataset:{id:'21'}});shrines[0].event.ends_at='2000-01-01 00:00:00';panel.onClick('shrine-attack');shrines[0].can_garrison=true;panel.onClick('shrine-garrison');shrines[0].can_recall=true;panel.onClick('shrine-recall');panel.onClick('congress-open')});
 const shrineActions=await page.evaluate(()=>({marches,calls}));assert.equal(shrineActions.marches.length,2);assert.equal(shrineActions.marches[0][1],'shrine');assert.equal(shrineActions.marches[1][1],'shrine-garrison');assert.equal(shrineActions.calls[0].path,'shrines/21/recall');assert.equal(await page.locator('h2').textContent(),'Kongress des Weltensees');assert.deepEqual(errors,[]);console.log('PASS 28 Congress/shrine layouts, permission gates, attack/garrison/recall action contracts. '+out);
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
