'use strict';
// Isolated browser fixture, mocked APIs, no saved game writes.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-defense-panel-'));
const css=['game','game-theme','defense-panel'].map(n=>fs.readFileSync(path.join(root,'assets/css',n+'.css'),'utf8')).join('\n');
const defs=JSON.parse(fs.readFileSync(path.join(root,'data/troops.json'),'utf8')).troops;
const troops=defs.map(t=>({code:t.code,name:t.name,tier:t.tier,available:100,promotion:t.tier<5?{target_code:t.code+100,name:'Veteran '+t.name,unlocked:t.tier===1,cost:{food:25,lumber:15,stone:5,gold:5},duration_seconds:18,max_count:500,building_level:13,castle_level:13}:null}));
const data={city_id:1,world_id:1,wall:{level:5,durability:22000,durability_max:25000,defense_buff:8.8},shield:{active:false,expires_at:null,beginner_until:null},protected_resources:{food:5000,lumber:6000,stone:4000,gold:3000},protection_fraction:.15,troops,formations:[{slot:1,name:'Waldwache <script>',troops:{50100101:30,50200101:40}}],limits:{march_capacity:50000,march_slots:3},reinforcements:[{id:9,sender_name:'Frühling',target_name:'Waldwacht',troops:{50100101:50,50200101:30},can_recall:true}],promotions:[],training_busy:false,targets:[{player_id:7,name:'Waldwacht',coord_x:100,coord_y:200}],alliance_id:1};
const script=fs.readFileSync(path.join(root,'assets/js/defense-panel.js'),'utf8');
fs.writeFileSync(path.join(out,'fixture.html'),`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}html,body{overflow:auto;height:auto;background:#e7dbc5}#content{display:block;box-sizing:border-box;width:100%;max-width:1100px;margin:0 auto;padding:12px;overflow:visible;position:relative}</style><div id="content"></div><script>${script}</script><script>window.data=${JSON.stringify(data)};window.calls=[];window.notices=[];window.reads=0;const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');window.panel=ConquerDefense({api:async(path,payload)=>{if(payload){calls.push({path,payload});return{message:'OK'}}reads++;return structuredClone(data)},esc,fmt:n=>Number(n).toLocaleString('de-DE'),duration:n=>n+' Sek.',toast:n=>notices.push(n),refresh:async()=>{}});document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)panel.onClick(b.dataset.action,b)});document.addEventListener('submit',e=>{e.preventDefault();panel.onSubmit(e.target)});panel.render();</script></html>`);
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
    await page.goto(pathToFileURL(path.join(out,'fixture.html')).href);await page.locator('.defense-cards').waitFor();
    for(const [width,height] of [[360,800],[390,844],[667,375],[768,1024],[1280,800]]){
        await page.setViewportSize({width,height});
        for(const section of ['wall','support','formations','promotion']){
            await page.locator(`[data-action="defense-tab"][data-id="${section}"]`).click();
            if(section==='support')await page.locator('summary').click();
            const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);assert(!overflow,`${section} horizontal overflow at ${width}×${height}`);
            const controls=await page.locator('.defense-panel input,.defense-panel select,.defense-panel button').evaluateAll(els=>els.filter(el=>el.getClientRects().length).map(el=>{const r=el.getBoundingClientRect();return{left:r.left,right:r.right,width:r.width}}));
            assert(controls.every(c=>c.left>=-1&&c.right<=width+1),`${section} controls outside width ${width}`);
        }
    }
    await page.setViewportSize({width:390,height:844});await page.locator('[data-action="defense-tab"][data-id="formations"]').click();
    await page.locator('input[name="name"]').fill('Unfertige Eingabe');const reads=await page.evaluate(()=>window.reads);await page.evaluate(()=>panel.render());assert.equal(await page.locator('input[name="name"]').inputValue(),'Unfertige Eingabe');assert.equal(await page.evaluate(()=>window.reads),reads);
    await page.locator('[data-action="defense-preset"]').click();assert.equal(await page.locator('input[name="troop_50100101"]').inputValue(),'30');assert.equal(await page.locator('input[name="name"]').inputValue(),'Waldwache <script>');assert.equal(await page.locator('script').count(),2);
    await page.locator('form[data-form="defense-formation"] button[type="submit"]').click();await page.waitForFunction(()=>calls.length===1);let request=await page.evaluate(()=>calls[0]);assert.deepEqual(request.payload,{city_id:1,action:'formation.save',slot:1,name:'Waldwache <script>',troops:{50100101:30,50200101:40}});
    await page.locator('[data-action="defense-tab"][data-id="wall"]').click();await page.locator('form[data-form="defense-wall"] button').click();await page.waitForFunction(()=>calls.length===2);assert.equal((await page.evaluate(()=>calls[1])).payload.hp_amount,1000);
    await page.locator('[data-action="defense-tab"][data-id="support"]').click();await page.locator('select[name="mission"]').selectOption('reinforce');await page.locator('input[name="target_player_id"]').fill('7');await page.locator('summary').click();await page.locator('[data-action="defense-preset"]').click();await page.locator('form[data-form="defense-dispatch"] button[type="submit"]').click();await page.waitForFunction(()=>calls.length===3);request=await page.evaluate(()=>calls[2]);assert.equal(request.payload.action,'reinforce');assert.deepEqual(request.payload.troops,{50100101:30,50200101:40});
    await page.locator('[data-action="defense-recall"]').click();await page.waitForFunction(()=>calls.length===4);assert.equal((await page.evaluate(()=>calls[3])).payload.reinforcement_id,9);
    await page.locator('[data-action="defense-tab"][data-id="promotion"]').click();assert(await page.locator('form[data-form="defense-promotion"] button[disabled]').count()>0);await page.locator('form[data-form="defense-promotion"] button:not([disabled])').first().click();await page.waitForFunction(()=>calls.length===5);assert.equal((await page.evaluate(()=>calls[4])).payload.action,'promotion.start');
    await page.screenshot({path:path.join(out,'defense-mobile.png'),fullPage:true});assert.deepEqual(errors,[]);console.log('PASS 20 defense layouts, form preservation, escaped preset text, saved compositions, repair/reinforce/recall/promotion action contracts. '+out);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
