'use strict';
// Self-contained browser fixture. Its API is memory-only and never reaches a game account.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const displayedTotal=async form=>Number(((await form.locator('[data-dungeon-total]').textContent()).match(/[\d.]+/)||['0'])[0].replace(/\./g,''));
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-dungeon-panel-'));
const css=['game','game-theme','dungeon-panel','dungeon-planner','village-theme'].map(n=>fs.readFileSync(path.join(root,'assets/css',n+'.css'),'utf8')).join('\n');
const script=fs.readFileSync(path.join(root,'assets/js/dungeon-panel.js'),'utf8');
const guidance={profile_name:'Ausgewogene Vorhut',reason:'Eine feste Front schützt schnelle Fernkämpfer.',mix:[{type:1,percent:40},{type:2,percent:35},{type:3,percent:25}],requirements:{normal:{skip:120,explore:180},hard:{skip:360,explore:540}},basis:'Empfehlung aus den Gegnerwerten dieser Woche'};
const dungeon={dungeon_code:'roots',name:'Wurzelgewölbe <script>',theme:'Smaragdwald',description:'Zwischen alten Wurzeln wartet ein vergessener Hort.',base_duration:7200,guidance};
const state={world_id:7,player_id:5,week_key:'2099-W37',rotation_ends_at:'2099-09-14T00:00:00Z',rotation:[dungeon,{...dungeon,dungeon_code:'frost',name:'Frostspalte'},{...dungeon,dungeon_code:'embers',name:'Gluttempel'}],next_rotation:[{...dungeon,dungeon_code:'hall',name:'Versunkene Halle'}],available_troops:{50100101:60000,50200101:10000},eligible_roles:['attack','defense','gather','hunter'],runs:[{id:40,dungeon_code:'roots',dungeon,leader_player_id:8,difficulty:'hard',stance:'balanced',status:'recruiting',members:[{player_id:8,username:'Mara',role:'defense',total_troops:300,is_self:false}],votes:[],progress:{encounters_done:0,encounters_total:3},can_start:false,can_leave:false,can_cancel:false,can_vote:false,can_claim:false},{id:41,dungeon_code:'frost',dungeon:{...dungeon,dungeon_code:'frost',name:'Frostspalte'},leader_player_id:6,difficulty:'normal',stance:'cautious',status:'decision',decision_deadline:'2099-09-12 20:00:00',members:[{player_id:5,username:'Du',role:'hunter',total_troops:200,is_self:true},{player_id:6,username:'Edda',role:'attack',total_troops:500,is_self:false}],votes:[],progress:{encounters_done:1,encounters_total:3},can_vote:true,can_claim:false},{id:90,dungeon_code:'moon',dungeon:{...dungeon,dungeon_code:'moon',name:'Mondmine'},leader_player_id:5,difficulty:'normal',stance:'balanced',status:'completed',completed_at:'2099-09-10 10:00:00',members:[{player_id:5,username:'Du',role:'attack',total_troops:100,is_self:true}],votes:[],progress:{encounters_done:3,encounters_total:3},reward:{fragments:12,item_quantity:1,claimed_at:null},can_claim:true}]};
fs.writeFileSync(path.join(out,'fixture.html'),`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}html,body{overflow:auto;height:auto;background:#eadfc9}#content{display:block;box-sizing:border-box;width:100%;max-width:1100px;margin:auto;padding:12px;overflow:auto;height:100vh}</style><div id="content"></div><script>${script}</script><script>window.K={city:{world_id:7},troop_defs:[{code:50100101,type:1,tier:1,name:'Infanterie'},{code:50200101,type:2,tier:1,name:'Bogenschützen'}]};window.calls=[];window.previewCalls=[];window.notices=[];window.fixtureState=${JSON.stringify(state)};window.resetFixture=()=>window.fixtureState=${JSON.stringify(state)};let pending=false;const clone=x=>JSON.parse(JSON.stringify(x));const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));window.panel=ConquerDungeons({base:${JSON.stringify(pathToFileURL(root).href)},getState:()=>K,esc,fmt:n=>Number(n).toLocaleString('de-DE'),toast:m=>notices.push(m),refresh:async()=>{},api:async(path,payload)=>{if(!payload)return clone(window.fixtureState);if(payload.action==='preview'){previewCalls.push({path,payload});const total=Object.values(payload.troops||{}).reduce((n,v)=>n+Number(v),0);if(window.previewMode==='deferred'&&total===20)await new Promise(r=>window.releasePreview=r);const members=payload.run_id?(window.fixtureState.runs.find(r=>Number(r.id)===Number(payload.run_id))?.members.length||0)+1:1;return {forecast:{status:members<2?'missing_members':total>=30?'ready':'risky',label:members<2?'Weiterer Spieler benötigt':total>=30?'Bereit '+total:'Riskant '+total,estimated:true,total_troops:total,remaining_hp_percent:Math.min(99,total),missing_roles:[],includes_side_room:payload.stance!=='cautious'},guidance:clone(window.fixtureState.rotation.find(d=>d.dungeon_code===payload.dungeon_code)?.guidance||window.fixtureState.rotation[0].guidance)};}calls.push({path,payload});if(pending)await new Promise(r=>window.release=r);return {message:'Gespeichert'};}});document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)panel.onClick(b.dataset.action,b)});document.addEventListener('submit',e=>{const f=e.target.closest('form[data-form]');if(f){e.preventDefault();panel.onSubmit(f)}});panel.render('dungeons');</script></html>`);
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'}),page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(pathToFileURL(path.join(out,'fixture.html')).href);await page.locator('.dungeon-grid').first().waitFor();assert.equal(await page.locator('.dungeon-grid').first().locator('.dungeon-card').count(),3);assert.equal(await page.locator('.dungeon-card script').count(),0,'server text is escaped');
 assert((await page.locator('.dungeon-intro').innerText()).includes('Klassen frei kombinierbar'),'Overview explains that classes are freely combinable');
 assert.equal((await page.locator('.dungeon-shell').innerText()).includes('Pflicht'),false,'Dungeon UI does not describe mandatory roles');
 assert.deepEqual(await page.locator('.dungeon-card').first().locator('.dungeon-role-icon').evaluateAll(es=>es.map(e=>e.title)),['Angreifer · Mehr Schaden','Verteidiger · Mehr Schutz','Sammler · Mehr Beute','Jäger · Kürzere Reise'],'Role icons expose each class bonus');
 assert.equal(await page.locator('.dungeon-grid').first().locator('.dungeon-guidance').count(),3,'Every weekly dungeon shows troop guidance');
 assert.equal(await page.locator('.dungeon-grid').first().locator('.dungeon-formation').first().locator('img').count(),3,'Guidance shows all three troop types');
 for(const [width,height] of [[320,700],[390,844],[667,375],[1280,800]]){
  await page.setViewportSize({width,height});
  for(const tab of ['overview','parties','reports']){
   await page.locator(`[data-action="dungeon-tab"][data-id="${tab}"]`).click();
   await page.locator('.dungeon-shell img').evaluateAll(async images=>{await Promise.all(images.map(image=>{image.loading='eager';return image.decode();}));});
   assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,`${tab} overflows ${width}x${height}`);
   assert.equal(await page.locator('.dungeon-shell').evaluate(el=>el.scrollWidth>el.clientWidth+2),false,`${tab} content overflows ${width}x${height}`);
   if(tab==='parties'){
    assert.equal(await page.locator('[data-party="41"] .dungeon-members > div').count(),4,'Party shows all four slots');
    assert.equal(await page.locator('[data-party="40"] .dungeon-member.is-empty small').first().innerText(),'Jede Klasse','Empty party slots accept every eligible class');
    assert((await page.locator('[data-party="40"] .dungeon-group-status').innerText()).includes('Weiterer Spieler benötigt'),'A solo group asks for one more player');
    assert.equal(await page.locator('[data-party="41"] [role="progressbar"]').getAttribute('aria-valuenow'),'1','Journey reflects server progress');
    await page.locator('[data-party="41"]').scrollIntoViewIfNeeded();
   }
   await page.screenshot({path:path.join(out,`${tab}-${width}x${height}.png`),fullPage:true});
  }
 }
 await page.evaluate(()=>{fixtureState.runs.find(r=>r.id===40).members.push({player_id:9,username:'Lio',role:'gather',total_troops:250,is_self:false})});await page.evaluate(()=>panel.refresh());await page.locator('[data-action="dungeon-tab"][data-id="parties"]').click();
 assert((await page.locator('[data-party="40"] .dungeon-group-status').innerText()).includes('2/4 Klassenboni'),'A two-player recruiting group reports its combined class bonuses');
 await page.evaluate(()=>resetFixture());await page.evaluate(()=>panel.refresh());
 await page.evaluate(()=>{fixtureState.runs=fixtureState.runs.filter(r=>r.status!=='decision')});await page.evaluate(()=>panel.refresh());await page.locator('[data-action="dungeon-tab"][data-id="overview"]').click();await page.locator('[data-action="dungeon-create-open"]').first().click();
 assert.equal(await page.locator('.dungeon-planner').count(),1,'Create replaces overview with one planner');assert.equal(await page.locator('.dungeon-planner form[data-form="dungeon-create"]').count(),1);
 const create=page.locator('form[data-form="dungeon-create"]');const createSubmit=create.locator('button[type="submit"]');assert(await createSubmit.isDisabled(),'Create waits for a role and ten troops');
 assert.equal(await create.locator('[data-dungeon-guidance]').count(),1,'Planner exposes live troop guidance');
 assert.equal(await create.locator('.dungeon-formation img').count(),3,'Planner guidance keeps the three-type formation');
 assert.equal((await create.innerText()).includes('Gesucht'),false,'Planner does not steer players toward mandatory classes');
 assert.deepEqual(await create.locator('.dungeon-role-option small').allInnerTexts(),['Mehr Schaden','Mehr Schutz','Mehr Beute','Kürzere Reise'],'Every role tile shows its own bonus');
 const guidanceText=async()=>create.locator('[data-dungeon-guidance]').innerText();const normalExplore=await guidanceText();assert(normalExplore.includes('180'),'Normal explore guidance uses its authoritative requirement');
 assert.deepEqual(await create.locator('input[name="role"]').evaluateAll(es=>es.map(e=>e.value)),['attack','defense','gather','hunter'],'Roles are native radios');assert.deepEqual(await create.locator('input[name="difficulty"]').evaluateAll(es=>es.map(e=>e.value)),['normal','hard'],'Difficulties are native radios');
 await create.locator('input[name="troop_50100101"]').fill('9');assert(await createSubmit.isDisabled(),'Nine troops is below minimum');await create.locator('input[name="troop_50100101"]').evaluate(e=>{e.value='10.5';e.dispatchEvent(new Event('input',{bubbles:true}));});assert(await createSubmit.isDisabled(),'Fractional troops are rejected');
 await create.locator('input[name="role"][value="attack"]').check();await create.locator('[data-action="dungeon-troops-preset"][data-value="10"]').click();assert.equal(await displayedTotal(create),10);assert.equal(await createSubmit.isEnabled(),true);
 await create.locator('input[name="difficulty"][value="hard"]').check();assert.equal(await create.locator('select[name="stance"]').count(),1,'Stance remains a select in details');const hardExplore=await guidanceText();assert(hardExplore.includes('540')&&hardExplore!==normalExplore,'Hard mode updates the guidance requirement');await create.locator('[data-detail^="tactics-"] summary').click();await create.locator('select[name="stance"]').selectOption('cautious');const hardSkip=await guidanceText();assert(hardSkip.includes('360')&&hardSkip!==hardExplore,'Cautious stance updates guidance to the skip requirement');await create.locator('select[name="stance"]').selectOption('balanced');
 await page.waitForFunction(()=>previewCalls.length>0);await create.locator('[data-dungeon-forecast]').waitFor();assert((await create.locator('[data-dungeon-forecast]').innerText()).includes('Weiterer Spieler benötigt'),'A single-member forecast reports the missing member');
 await create.locator('[data-action="dungeon-troops-preset"][data-value="clear"]').click();await page.evaluate(()=>{previewCalls.length=0;previewMode='deferred'});await create.locator('input[name="troop_50100101"]').fill('20');await create.locator('input[name="troop_50100101"]').dispatchEvent('input');await page.waitForFunction(()=>previewCalls.some(c=>Object.values(c.payload.troops).reduce((n,v)=>n+Number(v),0)===20));await create.locator('input[name="troop_50100101"]').fill('30');await create.locator('input[name="troop_50100101"]').dispatchEvent('input');await page.waitForFunction(()=>document.querySelector('[data-dungeon-forecast]')?.textContent.includes('30 Truppen'));await page.evaluate(()=>releasePreview());await page.waitForTimeout(50);assert((await create.locator('[data-dungeon-forecast]').innerText()).includes('30 Truppen'),'An older preview cannot overwrite a newer selection');await page.evaluate(()=>{previewMode='';previewCalls.length=0});await create.locator('[data-action="dungeon-troops-preset"][data-value="10"]').click();
 await page.locator('.dungeon-planner [data-action="dungeon-planning-close"]').click();assert.equal(await page.locator('.dungeon-planner').count(),0);await page.locator('[data-action="dungeon-create-open"]').first().click();assert(await create.locator('input[name="role"][value="attack"]').isChecked(),'Back keeps role draft');assert(await create.locator('input[name="difficulty"][value="hard"]').isChecked(),'Back keeps difficulty draft');assert.equal(await displayedTotal(create),10,'Back keeps troop draft');
 await create.locator('[data-action="dungeon-troops-preset"][data-value="100"]').click();assert.equal(await displayedTotal(create),100);await create.locator('[data-action="dungeon-troops-preset"][data-value="max"]').click();assert.equal(await displayedTotal(create),50000,'Max preset respects expedition cap');await create.locator('[data-action="dungeon-troops-preset"][data-value="clear"]').click();assert(await createSubmit.isDisabled());await create.locator('input[name="troop_50100101"]').fill('10');await create.locator('input[name="troop_50100101"]').dispatchEvent('input');assert.equal(await displayedTotal(create),10,'Typing updates total');
 await page.evaluate(()=>panel.refresh());await page.waitForTimeout(30);assert(await create.locator('input[name="role"][value="attack"]').isChecked(),'Polling preserves role radio');assert(await create.locator('input[name="difficulty"][value="hard"]').isChecked(),'Polling preserves difficulty radio');assert.equal(await create.locator('input[name="troop_50100101"]').inputValue(),'10','Polling preserves create draft');
 await createSubmit.click();await page.waitForFunction(()=>calls.length===1);await page.locator('.dungeon-planner').waitFor({state:'detached'});let call=await page.evaluate(()=>calls[0]);assert.equal(call.payload.dungeon_code,'roots');assert.equal(call.payload.role,'attack');assert.deepEqual(call.payload.troops,{50100101:10});
 await page.locator('[data-action="dungeon-tab"][data-id="overview"]').click();await page.locator('[data-action="dungeon-create-open"]').first().click();assert.equal(await displayedTotal(create),0,'Successful create clears troop draft');assert(await create.locator('input[name="difficulty"][value="normal"]').isChecked(),'Successful create clears difficulty draft');
 await create.locator('input[name="difficulty"][value="hard"]').check();await create.locator('[data-action="dungeon-troops-preset"][data-value="100"]').click();await page.locator('.dungeon-planner [data-action="dungeon-planning-close"]').click();
 await page.evaluate(()=>{K.city.world_id=8;fixtureState.world_id=8;panel.render('dungeons')});await page.evaluate(()=>panel.refresh());await page.locator('[data-action="dungeon-create-open"]').first().click();assert.equal(await displayedTotal(create),0,'World 8 does not receive world 7 troop draft');assert(await create.locator('input[name="difficulty"][value="normal"]').isChecked(),'World 8 does not receive world 7 settings');await page.locator('.dungeon-planner [data-action="dungeon-planning-close"]').click();
 await page.evaluate(()=>{K.city.world_id=7;fixtureState.world_id=7;panel.render('dungeons')});await page.evaluate(()=>panel.refresh());await page.locator('[data-action="dungeon-create-open"]').first().click();assert.equal(await displayedTotal(create),100,'Returning to world 7 restores its troop draft');assert(await create.locator('input[name="difficulty"][value="hard"]').isChecked(),'Returning to world 7 restores its settings');await page.locator('.dungeon-planner [data-action="dungeon-planning-close"]').click();
 await page.setViewportSize({width:390,height:844});await page.locator('[data-action="dungeon-tab"][data-id="parties"]').click();assert.equal(await page.locator('form[data-form="dungeon-join"]').count(),0,'Browse list contains no join forms');await page.locator('[data-action="dungeon-join-open"][data-id="40"]').click();assert.equal(await page.locator('.dungeon-planner').count(),1,'Join opens one planner');const join=page.locator('.dungeon-planner form[data-form="dungeon-join"]');await join.locator('input[name="role"][value="gather"]').check();await join.locator('input[name="troop_50100101"]').fill('250');await join.locator('input[name="troop_50100101"]').dispatchEvent('input');await page.evaluate(()=>panel.refresh());await page.waitForTimeout(30);assert(await join.locator('input[name="role"][value="gather"]').isChecked(),'polling preserves join role');assert.equal(await join.locator('input[name="troop_50100101"]').inputValue(),'250','polling preserves draft');
 await join.locator('button[type="submit"]').click();await page.waitForFunction(()=>calls.length===2);call=await page.evaluate(()=>calls[1]);assert.deepEqual(call.payload,{action:'join',run_id:40,role:'gather',troops:{50100101:250},expected_world_id:7,request_id:call.payload.request_id});
 await page.evaluate(()=>resetFixture());await page.evaluate(()=>panel.refresh());await page.locator('[data-action="dungeon-vote"][data-choice="explore"]').click();await page.waitForFunction(()=>calls.length===3);call=await page.evaluate(()=>calls[2]);assert.equal(call.payload.action,'vote');assert.equal(call.payload.choice,'explore');
 await page.locator('[data-action="dungeon-tab"][data-id="reports"]').click();await page.locator('[data-action="dungeon-claim"]').click();await page.waitForFunction(()=>calls.length===4);call=await page.evaluate(()=>calls[3]);assert.equal(call.payload.run_id,90);assert.equal(call.payload.expected_world_id,7);
 assert.deepEqual(errors,[]);console.log('PASS dungeon panel; screenshots: '+out);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
