'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),net=require('net'),{spawn}=require('child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts/extra-event');fs.mkdirSync(out,{recursive:true});
(async()=>{
 const socket=net.createServer();await new Promise(r=>socket.listen(0,'127.0.0.1',r));const port=socket.address().port;await new Promise(r=>socket.close(r));const base='http://127.0.0.1:'+port;
 const fixture=spawn('C:/xampp/php/php.exe',['tools/preview-feature-fixture.php','--port='+port,'--hud','--chat'],{cwd:root,stdio:['pipe','pipe','pipe'],windowsHide:true});
 let log='';fixture.stdout.on('data',d=>log+=d);fixture.stderr.on('data',d=>log+=d);
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
  for(let n=0;!log.includes('Synthetic preview ready');n++){assert(n<300&&fixture.exitCode===null,log);await new Promise(r=>setTimeout(r,100));}
  const admin=await browser.newPage({viewport:{width:390,height:844}}),page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));admin.on('pageerror',e=>errors.push(e.message));
  await admin.goto(base+'/admin/login');await admin.locator('[name=username]').fill('PreviewAdmin');await admin.locator('[name=password]').fill('PreviewFixture!2026');await Promise.all([admin.waitForURL('**/admin'),admin.locator('button[type=submit]').click()]);
  await admin.goto(base+'/admin/world?world_id=1');const form=admin.locator('#extra-event-settings');
  await form.locator('[name=enabled]').check();await form.locator('[name=name_en]').fill('Harvest Festival');await form.locator('[name=name_de]').fill('Erntefest');
  const utc=n=>new Date(Date.now()+n).toISOString().slice(0,16);await form.locator('[name=starts_at]').fill(utc(-3600000));await form.locator('[name=ends_at]').fill(utc(3600000));await form.locator('[name=reason]').fill('Event preview test');
  await Promise.all([admin.waitForNavigation(),form.locator('button[type=submit]').click()]);assert.equal(await form.locator('[name=name_en]').inputValue(),'Harvest Festival');
  await Promise.all([admin.waitForNavigation(),form.locator('[data-event-add]').click()]);await form.locator('[name=enabled]').check();await form.locator('[name=name_en]').fill('Summer Siege');await form.locator('[name=description_en]').fill('Gather your alliance for the summer siege.');await form.locator('[name=starts_at]').fill(utc(-3600000));await form.locator('[name=ends_at]').fill(utc(3600000));await form.locator('[name=target]').selectOption('market');await form.locator('[name=icon]').selectOption('alliance');await form.locator('[name=reason]').fill('Second simultaneous event');await Promise.all([admin.waitForNavigation(),form.locator('button[type=submit]').click()]);assert.equal(await form.locator('[name=event_id]').inputValue(),'2');
  await admin.screenshot({path:path.join(out,'admin-390.png'),fullPage:true});
  await page.route('**/api/rally/list',route=>route.fulfill({json:{ok:true,data:{rallies:[{id:99,world_id:1,leader_player_id:2,status:'gathering',launch_at:'2030-01-01 00:00:00',result:{alliance_id:1},participants:[],capacity:100,troop_count:1}]}}}));
  await page.goto(base+'/?zugang=login');await page.locator('[name=identifier],[name=username]').fill('PreviewPlayer');await page.locator('[name=password]').fill('PreviewFixture!2026');await Promise.all([page.waitForURL('**/city'),page.locator('form[action$="/auth/local"] button[type=submit]').click()]);
  for(const [width,height]of [[390,844],[320,568],[844,390],[568,320],[1280,800]]){
   await page.setViewportSize({width,height});await page.goto(base+'/city#world');await page.locator('#hud-extra-event').waitFor();await page.locator('#hud-alliance-rallies').waitFor();await page.waitForFunction(()=>!document.querySelector('.scene-transition.is-active'));
   const b=await page.locator('#hud-extra-event').boundingBox(),r=await page.locator('#hud-alliance-rallies').boundingBox();assert(r.y>=b.y+b.height-1&&Math.abs(b.x-r.x)<2,'Rally is directly beneath Events');
   assert(b.width>=44&&b.height>=44&&b.y+b.height<=height,'Touch size and viewport');assert(await page.locator('#hud-extra-event').evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),'Event is unobstructed');
   assert.equal(await page.locator('#hud-extra-event').getAttribute('aria-label'),'Open events · 2 active');assert.equal(await page.locator('#hud-extra-event .extra-events-count').innerText(),'2');await page.screenshot({path:path.join(out,`${width}x${height}-world.png`)});
   await page.locator('#hud-extra-event').tap();await page.locator('.extra-events').waitFor();assert.equal(await page.getByRole('tab').count(),2);await page.getByRole('tab',{name:'Summer Siege',exact:true}).tap();assert.equal(await page.getByRole('tab',{name:'Summer Siege',exact:true}).getAttribute('aria-selected'),'true');assert((await page.getByRole('tabpanel').innerText()).includes('Gather your alliance'));
   await page.getByRole('tab',{name:'Summer Siege',exact:true}).press('Home');assert.equal(await page.getByRole('tab',{name:'Harvest Festival',exact:true}).getAttribute('aria-selected'),'true');await page.getByRole('tab',{name:'Harvest Festival',exact:true}).press('End');await page.screenshot({path:path.join(out,`${width}x${height}-tabs.png`)});
   const go=page.locator('[data-action=extra-event-go]');assert(await go.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));}),'Selected event action reachable');await go.tap();await page.locator('#panel-dialog[data-panel=market]').waitFor();await page.waitForTimeout(500);assert(await page.locator('#panel-dialog[data-panel=market]').isVisible(),'Destination persists after dialog history settles');console.log('PASS event tabs '+width+'x'+height);
  }
  for(const eventId of [1,2]){await admin.goto(base+'/admin/world?world_id=1&event_id='+eventId);await form.locator('[name=enabled]').uncheck();await form.locator('[name=reason]').fill('Disable preview event');await Promise.all([admin.waitForNavigation(),form.locator('button[type=submit]').click()]);if(eventId===1){await page.goto(base+'/city#world');await page.reload();await page.locator('#hud-extra-event').waitFor();assert.equal(await page.locator('#hud-extra-event').getAttribute('aria-label'),'Open events · 1 active');}}
  await page.goto(base+'/city#world');await page.reload();await page.locator('.atlas-viewport').waitFor();await page.locator('#hud-extra-event').waitFor({state:'hidden'});assert(await page.locator('#hud-extra-event').isHidden(),'Admin disable hides event');assert.deepEqual(errors,[]);console.log('PASS admin multi-event save, independent disable and browser errors');
 }finally{await browser.close();if(fixture.exitCode===null){fixture.stdin.write('\n');await new Promise(r=>fixture.once('exit',r));}}
})().catch(e=>{console.error(e);process.exitCode=1;});
