'use strict';
// Actual main app on a disposable local database; never uses real player accounts.
const assert=require('assert'),fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TERRITORY_FIXTURE_URL||'http://127.0.0.1:18946';assert(/^http:\/\/127\.0\.0\.1:\d+$/.test(base));
const out=path.resolve(__dirname,'../output/playwright/landmark-actions');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);
 await page.goto(base+'/?zugang=login');await page.locator('[name="identifier"],[name="username"]').fill('PreviewPlayer');await page.locator('[name="password"]').fill('PreviewFixture!2026');await Promise.all([page.waitForURL('**/city'),page.locator('form[action$="/auth/local"] button[type="submit"]').click()]);await page.waitForFunction(()=>document.querySelector('#player-hud-name')?.textContent.includes('PreviewPlayer'));
 const payload=await (await page.request.get(base+'/api/territory/state?world_id=1')).json();assert(payload.ok);const state=payload.data;
 const available=state.targets.find(t=>t.can_attack&&t.kind==='commune'),locked=state.targets.find(t=>!t.can_attack&&t.kind==='commune'),shrine=state.targets.find(t=>t.kind==='canton'),crown=state.targets.find(t=>t.kind==='crown');assert(available&&locked&&shrine&&crown);
 async function select(target){await page.evaluate(t=>ConquerWorld.focus(t.x,t.y),target);const marker=page.locator(`[data-atlas-target="territory:${target.id}"]`);await marker.waitFor();await marker.click();await page.waitForSelector('.atlas-target-actions:not([hidden])');}
 async function close(){await page.locator('.landmark-info [data-action="close-dialog"],.territory-heading [data-action="territory-close"]').click();await page.waitForFunction(()=>!document.querySelector('#game-dialog').open);await page.waitForTimeout(160);}
 for(const size of [{width:1280,height:800},{width:390,height:844},{width:320,height:568},{width:844,height:390},{width:568,height:320}]){
  await page.setViewportSize(size);await page.locator('#navigation [data-id="world"]').click();await page.waitForSelector('.atlas-shell.is-luxembourg');
  for(const target of [available,shrine,crown]){
   await select(target);assert.equal(await page.locator('.atlas-target-actions [data-action="landmark-rally"]').count(),1);assert.equal(await page.locator('.atlas-target-actions [data-action="landmark-scout"]').count(),1);assert.equal(await page.locator('.atlas-target-actions [data-action="territory-target"]').count(),1);assert(!await page.locator('#game-dialog').evaluate(d=>d.open),'selecting landmark opens compact menu');
   const controls=await page.locator('.atlas-target-actions button').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,hit:e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))};}));assert(controls.every(r=>r.x>=0&&r.y>=0&&r.x+r.w<=size.width+1&&r.y+r.h<=size.height+1&&r.h>=44&&r.hit),JSON.stringify({size,controls}));
   await page.screenshot({path:path.join(out,`${target.kind}-menu-${size.width}x${size.height}.png`)});await page.locator('.atlas-target-actions [data-atlas="clear"]').click();await page.waitForTimeout(160);
  }
  await select(locked);await page.locator('.atlas-target-actions [data-action="landmark-rally"]').click();await page.waitForSelector('.landmark-info dl');const rect=await page.locator('#game-dialog').boundingBox();assert(rect.x>=0&&rect.y>=0&&rect.x+rect.width<=size.width+1&&rect.y+rect.height<=size.height+1);await page.screenshot({path:path.join(out,`closed-${size.width}x${size.height}.png`)});assert(Math.abs(rect.x+rect.width/2-size.width/2)<2&&Math.abs(rect.y+rect.height/2-size.height/2)<2,'attack info is centered '+JSON.stringify({size,rect}));assert((await page.locator('.landmark-info [role="status"]').innerText()).length>5);await page.screenshot({path:path.join(out,`closed-${size.width}x${size.height}.png`)});await close();
  await select(available);await page.goBack();await page.waitForFunction(()=>document.querySelector('.atlas-target-actions').hidden);await select(available);await page.locator('.atlas-target-actions [data-action="landmark-rally"]').click();await page.waitForSelector('[data-form="territory-army"]');await page.locator('[data-territory-troop]').first().fill('1');await page.locator('[data-form="territory-army"] [type="submit"]').scrollIntoViewIfNeeded();assert(await page.locator('[data-form="territory-army"] [type="submit"]').isVisible());await close();
  await select(available);await page.locator('.atlas-target-actions [data-action="territory-target"]').click();await page.waitForSelector('.territory-target-summary');await close();
  await page.locator('#navigation [data-id="city"]').click();await page.waitForSelector('.painted-village-building');await page.screenshot({path:path.join(out,`city-${size.width}x${size.height}.png`)});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);console.log(`PASS landmark menus, centered lock info, rally form, details and Back ${size.width}x${size.height}`);
 }
 await page.setViewportSize({width:1280,height:800});await page.locator('#navigation [data-id="world"]').click();await select(available);const pending=page.waitForResponse(r=>r.url().endsWith('/api/march/scout-landmark')&&r.request().method()==='POST');await page.locator('.atlas-target-actions [data-action="landmark-scout"]').click();const response=await pending,first=await response.json();assert(first.ok,JSON.stringify(first));const request=response.request();const replay=await page.request.post(request.url(),{headers:request.headers(),data:request.postData()});const second=await replay.json();assert(second.ok&&second.data.march_id===first.data.march_id,'repeated scout request returns the same order');assert.equal(replay.headers()['x-operation-replayed'],'1');
 assert.deepEqual(errors,[]);console.log('PASS real scout dispatch and replay, no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
