'use strict';
require('./fixtures/browser_locale.cjs')('de');
// Run against tools/preview-feature-fixture.php --teleport --landmark-actions --port=18947.
const assert=require('assert'),fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.LANDMARK_FIXTURE_URL||'http://127.0.0.1:18947';assert(/^http:\/\/127\.0\.0\.1:\d+$/.test(base));
const out=path.resolve(__dirname,'../output/playwright/landmark-actions');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);
 await page.goto(base+'/?zugang=login');await page.locator('[name="identifier"],[name="username"]').fill('PreviewPlayer');await page.locator('[name="password"]').fill('PreviewFixture!2026');await Promise.all([page.waitForURL('**/city'),page.locator('form[action$="/auth/local"] button[type="submit"]').click()]);await page.waitForFunction(()=>document.querySelector('#player-hud-name')?.textContent.includes('PreviewPlayer'));
 const payload=await (await page.request.get(base+'/api/game/state')).json();assert(payload.ok);const state=payload.data;
 assert(state.congress&&state.shrines.length===4,'Congress and four-shrine fixture available');
 async function select(kind,target){await page.evaluate(t=>ConquerWorld.focus(t.coord_x,t.coord_y),target);await page.locator(`[data-atlas-target="${kind==='congress'?'congress':'shrine:'+target.id}"]`).click();await page.waitForSelector('.atlas-target-actions:not([hidden])');}
 async function close(){await page.keyboard.press('Escape');await page.waitForFunction(()=>!document.querySelector('#game-dialog').open);await page.waitForTimeout(180);}
 await page.locator('#navigation [data-id="world"]').click();await page.waitForSelector('.atlas-shell');await page.waitForFunction(()=>document.body.classList.contains('world-mode'));await select('shrine',state.shrines[0]);
 const scouting=page.waitForResponse(r=>r.url().endsWith('/api/march/scout-landmark')&&r.request().method()==='POST');await page.locator('.atlas-target-actions [data-action="landmark-scout"]').click();const scout=await (await scouting).json();assert(scout.ok,JSON.stringify(scout));
 for(const size of [{width:1280,height:800},{width:390,height:844},{width:568,height:320}]){
  await page.setViewportSize(size);
  for(const target of [state.congress,...state.shrines]){
   await select(target.kind,target);const menu=page.locator('.atlas-target-actions');assert.equal(await menu.locator('[data-action="landmark-rally"],[data-action="landmark-scout"]').count(),2);assert(!await page.locator('#game-dialog').evaluate(d=>d.open));
   const controls=await menu.locator('button').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,hit:e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))};}));assert(controls.every(r=>r.x>=0&&r.y>=0&&r.x+r.w<=size.width+1&&r.y+r.h<=size.height+1&&r.h>=44&&r.hit));
   await menu.locator('[data-action="congress-open"],[data-action="shrine-open"]').click();await page.locator('.congress-panel').waitFor();await close();
  }
  const locked=state.shrines.find(t=>!t.can_attack);
  if(locked){await select('shrine',locked);await page.locator('.atlas-target-actions [data-action="landmark-rally"]').click();await page.locator('.landmark-info dl').waitFor();assert.match(await page.locator('.landmark-info dd').innerText(),/2026|Oct|10/);const rect=await page.locator('#game-dialog').boundingBox();assert(Math.abs(rect.x+rect.width/2-size.width/2)<2&&Math.abs(rect.y+rect.height/2-size.height/2)<2);await page.screenshot({path:path.join(out,`shrine-closed-${size.width}x${size.height}.png`)});await close();}
  await select('congress',state.congress);await page.locator('.atlas-target-actions [data-action="landmark-rally"]').click();await page.locator('.march-command').waitFor();assert.equal(await page.locator('.march-command-heading h2').innerText(),'Rally');await page.locator('[data-action="march-clear"]').click();await page.locator('.march-unit-amount input').first().fill('3');assert(!await page.locator('#march-confirm').isDisabled());await page.locator('[data-action="march-time-open"]').click();await page.locator('.march-time-dialog [data-id="1"]').click();await page.locator('[data-action="march-time-confirm"]').click();assert.match(await page.locator('#march-time-label').innerText(),/^1 /);await page.screenshot({path:path.join(out,`congress-rally-${size.width}x${size.height}.png`)});await close();console.log(`PASS real Shrine/Congress menus, details, closed event and rally selection ${size.width}x${size.height}`);
 }
 await select('congress',state.congress);await page.locator('.atlas-target-actions [data-action="landmark-rally"]').click();await page.locator('.march-command').waitFor();await page.locator('[data-action="march-clear"]').click();await page.locator('.march-unit-amount input').first().fill('3');const starting=page.waitForResponse(r=>r.url().endsWith('/api/rally/start-shrine')&&r.request().method()==='POST');await page.locator('#march-confirm').click();const response=await starting,rally=await response.json();assert(rally.ok,JSON.stringify(rally));assert.equal(JSON.parse(response.request().postData()).target_id,state.congress.id);console.log('PASS real Congress rally dispatched through troop selector');
 await close();await page.setViewportSize({width:1280,height:800});
 const deadline=Date.now()+90000;let report;
 while(Date.now()<deadline){const snapshot=await (await page.request.get(base+'/api/game/state')).json();report=snapshot.data?.reports.find(r=>r.details?.type==='landmark_scout');if(report)break;await page.waitForTimeout(2000);}
 assert(report,'scout report arrives through the real march tick');await page.locator('#navigation [data-id="reports"]').click();await page.locator('.mail-open').filter({hasText:state.shrines[0].name}).first().click();await page.locator('.scout-report').waitFor();assert.equal(await page.locator('.sr-troop').count(),2);assert.equal(await page.locator('.sr-resource,.sr-wall,.sr-mastery-card').count(),0);assert.match(await page.locator('.sr-target').innerText(),new RegExp(state.shrines[0].name));await page.waitForFunction(()=>[...document.querySelectorAll('.scout-report img')].every(i=>i.complete&&i.naturalWidth));await page.screenshot({path:path.join(out,'shrine-scout-report.png')});assert.deepEqual(errors,[]);console.log('PASS arrival intelligence in the real mailbox with correct Shrine portrait and defenders, no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
