'use strict';
// Actual main app on a disposable local database; never uses real player accounts.
const assert=require('assert'),fs=require('fs'),path=require('path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TERRITORY_FIXTURE_URL||'http://127.0.0.1:18946';assert(/^http:\/\/127\.0\.0\.1:\d+$/.test(base));
const out=path.resolve(__dirname,'../output/playwright/landmark-actions');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome'});try{
 const page=await browser.newPage({hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(20000);
 if(process.env.LANDMARK_THEME_PATH)await page.route('**/assets/css/village-theme.css?*',route=>route.fulfill({status:200,contentType:'text/css',body:fs.readFileSync(process.env.LANDMARK_THEME_PATH,'utf8')}));
 await page.goto(base+'/?zugang=login');await page.locator('[name="identifier"],[name="username"]').fill('PreviewPlayer');await page.locator('[name="password"]').fill('PreviewFixture!2026');await Promise.all([page.waitForURL('**/city'),page.locator('form[action$="/auth/local"] button[type="submit"]').click()]);await page.waitForFunction(()=>document.querySelector('#player-hud-name')?.textContent.includes('PreviewPlayer'));
 const payload=await (await page.request.get(base+'/api/territory/state?world_id=1')).json();assert(payload.ok);const state=payload.data;
 const available=state.targets.find(t=>t.can_attack&&t.kind==='commune'&&t.name.includes('Haute Sûre')),locked=state.targets.find(t=>!t.can_attack&&t.kind==='commune'),shrine=state.targets.find(t=>t.kind==='canton'),crown=state.targets.find(t=>t.kind==='crown');assert(available&&locked&&shrine&&crown);
 async function select(target){await page.evaluate(t=>ConquerWorld.focus(t.x,t.y),target);const marker=page.locator(`[data-atlas-target="territory:${target.id}"]`);await marker.waitFor();await marker.click();await page.waitForSelector('.atlas-target-actions:not([hidden])');await page.waitForFunction(()=>getComputedStyle(document.querySelector('.atlas-marker.is-selected>.atlas-marker-name')).opacity==='0');}
 async function close(){await page.locator('.landmark-info [data-action="close-dialog"],.territory-heading [data-action="territory-close"]').click();await page.waitForFunction(()=>!document.querySelector('#game-dialog').open);await page.waitForTimeout(160);}
 for(const size of [{width:1280,height:800},{width:390,height:844},{width:320,height:568},{width:844,height:390},{width:568,height:320}]){
  await page.setViewportSize(size);await page.locator('#navigation [data-id="world"]').click();await page.waitForSelector('.atlas-shell.is-luxembourg');
  for(const target of [available,shrine,crown]){
   await select(target);assert.equal(await page.locator('.atlas-target-actions [data-action="landmark-rally"]').count(),1);assert.equal(await page.locator('.atlas-target-actions [data-action="landmark-scout"]').count(),1);assert.equal(await page.locator('.atlas-target-actions [data-action="territory-target"]').count(),1);assert(!await page.locator('#game-dialog').evaluate(d=>d.open),'selecting landmark opens compact menu');
   const controls=await page.locator('.atlas-target-actions button').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,hit:e.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))};}));assert(controls.every(r=>r.x>=0&&r.y>=0&&r.x+r.w<=size.width+1&&r.y+r.h<=size.height+1&&r.h>=44&&r.hit),JSON.stringify({size,controls}));
   const layout=await page.locator('.atlas-target-actions').evaluate(menu=>{const r=menu.getBoundingClientRect(),name=menu.querySelector('.atlas-village-banner strong'),n=name.getBoundingClientRect(),close=menu.querySelector('[data-atlas="clear"]').getBoundingClientRect();return {contained:[...menu.querySelectorAll('button')].every(b=>{const x=b.getBoundingClientRect();return x.left>=r.left&&x.right<=r.right+1&&x.top>=r.top&&x.bottom<=r.bottom+1;}),fullName:name.scrollWidth<=name.clientWidth+1,noOverlap:n.right<=close.left+1,hiddenDuplicate:getComputedStyle(document.querySelector('.atlas-marker.is-selected>.atlas-marker-name')).opacity==='0'};});assert(Object.values(layout).every(Boolean),JSON.stringify({size,layout}));
   const artLayout=await page.locator('.atlas-target-actions').evaluate(menu=>{const m=menu.getBoundingClientRect(),a=document.querySelector('.atlas-marker.is-selected img').getBoundingClientRect();return {visible:a.left>=-1&&a.top>=-1&&a.right<=innerWidth+1&&a.bottom<=innerHeight+1,clear:Math.min(m.right,a.right)<=Math.max(m.left,a.left)+1||Math.min(m.bottom,a.bottom)<=Math.max(m.top,a.top)+1,font:getComputedStyle(menu.querySelector('.atlas-village-banner strong')).fontFamily};});assert(artLayout.visible&&artLayout.clear&&artLayout.font.includes('Bree Serif'),JSON.stringify({size,artLayout}));
   await page.screenshot({path:path.join(out,`${target.kind}-menu-${size.width}x${size.height}.png`)});await page.locator('.atlas-target-actions [data-atlas="clear"]').click();await page.waitForTimeout(160);
  }
  await select(locked);await page.locator('.atlas-target-actions [data-action="landmark-rally"]').click();await page.waitForSelector('.landmark-info dl');const rect=await page.locator('#game-dialog').boundingBox();assert(rect.x>=0&&rect.y>=0&&rect.x+rect.width<=size.width+1&&rect.y+rect.height<=size.height+1);await page.screenshot({path:path.join(out,`closed-${size.width}x${size.height}.png`)});assert(Math.abs(rect.x+rect.width/2-size.width/2)<2&&Math.abs(rect.y+rect.height/2-size.height/2)<2,'attack info is centered '+JSON.stringify({size,rect}));assert((await page.locator('.landmark-info [role="status"]').innerText()).length>5);await page.screenshot({path:path.join(out,`closed-${size.width}x${size.height}.png`)});await close();
  await select(available);await page.goBack();await page.waitForFunction(()=>document.querySelector('.atlas-target-actions').hidden);await select(available);
  const rally=page.locator('.atlas-target-actions [data-action="landmark-rally"]'),before=await rally.boundingBox();await page.mouse.move(before.x+before.width/2,before.y+before.height-2);await page.waitForTimeout(200);const after=await rally.boundingBox();assert(Math.abs(before.x-after.x)<1&&Math.abs(before.y-after.y)<1,'rally hit area must not move on hover');
  if(size.width<=390)await page.touchscreen.tap(after.x+after.width/2,after.y+after.height-2);else await page.mouse.click(after.x+after.width/2,after.y+after.height-2);
  await page.waitForSelector('[data-form="territory-army"]');await page.locator('[data-territory-troop]').first().fill('1');await page.locator('[data-form="territory-army"] [type="submit"]').scrollIntoViewIfNeeded();assert(await page.locator('[data-form="territory-army"] [type="submit"]').isVisible());await close();
  await select(available);await page.locator('.atlas-target-actions [data-action="territory-target"]').click();await page.waitForSelector('.territory-target-summary');await close();
  await page.locator('#navigation [data-id="city"]').click();await page.waitForSelector('.painted-village-building');await page.screenshot({path:path.join(out,`city-${size.width}x${size.height}.png`)});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);console.log(`PASS landmark menus, centered lock info, rally form, details and Back ${size.width}x${size.height}`);
 }
 await page.setViewportSize({width:390,height:844});await page.locator('#navigation [data-id="world"]').click();await page.waitForSelector('.atlas-shell.is-luxembourg');await select(available);await page.locator('.atlas-target-actions [data-action="landmark-rally"]').tap();await page.waitForSelector('[data-form="territory-army"]');await page.locator('[data-territory-troop]').first().fill('1');
 const started=page.waitForResponse(r=>r.url().endsWith('/api/territory/action')&&r.request().method()==='POST');await page.locator('[data-form="territory-army"] [type="submit"]').tap();const startResponse=await started,startResult=await startResponse.json();assert(startResult.ok&&startResult.data.rally_id,JSON.stringify(startResult));
 const startRequest=startResponse.request(),startReplay=await page.request.post(startRequest.url(),{headers:startRequest.headers(),data:startRequest.postData()}),repeatedStart=await startReplay.json();assert(repeatedStart.ok&&repeatedStart.data.rally_id===startResult.data.rally_id,'rally retry returns the same order');
 await page.waitForFunction(()=>!document.querySelector('[data-form="territory-army"]'));const updated=(await (await page.request.get(base+'/api/territory/state?world_id=1')).json()).data;assert.equal(updated.rallies.filter(r=>Number(r.id)===Number(startResult.data.rally_id)).length,1);await page.screenshot({path:path.join(out,'commune-rally-created-390x844.png')});await close();console.log('PASS real Commune rally from touch menu through troop confirmation and retry');
 await page.setViewportSize({width:1280,height:800});await select(available);const pending=page.waitForResponse(r=>r.url().endsWith('/api/march/scout-landmark')&&r.request().method()==='POST');await page.locator('.atlas-target-actions [data-action="landmark-scout"]').click();const response=await pending,first=await response.json();assert(first.ok,JSON.stringify(first));const request=response.request();const replay=await page.request.post(request.url(),{headers:request.headers(),data:request.postData()});const second=await replay.json();assert(second.ok&&second.data.march_id===first.data.march_id,'repeated scout request returns the same order');assert.equal(replay.headers()['x-operation-replayed'],'1');
 assert.deepEqual(errors,[]);console.log('PASS real scout dispatch and replay, no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
