'use strict';
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.argv[2];
assert(/^http:\/\/127\.0\.0\.1:\d+\/conquer$/.test(base), 'Disposable fixture required');
const out = path.resolve(__dirname, '../output/playwright/link-tracker');
fs.mkdirSync(out, { recursive: true });
const ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131.0.0.0 Safari/537.36';
(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const context = await browser.newContext({ userAgent:ua, permissions:['clipboard-read','clipboard-write'], reducedMotion:'reduce' });
  const page = await context.newPage(), errors = [], screenshots = [];
  page.on('pageerror', error => errors.push(error.message));
  const login = async name => {
    await page.goto(base+'/admin/login');
    await page.locator('[name=username]').fill(name);
    await page.locator('[name=password]').fill('Link-Fixture-2026!');
    await Promise.all([page.waitForURL(base+'/admin'),page.locator('button[type=submit]').click()]);
  };
  try {
    await page.goto(base+'/admin/links');
    assert.equal(new URL(page.url()).pathname, '/conquer/admin/login');
    await login('LinkAdmin');
    await page.goto(base+'/admin/links');
    await page.getByRole('heading',{name:'Link tracker',exact:true}).waitFor();
    const form = page.locator('.link-editor').first();
    await form.locator('..').locator('summary').click();
    const values = await form.evaluate(el=>Object.fromEntries(new FormData(el)));
    assert.equal((await context.request.post(base+'/admin/action/link-save',{form:{...values,csrf_token:'bad'},maxRedirects:0})).status(),403);
    assert.equal((await context.request.get(base+'/admin/action/link-save',{maxRedirects:0})).status(),405);
    // Invalid server input retains a bounded draft without creating a campaign.
    await context.request.post(base+'/admin/action/link-save',{form:{...values,label:'Retained campaign',slug:'browser-fixture',destination:'//evil.invalid',reason:'Fixture invalid target'},maxRedirects:0});
    await page.reload();
    assert.equal(await form.locator('[name=label]').inputValue(),'Retained campaign');
    await form.locator('[name=label]').fill('Browser campaign');
    await form.locator('[name=slug]').fill('browser-fixture');
    await form.locator('[name=destination]').fill('https://play.unionofkingdoms.com/?mode=register');
    await form.locator('[name=reason]').fill('Browser fixture campaign');
    const createValues = await form.evaluate(el=>Object.fromEntries(new FormData(el)));
    await Promise.all([page.waitForURL(base+'/admin/links'),form.getByRole('button',{name:'Create link',exact:true}).click()]);
    const row = page.locator('.link-row').filter({has:page.getByRole('heading',{name:'Browser campaign',exact:true})});
    await row.waitFor();
    const share = row.locator('.link-copy input');
    assert.equal(await share.inputValue(),base+'/go/browser-fixture');
    assert.equal((await context.request.post(base+'/admin/action/link-save',{form:createValues,maxRedirects:0})).status(),303);
    await page.reload();
    assert.equal(await page.getByRole('heading',{name:'Browser campaign',exact:true}).count(),1);
    await row.locator('[data-link-copy]').click();
    assert.match(await row.locator('.link-copy-feedback').innerText(),/Link copied/);
    assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),base+'/go/browser-fixture');
    await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(new Error('Unavailable'))}}));
    await row.locator('[data-link-copy]').click();
    assert.match(await row.locator('.link-copy-feedback').innerText(),/Select and copy/);
    assert.equal(await share.evaluate(el=>el.selectionEnd-el.selectionStart), (await share.inputValue()).length);
    assert.equal((await context.request.get(base+'/admin/links?export=csv')).status(),200);
    assert.match((await context.request.get(base+'/admin/links?export=csv')).headers()['content-disposition'],/union-of-kingdoms-links.csv/);
    // The public document uses the actual shipped view and JavaScript.
    const site = await context.newPage(), clicks = [];
    site.on('pageerror',error=>errors.push(error.message));
    site.on('request',req=>{if(req.url()===base+'/api/links/click')clicks.push(req.postDataJSON());});
    await context.route('https://play.unionofkingdoms.com/**',route=>route.fulfill({contentType:'text/html',body:'<title>Fixture destination</title><p>Fixture destination</p>'}));
    await site.goto(base+'/website?utm_source=instagram&private=not-transmitted');
    assert.equal(await site.locator('.link-tracker-notice summary').innerText(),'Link statistics and privacy');
    const [galleryResponse]=await Promise.all([site.waitForResponse(r=>r.url()===base+'/api/links/click'),site.locator('[data-track-link=site-gallery-city]').first().click()]);
    assert.equal(galleryResponse.status(),204,'website event response; headers '+JSON.stringify(await galleryResponse.request().allHeaders()));
    assert.deepEqual(clicks,[{link:'site-gallery-city',source:'instagram'}]);
    await site.evaluate(()=>document.querySelector('[data-track-link=site-gallery-city]').click());
    await site.waitForTimeout(100);
    assert.equal(clicks.length,1,'synthetic events never count');
    await site.locator('[data-track-link=site-register-hero]').click();
    await site.waitForURL('https://play.unionofkingdoms.com/?mode=register');
    assert.equal(clicks.length,2,'normal navigation counts once without blocking departure');
    await page.goto(base+'/admin/links?kind=website');
    const hero=page.locator('.link-row').filter({has:page.getByRole('heading',{name:'Website · register in hero',exact:true})});
    await page.waitForFunction(()=>[...document.querySelectorAll('.link-row')].some(el=>el.querySelector('h3')?.textContent==='Website · register in hero'&&el.querySelector('dd')?.textContent==='1'));
    assert.equal(await hero.locator('dd').first().innerText(),'1');
    await site.close();
    // Opt-out prevents the frontend request itself, including anchor navigation.
    const privacyPage=await context.newPage(),privacyRequests=[];
    await privacyPage.addInitScript(()=>Object.defineProperty(navigator,'globalPrivacyControl',{value:true}));
    privacyPage.on('request',req=>{if(req.url().includes('/api/links/click'))privacyRequests.push(req.url());});
    await privacyPage.goto(base+'/website');await privacyPage.locator('[data-track-link=site-gallery-city]').first().click();
    await privacyPage.waitForTimeout(100);assert.deepEqual(privacyRequests,[]);await privacyPage.close();
    for(const [lang,width,height] of [['en',1280,800],['en',390,844],['en',320,568],['en',844,390],['de',390,844],['fr',390,844],['fr',844,390]]) {
      await context.addCookies([{name:'conquer_locale',value:lang,url:base}]);
      await page.setViewportSize({width,height});
      await page.goto(base+'/admin/links');
      const title={en:'Link tracker',de:'Linktracker',fr:'Suivi des liens'}[lang];
      await page.getByRole('heading',{name:title,exact:true}).waitFor();
      await page.waitForFunction(()=>window.ConquerLocale?.ready===true || document.documentElement.lang===window.ConquerLocale?.locale);
      assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2),true,`${lang} ${width} no overflow`);
      assert.equal(await page.evaluate(()=>getComputedStyle(document.body).scrollbarWidth),'none','scrollbars hidden while scrolling remains available');
      assert.equal(await page.evaluate(()=>getComputedStyle(document.body).fontFamily.includes('system-ui')),true,'approved admin typography');
      const shot=`admin-${lang}-${width}x${height}.png`;
      await page.screenshot({path:path.join(out,shot)});screenshots.push(shot);
      await page.locator('.link-row').first().scrollIntoViewIfNeeded();
      const rowShot=`links-${lang}-${width}x${height}.png`;
      await page.screenshot({path:path.join(out,rowShot)});screenshots.push(rowShot);
    }
    await context.addCookies([{name:'conquer_locale',value:'en',url:base}]);
    await page.goto(base+'/admin/links');
    const statsRow=page.locator('.link-row').filter({has:page.getByRole('heading',{name:'Instagram Alpha updated',exact:true})});
    await statsRow.getByRole('link',{name:'Statistics',exact:true}).click();
    assert.match(await page.locator('.link-insights').innerText(),/Instagram/);
    await page.setViewportSize({width:1280,height:800});
    await page.locator('form[action$="/admin/logout"] button').click();await page.waitForURL(base+'/admin/login');
    await login('LinkModerator');await page.goto(base+'/admin/links');
    assert.equal(await page.locator('.link-editor').count(),0,'moderator sees statistics without campaign editors');
    assert.equal((await context.request.post(base+'/admin/action/link-save',{form:createValues,maxRedirects:0})).status(),403);
    assert.deepEqual(errors,[]);
    fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({passed:true,screenshots,errors,clicks},null,2));
    console.log('PASS real browser: campaign forms, CSRF, replay, retained draft, clipboard and fallback, public clicks, opt-out, CSV, localization, moderator and seven responsive views');
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
