'use strict';
// Pure client tests: real localization/renderers, no browser, HTTP server or database.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'..'),catalogs=Object.fromEntries(['en','de','fr'].map(lang=>[lang,JSON.parse(fs.readFileSync(path.join(root,'data/i18n',lang+'.json'),'utf8'))]));
const source=file=>fs.readFileSync(path.join(root,'assets/js',file),'utf8');
const decode=value=>String(value).replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
// A small DOM for text boundaries only; layout/history are exercised by app suites.
class Element{
 constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.children=[];this.nodeType=1;this.dataset={};for(const[k,v]of Object.entries(attrs))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=v;this.listeners={};this.classList={add(){},remove(){},toggle(){}};this.scrollTop=0;}
 append(...children){for(const node of children){node.parentElement=this;this.children.push(node);}}
 matches(selectors){return selectors.split(',').some(selector=>{selector=selector.trim();if(selector.includes('>')){const parts=selector.split('>'),last=parts.pop();return this.matches(last)&&this.parentElement?.matches(parts.join('>'));}const not=selector.match(/:not\(([^)]+)\)/);if(not){if(this.matches(not[1]))return false;selector=selector.replace(not[0],'');}for(const match of selector.matchAll(/\[([^\]=^]+)(\^?=)?(?:"([^"]*)"|'([^']*)')?\]/g)){const value=this.attrs[match[1]],expected=match[3]??match[4];if(value===undefined||match[2]==='='&&value!==expected||match[2]==='^='&&!value.startsWith(expected))return false;}selector=selector.replace(/\[[^\]]*\]/g,'');const tag=selector.match(/^[a-z][a-z0-9-]*/i)?.[0];if(tag&&this.tagName!==tag.toUpperCase())return false;for(const id of selector.matchAll(/#([\w-]+)/g))if(this.attrs.id!==id[1])return false;for(const cls of selector.matchAll(/\.([\w-]+)/g))if(!(this.attrs.class||'').split(' ').includes(cls[1]))return false;return true;});}
 closest(selector){return this.matches(selector)?this:this.parentElement?.closest(selector)||null;}
 querySelectorAll(selector){return this.children.filter(x=>x.nodeType===1).flatMap(x=>[...(x.matches(selector)?[x]:[]),...x.querySelectorAll(selector)]);}
 querySelector(selector){return this.querySelectorAll(selector)[0]||null;}
 get textContent(){return this.children.map(x=>x.nodeType===3?x.nodeValue:x.textContent).join('');}
 set textContent(value){this.children=[];this.append({nodeType:3,nodeValue:String(value)});}
 set innerHTML(html){this.children=[];const stack=[this];for(const token of String(html).match(/<[^>]+>|[^<]+/g)||[]){if(token.startsWith('</')){if(stack.length>1)stack.pop();continue;}if(token.startsWith('<')){const tag=token.match(/^<([\w-]+)/)?.[1];if(!tag)continue;const attrs={};for(const a of token.slice(tag.length+1).matchAll(/([\w-]+)(?:="([^"]*)"|='([^']*)')?/g))attrs[a[1]]=decode(a[2]??a[3]??'');const el=new Element(tag,attrs);stack.at(-1).append(el);if(!/^(img|input|br|hr|meta|link)$/.test(tag)&&!token.endsWith('/>'))stack.push(el);}else stack.at(-1).append({nodeType:3,nodeValue:decode(token)});}}
 getAttribute(name){return this.attrs[name]??null;}
 setAttribute(name,value){this.attrs[name]=String(value);}
 hasAttribute(name){return Object.hasOwn(this.attrs,name);}
 addEventListener(name,callback){this.listeners[name]=callback;}
 dispatchEvent(event){this.listeners[event.type]?.(event);}
 contains(node){return node===this||this.children.some(x=>x.nodeType===1&&x.contains(node));}
 focus(){}
}
function runtime({locale='en',stored='',provided=catalogs,sourceCatalogs={},urls={},fetch=async()=>{throw Error('Unexpected network');}}={}){
 const document=new Element('html');document.documentElement=document;document.body=new Element('body');document.append(document.body);document.readyState='loading';document.createElement=tag=>new Element(tag);document.getElementById=id=>document.querySelector('#'+id);document.createTreeWalker=el=>{const list=[],walk=e=>e.children.forEach(x=>x.nodeType===3?list.push(x):walk(x));walk(el);let index=0;return{nextNode:()=>list[index++]||null};};
 const storage=new Map(stored?[['conquer.locale',stored]]:[]),window={CONQUER_BASE:'',CONQUER_I18N:{locale,catalogs:structuredClone(provided),sourceCatalogs,catalogUrls:urls},addEventListener(){},innerHeight:800,innerWidth:1280};
 const sandbox={window,document,localStorage:{getItem:key=>storage.get(key),setItem:(k,v)=>storage.set(k,v)},location:{protocol:'http:',href:'http://test.invalid/city'},navigator:{language:'de-DE'},NodeFilter:{SHOW_TEXT:4},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options?.detail;}},Intl,Date,URL,AbortController,fetch,setTimeout,clearTimeout,queueMicrotask,console,structuredClone};
 vm.createContext(sandbox);vm.runInContext(source('localization.js'),sandbox);return{sandbox,window,document,locale:window.ConquerLocale,load:file=>vm.runInContext(source(file),sandbox)};
}
async function main(){
 const app=runtime();await app.locale.ready;const{document,locale,window}=app;
 assert.equal(locale.locale,'en','A German browser does not change the English default');
 assert.equal(locale.t('battle.preview.fallen'),'Fallen');assert.equal(locale.text('Gefallen'),'Fallen');assert.equal(locale.text('Tue'),'Tue','English Tuesday is never translated into kills');
 document.body.innerHTML='<main id="content"><section class="community-message"><header><strong data-user-content>Forschung</strong></header><p data-user-content>Helfen</p><button data-action="community-shared-report"><span data-i18n="community.view_report">Bericht ansehen</span></button></section><h3 data-i18n-ignore>Tue<small>09/29</small></h3><span data-user-content data-i18n="common.save">Forschung</span></main>';
 locale.apply();assert.equal(document.querySelector('strong').textContent,'Forschung');assert.equal(document.querySelector('p').textContent,'Helfen');assert.equal(document.querySelector('button').textContent,'View report');assert.equal(document.querySelector('h3').textContent,'Tue09/29');
 for(const lang of ['fr','de','en']){locale.setLocale(lang);assert.equal(document.querySelector('strong').textContent,'Forschung');assert.equal(document.querySelector('p').textContent,'Helfen');assert.equal(document.querySelector('button').textContent,catalogs[lang]['community.view_report']);}
 app.load('alliance-ranks.js');app.load('mvp-panels.js');const host=document.querySelector('#content'),profile={id:1,display_name:'Forschung',city_name:'Helfen',avatar:'knight',power:100,castle_level:1,gems:100,prestige_points:0,action_points:100,action_points_max:200,lord_level:1,lord_xp_next:250,alliance:{tag:'Tue',name:'Helfen',role:'vice_leader'}};
 const ctx={base:'',esc:escape,fmt:String,date:v=>new Date(v),duration:String,countdown:String,getState:()=>({city:{world_id:1},player:{name:'Forschung'},troop_defs:[]}),getKingdom:()=>({profile}),getExpeditions:()=>null,getMarket:()=>null,openDialog(){},api:async()=>({profile}),action(){},navigate(){},toast(){},refresh(){},costHtml:()=>''};
 const panels=window.ConquerPanels(ctx);panels.render('profile');locale.apply();assert.equal(host.querySelector('.lok-profile-hero').querySelector('strong').textContent,'Forschung');assert.equal(host.querySelector('.lok-profile-identity').querySelector('strong').textContent,'Forschung');assert.match(host.textContent,/\[Tue\] Helfen/);
 for(const lang of ['fr','de','en']){locale.setLocale(lang);assert.equal(host.querySelector('.alliance-rank-badge').getAttribute('title'),catalogs[lang]['alliance_rank.label.vice_leader']);assert.equal(host.querySelector('[data-i18n="alliance_rank.role.vice_leader"]').textContent,catalogs[lang]['alliance_rank.role.vice_leader']);assert.equal(host.querySelector('.lok-profile-identity').querySelector('strong').textContent,'Forschung');}
 app.load('progression-panel.js');window.ConquerTalents=()=>({render(){},onClick(){return false;}});const panel=new Element('div',{'id':'panel-dialog','data-panel':'events'});document.body.append(panel);const events=window.ConquerProgression({...ctx,api:async()=>({events:{invasions:[],events:[],chapter:1}})});events.render('events');await Promise.resolve();locale.apply();const days=host.querySelectorAll('.event-week')[0].querySelectorAll('h3');assert.equal(days.length,7);assert.ok(days.some(x=>x.textContent.startsWith('Tue')));assert.ok(days.every(x=>!x.textContent.includes('Kills')));
 app.load('inventory-overview.js');assert.equal(window.ConquerInventoryOverview.formatTime(183840),'2 d 3 hr 4 min');locale.setLocale('de');assert.equal(window.ConquerInventoryOverview.formatTime(183840),'2 Tg. 3 Std. 4 Min.');locale.setLocale('fr');assert.equal(window.ConquerInventoryOverview.formatTime(183840),'2 j 3 h 4 min');
 app.load('boss-mechanic.js');host.innerHTML=window.ConquerBossMechanic.render({id:'grumwald_regeneration',heal_percent:20,counter_power_percent:30,countered:true,counter_power_share_percent:50,hp_restored:0});locale.apply();assert.ok(!host.textContent.includes('Nach einem'));assert.ok(!host.textContent.includes('boss.grumwald'));
 let copied='',shared='';app.sandbox.navigator.clipboard={writeText:async value=>{copied=value;}};app.sandbox.history={state:{},pushState(state){this.state=state;}};
 const reportRoot=new Element('dialog',{id:'game-dialog'});document.body.append(reportRoot);
 const army=name=>({name,totals:{sent:1001,dead:3,injured:4,survived:994,power_lost:7},troops:[],equipment:null,talents:null,hunter_level:1});
 const battle={id:7,created_at:'2026-09-30 12:00:00',target_x:3,target_y:4,outcome:'attacker_wins',details:{battle_kind:'city',perspective:'attacker',combat:{attacker:{armies:[army('Forschung')],totals:army('').totals,types:{}},defender:{armies:[army('Helfen')],totals:army('').totals,types:{}}}}};
 app.load('combat-report.js');const combat=window.ConquerCombatReport({...ctx,unitName:t=>t.name,getState:()=>({troop_defs:[],reports:[]}),openDialog:html=>{reportRoot.innerHTML=html;},shareReport:text=>{shared=text;}});
 locale.setLocale('en');combat.open(battle);locale.apply();assert.equal(reportRoot.querySelector('.cr-identity').querySelector('strong').textContent,'Forschung');assert.match(reportRoot.textContent,/Fallen/);assert.ok(!reportRoot.textContent.includes('Liked'));
 await reportRoot.listeners.click({target:{closest:()=>({dataset:{combat:'copy'}})}});assert.ok(copied.startsWith('Union of Kingdoms · Battle report #7'));assert.match(copied,/Forschung versus Helfen/);assert.match(copied,/3 fallen, 4 wounded/);
 await reportRoot.listeners.click({target:{closest:()=>({dataset:{combat:'share'}})}});assert.match(shared,/Player battle report/);assert.match(shared,/Forschung versus Helfen/);
 const monster={id:8,created_at:'2026-09-30 12:00:00',target_x:3,target_y:4,outcome:'attacker_wins',details:{monster_name:'Orc',source_snapshot:{identity:{name:'Forschung',alliance_tag:'Helfen'},equipment:[],hunter:{talents:[]}},troops:[{sent:12,dead:3,injured:4,survived:5}],monster_hp_after:0,monster_hp_before:100}};
 app.load('monster-report.js');reportRoot.innerHTML=window.ConquerMonsterReport.render(monster);window.ConquerMonsterReport.bind({root:reportRoot,getReport:()=>monster,toast(){},shareReport:text=>{shared=text;}});locale.apply();assert.match(reportRoot.textContent,/\[Helfen\] Forschung/);
 await reportRoot.listeners.click({target:{closest:()=>({dataset:{monster:'copy'}})}});assert.ok(copied.startsWith('Union of Kingdoms · Monster battle report #8'));assert.match(copied,/\[Helfen\] Forschung versus Orc/);assert.match(copied,/3 fallen, 4 wounded/);assert.match(copied,/Monster HP after \/ before battle: 0 \/ 100/);
 await reportRoot.listeners.click({target:{closest:()=>({dataset:{monster:'share'}})}});assert.match(shared,/Monster battle report/);assert.match(shared,/\[Helfen\] Forschung versus Orc/);
 locale.setLocale('fr');let requests=[];const deferred=runtime({stored:'fr',provided:{en:catalogs.en},sourceCatalogs:{de:catalogs.de},urls:{fr:'/fr.json'},fetch:async url=>{requests.push(url);return{ok:true,json:async()=>catalogs.fr};}});await deferred.locale.ready;assert.deepEqual(requests,['/fr.json']);assert.equal(deferred.locale.t('community.view_report'),'Voir le rapport');assert.equal(deferred.locale.text('Bericht ansehen'),locale.text('Bericht ansehen'),'DE source index works without downloading the DE destination catalogue');
 const fallback=runtime({stored:'fr',provided:{en:catalogs.en},sourceCatalogs:{de:catalogs.de},urls:{fr:'/fr.json'},fetch:async()=>{throw Error('offline');}});await fallback.locale.ready;assert.equal(fallback.locale.t('community.view_report'),'View report','A failed target catalogue keeps English usable');
 const recover=runtime({provided:{},sourceCatalogs:{de:catalogs.de},urls:{en:'/en.json'},fetch:async()=>({ok:true,json:async()=>catalogs.en})});await recover.locale.ready;assert.equal(recover.locale.t('community.view_report'),'View report','Missing initial EN script recovers through JSON');
 console.log('PASS localization: EN default/fallback, lazy catalogues, opaque player/alliance/chat data, editorial chat controls, real profile/calendar renderers, time units, boss rules, player/monster report displays and localized clipboard/share summaries.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
