'use strict';
// Isolated collection fixture: actions are captured and never reach the live account or API.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert');
const {pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-march-skins-'));
const styles=[...fs.readFileSync(root+'/views/game.php','utf8').matchAll(/assets\/css\/([a-z0-9-]+)\.css/g)].map(m=>fs.readFileSync(root+'/assets/css/'+m[1]+'.css','utf8')).join('\n');
const js=['castle-skins.js','march-skins.js','village-menu.js'].map(file=>fs.readFileSync(root+'/assets/js/'+file,'utf8')).join('\n');
fs.writeFileSync(out+'/fixture.html',`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${styles}</style><body class="mobile-game"><dialog id="game-dialog"><button class="dialog-close" aria-label="Schließen">×</button><div id="dialog-content"></div></dialog><script>${js}</script><script>
const catalog=ConquerMarchSkins.entries;window.sent=[];window.pending=[];
window.K={profile:{display_name:'Eichenwacht',city_skin:'ironkeep',march_skin:'ironkeep',gems:1800},march_skins:{equipped:'ironkeep',bonus_pct:5,entries:catalog.map(e=>({...e,owned:['ironkeep','yggdrasil'].includes(e.id),equipped:e.id==='ironkeep',can_claim:e.id==='default'}))}};
window.resolveAction=()=>pending.shift()?.({state:K});
window.village=ConquerVillage({base:${JSON.stringify(pathToFileURL(root).href)},esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt:n=>Math.floor(Number(n)||0).toLocaleString('de-DE'),getState:()=>({player:{name:'Eichenwacht'},city:{id:1,coord_x:83,coord_y:70,castle_level:2},players:[]}),getKingdom:()=>K,openDialog:html=>{const d=document.querySelector('#game-dialog'),c=document.querySelector('#dialog-content');d.querySelector('.popup-heading')?.remove();c.innerHTML=html;const heading=c.querySelector('h2'),header=document.createElement('header');header.className='popup-heading';header.append(heading);d.insertBefore(header,c);d.classList.add('has-popup-heading');if(!d.open)d.showModal();},navigate(){},action:(...args)=>{sent.push(args);return new Promise(resolve=>pending.push(resolve));},toast(){},marchPanel:{}});
document.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button)village.onClick(button.dataset.action,button)});window.openMarchSkins=()=>village.onClick('march-skins',{dataset:{}});openMarchSkins();
</script></body></html>`);
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})}),page=await browser.newPage();const errors=[];page.on('pageerror',error=>errors.push(error.message));try{
 await page.goto(pathToFileURL(out+'/fixture.html').href);
 assert.equal(await page.getByRole('button',{name:/Marsch-Skins 2\/18/}).getAttribute('aria-pressed'),'true');
 assert.equal(await page.locator('.march-speed-seal').innerText(),'+5%');
 assert.match(await page.locator('.march-skin-benefit').innerText(),/nicht.*stapelt|stapelt.*nicht/i);
 const ids=new Set();for(let p=0;p<5;p++){for(const id of await page.locator('.march-skin-option').evaluateAll(items=>items.map(item=>item.dataset.id)))ids.add(id);if(p<4)await page.getByRole('button',{name:'Nächste Marsch-Skin-Seite'}).click();}
 assert.deepEqual([...ids].sort(),catalogIds(root).sort());console.log('PASS all 18 paired march skins are reachable');
 await page.getByRole('button',{name:'Im Besitz 2',exact:true}).click();
 assert.deepEqual(await page.locator('.march-skin-option').evaluateAll(items=>items.map(item=>item.dataset.id)),['ironkeep','yggdrasil']);
 assert.equal(await page.locator('[data-id="ironkeep"]').getAttribute('aria-pressed'),'true');console.log('PASS owned filter and equipped state are distinct');
 await page.evaluate(()=>village.onClick('march-skin-detail',{dataset:{id:'default'}}));
 const claim=page.getByRole('button',{name:'Kostenlos abholen'});await claim.click();assert(await claim.isDisabled());
 assert.deepEqual((await page.evaluate(()=>sent.at(-1))).slice(0,2),['kingdom/action',{action:'march_skin.claim',march_skin:'default'}]);await page.evaluate(()=>resolveAction());console.log('PASS earnable default skin uses the claim action');
 await page.evaluate(()=>village.onClick('march-skin-detail',{dataset:{id:'rosehall'}}));await page.getByRole('button',{name:'Kaufen · ◆ 1.200'}).click();
 assert.match(await page.getByText(/Möchtest du „Rosenhirsch“/).innerText(),/◆ 1\.200/);assert.equal(await page.getByText('Danach').locator('xpath=following-sibling::strong[1]').innerText(),'◆ 600');
 const buy=page.getByRole('button',{name:'Für ◆ 1.200 kaufen'});await buy.click();assert(await buy.isDisabled());assert.deepEqual((await page.evaluate(()=>sent.at(-1))).slice(0,2),['kingdom/action',{action:'march_skin.buy',march_skin:'rosehall'}]);await page.evaluate(()=>resolveAction());console.log('PASS gem purchase requires a concrete confirmation and is disabled while pending');
 await page.evaluate(()=>village.onClick('march-skin-detail',{dataset:{id:'phoenix'}}));assert(await page.getByRole('button',{name:'Kaufen · ◆ 2.400'}).isDisabled());assert.match(await page.locator('.notice.error').innerText(),/600/);console.log('PASS insufficient gems cannot submit a purchase');
 await page.evaluate(()=>village.onClick('march-skin-detail',{dataset:{id:'dragon'}}));assert.equal(await page.locator('.march-skin-detail h3').innerText(),'Drachenmarsch');assert.match(await page.locator('.skin-match').innerText(),/Drachenfestung/);assert(await page.getByRole('button',{name:'Kaufen · ◆ 2.400'}).isDisabled());console.log('PASS dragon march is paired with the animated dragon fortress at its mythic price');
 await page.evaluate(()=>village.onClick('march-skin-detail',{dataset:{id:'phoenix'}}));const portrait=page.locator('.march-skin-portrait img');await page.waitForFunction(()=>document.querySelector('.march-skin-portrait img')?.src.includes('flight-phoenix.webp'));await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('.march-skin-portrait img')?.src.includes('flight-phoenix.png'));await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>document.querySelector('.march-skin-portrait img')?.src.includes('flight-phoenix.webp'));await portrait.dispatchEvent('error');await page.waitForFunction(()=>document.querySelector('.march-skin-portrait img')?.src.includes('flight-phoenix.png'));assert.equal(await portrait.getAttribute('data-march-motion-failed'),'1');console.log('PASS open portrait switches for reduced motion and falls back from broken motion to its still image');
 await page.evaluate(()=>village.onClick('march-skin-detail',{dataset:{id:'yggdrasil'}}));const equip=page.getByRole('button',{name:'Marsch-Skin anlegen'});await equip.click();assert.deepEqual((await page.evaluate(()=>sent.at(-1))).slice(0,2),['kingdom/action',{action:'march_skin.equip',march_skin:'yggdrasil'}]);await page.evaluate(()=>resolveAction());console.log('PASS owned skin equips independently with its stable identifier');
 for(const viewport of [{width:390,height:844},{width:320,height:568},{width:568,height:320},{width:1280,height:720}]){await page.setViewportSize(viewport);await page.evaluate(()=>openMarchSkins());const metrics=await page.evaluate(()=>{const dialog=document.querySelector('#game-dialog').getBoundingClientRect();const outside=[...document.querySelectorAll('#game-dialog button')].filter(button=>{const box=button.getBoundingClientRect();return box.width&&box.height&&(box.left<dialog.left-1||box.right>dialog.right+1||box.top<dialog.top-1||box.bottom>dialog.bottom+1)}).map(button=>button.textContent.trim());const grid=document.querySelector('.march-skin-options');return{outside,grid:{scrollWidth:grid.scrollWidth,clientWidth:grid.clientWidth,scrollHeight:grid.scrollHeight,clientHeight:grid.clientHeight},portraitHeights:[...document.querySelectorAll('.march-skin-portrait')].map(node=>node.clientHeight)}});assert.deepEqual(metrics.outside,[],JSON.stringify({viewport,metrics}));assert(metrics.grid.scrollWidth<=metrics.grid.clientWidth+1&&metrics.grid.scrollHeight<=metrics.grid.clientHeight+1,JSON.stringify({viewport,metrics}));assert(metrics.portraitHeights.every(height=>height>=28),JSON.stringify({viewport,metrics}));if(viewport.width===390||viewport.height===320)await page.screenshot({path:path.join(out,viewport.width+'x'+viewport.height+'.png')});console.log('PASS '+viewport.width+'×'+viewport.height+' collection controls remain reachable');}
 const normalized=await page.evaluate(()=>({unknown:ConquerMarchSkins.get('bad').id,ids:ConquerMarchSkins.ids,state:ConquerMarchSkins.normalizeState(K.march_skins)}));assert.equal(normalized.unknown,'default');assert.equal(normalized.ids.length,18);assert.equal(normalized.state.entries.find(entry=>entry.id==='dragon').name,'Drachenmarsch');assert.equal(normalized.state.equipped,'ironkeep');assert.equal(normalized.state.entries.find(entry=>entry.id==='ironkeep').equipped,true);
 assert.deepEqual(errors,[]);console.log('PASS catalog normalization and browser console');console.log('Screenshots/fixture: '+out);
}finally{await browser.close()}})().catch(error=>{console.error(error);process.exitCode=1});
function catalogIds(projectRoot){const code=fs.readFileSync(projectRoot+'/assets/js/castle-skins.js','utf8'),match=[...code.matchAll(/\{id:'([^']+)'/g)];return match.map(item=>item[1]);}
