'use strict';
// Isolated collection fixture: actions are captured and never reach the live account or API.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert');
const {pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-march-skins-'));
const styles=[...fs.readFileSync(root+'/views/game.php','utf8').matchAll(/assets\/css\/([a-z0-9-]+)\.css/g)].map(m=>fs.readFileSync(root+'/assets/css/'+m[1]+'.css','utf8')).join('\n');
const js=['castle-skins.js','march-skins.js','village-menu.js'].map(file=>fs.readFileSync(root+'/assets/js/'+file,'utf8')).join('\n');
fs.writeFileSync(out+'/fixture.html',`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${styles}</style><body class="mobile-game"><dialog id="game-dialog"><button class="dialog-close" aria-label="Schließen">×</button><div id="dialog-content"></div></dialog><script>${js}</script><script>
const catalog=ConquerMarchSkins.entries;window.sent=[];window.pending=[];
window.K={profile:{display_name:'Eichenwacht',city_skin:'forest',march_skin:'forest',gems:1800},march_skins:{equipped:'forest',bonus_pct:5,entries:catalog.map(e=>({...e,owned:['forest','water'].includes(e.id),equipped:e.id==='forest',can_claim:e.id==='default'}))}};
window.resolveAction=()=>pending.shift()?.({state:K});
window.village=ConquerVillage({base:${JSON.stringify(pathToFileURL(root).href)},esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt:n=>Math.floor(Number(n)||0).toLocaleString('de-DE'),getState:()=>({player:{name:'Eichenwacht'},city:{id:1,coord_x:83,coord_y:70,castle_level:2},players:[]}),getKingdom:()=>K,openDialog:html=>{const d=document.querySelector('#game-dialog'),c=document.querySelector('#dialog-content');d.querySelector('.popup-heading')?.remove();c.innerHTML=html;const heading=c.querySelector('h2'),header=document.createElement('header');header.className='popup-heading';header.append(heading);d.insertBefore(header,c);d.classList.add('has-popup-heading');if(!d.open)d.showModal();},navigate(){},action:(...args)=>{sent.push(args);return new Promise(resolve=>pending.push(resolve));},toast(){},marchPanel:{}});
document.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button)village.onClick(button.dataset.action,button)});window.openMarchSkins=()=>village.onClick('march-skins',{dataset:{}});openMarchSkins();
</script></body></html>`);
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})}),page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(pathToFileURL(out+'/fixture.html').href);
 assert.equal(await page.getByRole('button',{name:/Marsch-Skins 2\/5/}).getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.march-speed-seal').innerText(),'+5%');
 assert.deepEqual(await page.locator('.march-skin-option').evaluateAll(items=>items.map(i=>i.dataset.id)),['default','forest','fire','water','wind']);
 await page.getByRole('button',{name:'Im Besitz 2',exact:true}).click();assert.deepEqual(await page.locator('.march-skin-option').evaluateAll(items=>items.map(i=>i.dataset.id)),['forest','water']);
 await page.evaluate(()=>village.onClick('march-skin-detail',{dataset:{id:'default'}}));const claim=page.getByRole('button',{name:'Kostenlos abholen'});await claim.click();assert(await claim.isDisabled());assert.equal((await page.evaluate(()=>sent.at(-1)))[1].action,'march_skin.claim');await page.evaluate(()=>resolveAction());
 await page.evaluate(()=>village.onClick('march-skin-detail',{dataset:{id:'fire'}}));const buy=page.getByRole('button',{name:'Sofort kaufen · ◆ 1.200'});await buy.click();assert(await buy.isDisabled());assert.deepEqual((await page.evaluate(()=>sent.at(-1))).slice(0,2),['kingdom/action',{action:'march_skin.buy',march_skin:'fire'}]);await page.evaluate(()=>resolveAction());
 await page.evaluate(()=>{K.profile.gems=600;village.onClick('march-skin-detail',{dataset:{id:'wind'}})});assert(await page.getByRole('button',{name:'Sofort kaufen · ◆ 1.200'}).isDisabled());assert.match(await page.locator('.notice.error').innerText(),/600/);
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.querySelector('.march-skin-portrait img').src.includes('/march-wind.webp'));await page.emulateMedia({reducedMotion:'no-preference'});await page.waitForFunction(()=>document.querySelector('.march-skin-portrait img').src.includes('/animated-march-wind.webp'));
 await page.locator('.march-skin-portrait img').dispatchEvent('error');await page.waitForFunction(()=>document.querySelector('.march-skin-portrait img').src.includes('/march-wind.webp'));
 await page.evaluate(()=>village.onClick('march-skin-detail',{dataset:{id:'water'}}));await page.getByRole('button',{name:'Marsch-Skin anlegen'}).click();assert.equal((await page.evaluate(()=>sent.at(-1)))[1].march_skin,'water');await page.evaluate(()=>resolveAction());
 for(const viewport of [{width:390,height:844},{width:320,height:568},{width:568,height:320},{width:1280,height:720}]){await page.setViewportSize(viewport);await page.evaluate(()=>openMarchSkins());for(const card of await page.locator('.march-skin-option').all()){await card.scrollIntoViewIfNeeded();const r=await card.boundingBox();assert(r.x>=0&&r.x+r.width<=viewport.width+1);}assert(await page.locator('.march-skin-options').evaluate(el=>el.scrollWidth<=el.clientWidth+1));console.log('PASS '+viewport.width+'x'+viewport.height+' collection reachable');}
 await page.evaluate(()=>{K.march_skins.entries.push({...ConquerMarchSkins.get('dragon'),owned:true});openMarchSkins()});assert.equal(await page.locator('[data-id="dragon"]').count(),1);assert.equal(await page.locator('[data-id="phoenix"]').count(),0);await page.locator('[data-id="dragon"]').click();assert.match(await page.locator('.march-skin-portrait img').getAttribute('src'),/flight-dragon/);await page.getByRole('button',{name:'Marsch-Skin anlegen'}).click();assert.equal((await page.evaluate(()=>sent.at(-1)))[1].march_skin,'dragon');await page.evaluate(()=>resolveAction());
 assert.deepEqual(errors,[]);console.log('PASS active claims/purchases, retained historical ownership, reduced-motion and pending-action guard; '+out);
 }finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
