'use strict';
// Memory-only responses: no real players, servers or database writes.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert'),{pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-melusina-panel-'));
const css=['game','game-theme','mobile-shell','game-popups','popup-surfaces','popup-skin','window-layout','dungeon-panel','dungeon-planner','village-theme'].map(n=>fs.readFileSync(path.join(root,'assets/css',n+'.css'),'utf8')).join('\n');
const script=fs.readFileSync(path.join(root,'assets/js/dungeon-panel.js'),'utf8'),en=JSON.parse(fs.readFileSync(path.join(root,'data/i18n/en.json'),'utf8'));
const dungeon={dungeon_code:'melusina_well',name:en['melusina.dungeon_name'],theme:en['melusina.dungeon_theme'],base_duration:7200,treasure_code:60400102};
const state={world_id:7,player_id:5,rotation_ends_at:'2099-10-12T00:00:00Z',rotation:[{...dungeon,dungeon_code:'sunken_temple',name:'Sunken Temple'}],next_rotation:[],permanent_dungeons:[dungeon],available_troops:{50100101:1000},eligible_roles:['attack'],runs:[],melusina:{available:true,accepted:false,fragments:3,fragments_required:3,keys:0,can_craft:false,pity_count:4,pity_limit:5,actions_until_guaranteed:1,drop_chance:.35,first_clear_at:null,reserved_keys:0,in_transit_fragments:1,entrance:{x:105,y:109,dungeon_code:'melusina_well'},sources:[{type:'monster',id:33,x:110,y:118,level:3,name:'Guardian <script>not executable</script>'},{type:'gather',id:45,x:113,y:119,level:2,name:'Food'}]}};
fs.writeFileSync(path.join(out,'fixture.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${css}html,body{overflow:auto;height:auto}body.mobile-game #panel-dialog{position:static!important;display:block!important;box-sizing:border-box;width:100%!important;max-width:1100px!important;height:auto!important;max-height:none!important;margin:0 auto!important;padding:0!important;transform:none!important}#content{display:block;box-sizing:border-box;width:100%;max-width:1100px;margin:auto;padding:12px;overflow:auto;height:100vh}</style><body class="mobile-game"><dialog id="panel-dialog" data-panel="dungeons" open><div id="content"></div></dialog><script>${script}</script><script>
const messages=${JSON.stringify(en)},fixture=${JSON.stringify(state).replace(/</g,'\\u003c')};
window.ConquerLocale={locale:'en',t:(k,p={})=>String(messages[k]||k).replace(/\\{(\\w+)\\}/g,(s,n)=>p[n]??s),text:v=>v};
window.K={city:{world_id:7},troop_defs:[]};window.fixtureState=fixture;window.calls=[];window.jumps=[];window.notices=[];window.uncertain=false;
const clone=x=>JSON.parse(JSON.stringify(x)),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.panel=ConquerDungeons({base:${JSON.stringify(pathToFileURL(root).href)},getState:()=>K,esc,fmt:n=>Number(n).toLocaleString('en-US'),toast:m=>notices.push(m),refresh:async()=>{},onMelusinaSource:(s,w)=>jumps.push({kind:'source',source:s,world:w}),onMelusinaEntrance:(s,w)=>jumps.push({kind:'entrance',source:s,world:w}),api:async(path,payload)=>{if(!payload)return clone(fixtureState);calls.push(clone(payload));if(payload.action==='accept_melusina'){fixtureState.melusina.accepted=true;fixtureState.melusina.can_craft=true;}if(payload.action==='craft_melusina_key'){if(uncertain){uncertain=false;throw new Error('Connection lost; retry safely.');}fixtureState.melusina.fragments-=3;fixtureState.melusina.keys++;fixtureState.melusina.can_craft=fixtureState.melusina.fragments>=3;}return {message:'Saved',state:clone(fixtureState)};}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)panel.onClick(b.dataset.action,b)});panel.render('dungeons');
</script></html>`);
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'}),page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));try{
 await page.goto(pathToFileURL(path.join(out,'fixture.html')).href);await page.locator('.melusina-adventure').waitFor();
 assert(await page.locator('[data-action="dungeon-melusina-accept"]').isVisible());
 for(const [width,height] of [[1280,800],[390,844],[667,375]]){await page.setViewportSize({width,height});assert(await page.locator('.melusina-adventure .button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)), 'Initial quest touch targets in themed panel '+width+'x'+height);const colors=await page.locator('.melusina-heading').evaluate(e=>({background:getComputedStyle(e).backgroundColor,foreground:[e,...e.children].map(n=>getComputedStyle(n).color)}));const luminance=value=>{const rgb=value.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4});return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]};const bg=luminance(colors.background);for(const color of colors.foreground){const fg=luminance(color),contrast=(Math.max(bg,fg)+.05)/(Math.min(bg,fg)+.05);assert(contrast>=4.5,'Regional header text contrast '+contrast);}}assert.equal(await page.locator('[data-action="dungeon-melusina-craft"]').count(),0);assert.equal(await page.evaluate(()=>calls.length),0,'Opening never accepts or crafts automatically');
 await page.locator('[data-action="dungeon-melusina-accept"]').click();await page.locator('[data-action="dungeon-melusina-craft"]').waitFor();assert.equal(await page.evaluate(()=>calls[0].action),'accept_melusina');assert(await page.locator('[data-action="dungeon-melusina-craft"]').isEnabled());
 await page.evaluate(()=>panel.refresh());assert.equal(await page.evaluate(()=>calls.length),1,'Polling with three fragments never crafts');
 const pity=await page.locator('.melusina-pity').innerText();assert(!pity.includes('%')&&pity.includes('fragment: 1')&&pity.includes('4/5'),'Drop chance is hidden and remaining pity stays visible');assert((await page.locator('.melusina-transit').innerText()).includes('troops: 1.'));
 await page.locator('.melusina-sources summary').click();assert.equal(await page.locator('.melusina-sources script').count(),0,'Source labels are escaped');assert((await page.locator('.melusina-sources').innerText()).includes('defeat solo monsters'),'Fragment guidance explicitly limits kills to solo monsters');
 await page.locator('[data-action="dungeon-melusina-source"]').first().click();assert.deepEqual(await page.evaluate(()=>jumps[0]),{kind:'source',source:state.melusina.sources[0],world:7});assert.equal(await page.evaluate(()=>calls.length),1,'Map navigation never sends a march');
 await page.locator('[data-action="dungeon-melusina-entrance"]').click();assert.equal(await page.evaluate(()=>jumps[1].kind),'entrance');
 for(const [width,height]of [[1280,800],[390,844],[667,375]]){await page.setViewportSize({width,height});await page.locator('.melusina-intro>img').evaluate(e=>e.decode());assert.equal(await page.locator('.melusina-adventure').evaluate(e=>e.scrollWidth>e.clientWidth+2),false,`Adventure fits ${width}x${height}`);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false,`Page fits ${width}x${height}`);assert(await page.locator('.melusina-content button').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().height>=44)),`Touch targets ${width}x${height}`);await page.evaluate(()=>document.querySelector('#content').scrollTop=0);await page.screenshot({path:path.join(out,`melusina-${width}x${height}.png`),fullPage:true});}
 await page.evaluate(()=>uncertain=true);await page.locator('[data-action="dungeon-melusina-craft"]').click();await page.locator('.dungeon-error').waitFor();assert((await page.locator('.dungeon-error').innerText()).includes('Connection lost'));await page.locator('[data-action="dungeon-melusina-craft"]').click();await page.waitForFunction(()=>fixtureState.melusina.keys===1);assert.deepEqual(await page.evaluate(()=>calls.slice(1).map(c=>c.request_id)),await page.evaluate(()=>[calls[1].request_id,calls[1].request_id]),'Retry preserves the operation ID after uncertain failure');assert(await page.locator('[data-action="dungeon-melusina-craft"]').isDisabled());
 await page.locator('[data-action="dungeon-create-open"][data-id="melusina_well"]').click();assert.equal(await page.locator('form[data-id="melusina_well"]').count(),1,'Permanent adventure uses the shared planner');assert((await page.locator('.dungeon-planner>.dungeon-key-explanation').innerText()).includes('whole party'));await page.locator('[data-action="dungeon-planning-close"]').click();
 await page.evaluate(()=>{fixtureState.runs=[{id:40,dungeon:fixtureState.permanent_dungeons[0],dungeon_code:'melusina_well',leader_player_id:5,difficulty:'normal',stance:'cautious',status:'running',members:[{player_id:5,role:'attack',username:'Hero',total_troops:50},{player_id:6,role:'attack',username:'Friend',total_troops:50}],progress:{encounters_done:1,encounters_total:3},votes:[],can_cancel:true,key_status:'reserved',story_mode:'first'}]});await page.evaluate(()=>panel.refresh());await page.locator('[data-action="dungeon-tab"][data-id="parties"]').click();assert(await page.locator('[data-action="dungeon-cancel"]').isVisible(),'Leader can cancel a running regional adventure');assert((await page.locator('.melusina-party-note').innerText()).includes('One key is reserved'));
 await page.evaluate(()=>{const run=fixtureState.runs[0];run.status='completed';run.key_status='consumed';run.can_cancel=false;run.story_mode='first';run.reward={};fixtureState.melusina.first_clear_at='2099-10-05T12:00:00Z';});await page.evaluate(()=>panel.refresh());await page.locator('[data-action="dungeon-tab"][data-id="reports"]').click();assert((await page.locator('.melusina-report-story').innerText()).includes('Melusina is free'),'First completion tells the rescue');await page.evaluate(()=>fixtureState.runs[0].story_mode='echo');await page.evaluate(()=>panel.refresh());assert((await page.locator('.melusina-report-story').innerText()).includes('An echo laid to rest'),'Repeat completion does not rescue her again');
 await page.evaluate(()=>{fixtureState.runs[0].status='failed';fixtureState.runs[0].key_status='returned';});await page.evaluate(()=>panel.refresh());const echoFailure=await page.locator('.melusina-report-story').innerText();assert(echoFailure.includes('Melusina remains free')&&echoFailure.includes('party’s key return')&&!echoFailure.includes('well remains sealed'),'Echo defeat preserves the first rescue and explains key return');
 await page.evaluate(()=>fixtureState.runs[0].story_mode='first');await page.evaluate(()=>panel.refresh());assert((await page.locator('.melusina-report-story').innerText()).includes('The well remains sealed'),'Failed first attempt retains its own unfinished rescue story');
 await page.evaluate(()=>{K.city.world_id=8;fixtureState.world_id=8;fixtureState.melusina.available=false;fixtureState.permanent_dungeons=[];fixtureState.runs=[];panel.render('dungeons')});await page.evaluate(()=>panel.refresh());await page.locator('[data-action="dungeon-tab"][data-id="overview"]').click();assert.equal(await page.locator('.melusina-adventure').count(),0,'Unavailable worlds have no regional quest or leaked progress');
 assert.deepEqual(errors,[]);console.log('PASS Melusina panel; screenshots: '+out);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
