'use strict';
// Isolated visual contract: no account, payment provider or live API is used.
const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert');
const {pathToFileURL}=require('url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-name-frames-'));
const view=fs.readFileSync(path.join(root,'views/game.php'),'utf8');
const styleNames=[...view.matchAll(/assets\/css\/([a-z0-9-]+)\.css/g)].map(match=>match[1]);
const frameAssetBase=pathToFileURL(path.join(root,'assets/art/name-frames')).href;
const styles=[...new Set(styleNames)].map(name=>fs.readFileSync(path.join(root,'assets/css',name+'.css'),'utf8')).join('\n').replaceAll('../art/name-frames/',frameAssetBase+'/');
const scripts=['castle-skins.js','march-skins.js','name-frames.js','village-menu.js'].map(name=>fs.readFileSync(path.join(root,'assets/js',name),'utf8')).join('\n');
const owned=['default','forest','water'];
fs.writeFileSync(path.join(out,'fixture.html'),`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${styles}</style><body class="mobile-game"><header class="topbar"><div class="hud-profile"><button class="player-button" id="account-button"><span class="avatar" aria-hidden="true">♜</span><span id="player-hud-name" data-name-frame-self>Waldwacht<small>123 Macht</small></span></button></div></header><div class="map-overlay-shell" style="position:absolute;left:-1000px"><button class="atlas-marker atlas-marker--players"><span class="atlas-marker-name name-frame name-frame--water" data-name-frame="water"><span class="atlas-marker-level">16</span><span class="name-frame-label">Ekkii1992</span></span></button></div><dialog id="game-dialog"><button class="dialog-close" aria-label="Schließen">×</button><div id="dialog-content"></div></dialog><script>${scripts}</script><script>
window.K={profile:{display_name:'Waldwacht',city_skin:'forest',name_frame:'default'},name_frames:{equipped:'default',entries:ConquerNameFrames.entries.map(entry=>({id:entry.id,owned:${JSON.stringify(owned)}.includes(entry.id),equipped:entry.id==='default'}))},march_skins:{entries:[]}};
window.sent=[];window.frameEvents=0;window.addEventListener('conquer:name-frame-changed',()=>frameEvents++);ConquerNameFrames.syncSelf({equipped:'forest'});
const openDialog=html=>{const dialog=document.querySelector('#game-dialog'),content=document.querySelector('#dialog-content');dialog.querySelector('.popup-heading')?.remove();content.innerHTML=html;const heading=content.querySelector('h2');if(heading){const header=document.createElement('header');header.className='popup-heading';header.append(heading);dialog.insertBefore(header,content);}if(!dialog.open)dialog.showModal();};
window.village=ConquerVillage({base:${JSON.stringify(pathToFileURL(root).href)},esc:value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),fmt:String,getState:()=>({player:{name:'Waldwacht'},city:{id:1,coord_x:64,coord_y:64,castle_level:5},players:[]}),getKingdom:()=>K,openDialog,navigate(){},action:async(...args)=>{sent.push(args);return{};},toast(){},marchPanel:{}});
document.addEventListener('click',event=>{const button=event.target.closest('[data-action]');if(button)village.onClick(button.dataset.action,button);});
village.onClick('city-skins',{dataset:{}});
</script></body></html>`);
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHANNEL?{channel:process.env.PLAYWRIGHT_CHANNEL}:{})}),page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
 try{
  await page.goto(pathToFileURL(path.join(out,'fixture.html')).href);
  const catalog=await page.evaluate(()=>({ids:ConquerNameFrames.ids,unknown:ConquerNameFrames.get('UNKNOWN').id,direct:ConquerNameFrames.resolve('wind'),invalid:ConquerNameFrames.resolve({name_frame:'UNKNOWN'},'water'),owned:ConquerNameFrames.normalizeState({entries:[{id:'eclipse',owned:true},{id:'default',owned:false}]}).entries.filter(entry=>entry.owned).map(entry=>entry.id)}));
  assert.deepEqual(catalog.ids,['default','forest','fire','water','wind']);assert.deepEqual(catalog.ids,await page.evaluate(()=>ConquerCastleSkins.ids));assert.equal(new Set(catalog.ids).size,5);assert.equal(catalog.unknown,'default');assert.equal(catalog.direct,'wind');assert.equal(catalog.invalid,'water');assert.deepEqual(catalog.owned,['default','eclipse']);
  const hud=page.locator('#player-hud-name');assert.equal(await hud.getAttribute('data-name-frame'),'forest');assert.equal(await hud.locator(':scope > [data-name-frame-ornament]').count(),2);assert.equal(await hud.locator('small').innerText(),'123 Macht');assert.equal(await page.evaluate(()=>frameEvents),1);
  const combined=await page.locator('.map-overlay-shell .atlas-marker-name').evaluate(node=>({image:getComputedStyle(node).backgroundImage,levelImage:getComputedStyle(node.querySelector('.atlas-marker-level')).backgroundImage,children:[...node.children].map(child=>child.className)}));assert.match(combined.image,/nameplate-combined-water\.webp/);assert.equal(combined.levelImage,'none');assert.deepEqual(combined.children,['atlas-marker-level','name-frame-label']);
  await page.getByRole('button',{name:/Namensrahmen/}).click();assert.equal(await page.locator('.name-frame-card').count(),5);assert.equal(await page.locator('.name-frame-card .name-frame').count(),5);
  const visualSignatures=await page.locator('.name-frame-card .name-frame').evaluateAll(frames=>frames.map(frame=>{const style=getComputedStyle(frame),ornament=getComputedStyle(frame.querySelector('.name-frame-ornament'));return [style.backgroundImage,style.borderRadius,ornament.backgroundImage].join('|')}));assert.equal(new Set(visualSignatures).size,5,'every frame has a distinct theme silhouette and material');
  await page.getByRole('button',{name:'Im Besitz 3'}).click();await page.locator('.name-frame-card[data-frame-id="water"] [data-action="name-frame-equip"]').click();await page.waitForFunction(()=>sent.length===1);const sent=await page.evaluate(()=>window.sent);assert.equal(sent[0][0],'kingdom/action');assert.deepEqual(sent[0][1],{action:'name_frame.equip',name_frame:'water'});
  for(const viewport of [{width:320,height:568},{width:390,height:844},{width:568,height:320},{width:1280,height:720}]){await page.setViewportSize(viewport);await page.evaluate(()=>{village.onClick('city-skins',{dataset:{}})});await page.getByRole('button',{name:/Namensrahmen/}).click();const layout=await page.evaluate(()=>({page:document.documentElement.scrollWidth-innerWidth,dialog:document.querySelector('#game-dialog').scrollWidth-document.querySelector('#game-dialog').clientWidth,cards:[...document.querySelectorAll('.name-frame-card')].map(card=>({x:card.scrollWidth-card.clientWidth,y:card.scrollHeight-card.clientHeight}))}));assert(layout.page<=0,JSON.stringify({viewport,layout}));assert(layout.dialog<=1,JSON.stringify({viewport,layout}));assert(layout.cards.every(value=>value.x<=1&&value.y<=1),JSON.stringify({viewport,layout}));await page.screenshot({path:path.join(out,`frames-${viewport.width}x${viewport.height}.png`)});}
  await page.evaluate(()=>{K.name_frames.entries.push({id:'dragon',owned:true});village.onClick('city-skins',{dataset:{}})});await page.getByRole('button',{name:/Namensrahmen/}).click();assert.equal(await page.locator('.name-frame-card[data-frame-id="dragon"]').count(),1);assert.equal(await page.locator('.name-frame-card[data-frame-id="phoenix"]').count(),0);await page.locator('.name-frame-card[data-frame-id="dragon"] [data-action="name-frame-equip"]').click();await page.waitForFunction(()=>sent.length===2);assert.equal((await page.evaluate(()=>sent.at(-1)))[1].name_frame,'dragon');
  await page.evaluate(()=>document.querySelector('#game-dialog').close());for(const viewport of [{width:320,height:568},{width:1280,height:720}]){await page.setViewportSize(viewport);await page.screenshot({path:path.join(out,`hud-${viewport.width}x${viewport.height}.png`)});}
  await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.name-frame--forest .name-frame-ornament').first().evaluate(node=>getComputedStyle(node).animationName),'none');
  assert.deepEqual(errors,[]);console.log('PASS five active themed frames, retained legacy ownership, ownership/equip hook, HUD, accessibility, reduced motion and responsive scrolling collection; '+out);
 }finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
