'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),fixture=require('./fixtures/world_march_motion.cjs'),output=path.join(root,'artifacts/phoenix-refinement-20260913');fs.mkdirSync(output,{recursive:true});
(async()=>{const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(name==='/'){res.setHeader('Content-Type','text/html');res.end(fixture(root));return;}const file=path.resolve(root,'.'+name);if(!name.startsWith('/assets/')||!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.webp')?'image/webp':file.endsWith('.png')?'image/png':'application/octet-stream');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(()=>{demoAuto=false;window.paintCalls=0;const ground=ConquerLandscape.ground;ConquerLandscape.ground=(...a)=>{paintCalls++;return ground(...a)};});
for(const [width,height,region]of [[1280,800,'forest'],[390,844,'ice'],[320,568,'sand'],[844,390,'lava']]){
 await page.setViewportSize({width,height});await page.evaluate(region=>{document.querySelector('#region').value=region;startMarch(5,3000)},region);await page.waitForSelector('.has-flight-animation.is-skinned');
 await page.waitForTimeout(850);await page.screenshot({path:path.join(output,`${width}-flight.png`)});
 await page.waitForFunction(()=>parseFloat(document.querySelector('.atlas-march-party').style.getPropertyValue('--march-charge'))>.2);const before=await page.evaluate(()=>paintCalls);await page.waitForSelector('.atlas-phoenix-impact');
 const canvas=page.locator('.atlas-phoenix-impact');assert.equal(await page.locator('.atlas-impact-emblem').count(),0,'No text glyph in the phoenix effect');
 await page.waitForTimeout(310);await page.screenshot({path:path.join(output,`${width}-arrival.png`)});
 const first=await canvas.evaluate(c=>c.toDataURL());await page.waitForTimeout(240);assert.notEqual(await canvas.evaluate(c=>c.toDataURL()),first,'Effect progresses through different poses');
 await page.waitForTimeout(1800);assert.equal(await canvas.count(),0,'Canvas released after the afterglow');assert.equal(await page.evaluate(()=>paintCalls),before,'Arrival never redraws scenery');await page.evaluate(()=>ConquerWorld.render(options));assert.equal(await canvas.count(),0,'Poll cannot replay arrival');console.log('PASS detailed phoenix and arrival '+width+'x'+height+' '+region);
}
await page.evaluate(()=>{document.querySelector('#region').value='forest';startMarch(9,120)});await page.waitForTimeout(350);assert.equal(await page.locator('.atlas-phoenix-impact').count(),0,'Gatherers do not ignite their destination');
await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>startMarch(5,120));await page.waitForTimeout(300);assert.equal(await page.locator('.atlas-phoenix-impact').count(),0);assert.equal(await page.locator('.atlas-party-skin').evaluate(el=>getComputedStyle(el).rotate),'0deg');
await page.emulateMedia({reducedMotion:'no-preference'});await page.setViewportSize({width:1280,height:800});await page.evaluate(()=>startMarch(5,16000));await page.locator('.atlas-viewport').focus();for(let i=0;i<4;i++)await page.keyboard.press('+');await page.waitForTimeout(2800);await page.screenshot({path:path.join(output,'phoenix-close.png')});assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',errors,output}));
}finally{if(browser)await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
