'use strict';
// Real game.php popup shell and module listeners; all API calls use in-memory fixtures.
const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),assert=require('assert'),{execFileSync}=require('child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-progression-panel-'));
const localeCatalogs=Object.fromEntries(['de','fr','lb'].map(locale=>[locale,JSON.parse(fs.readFileSync(root+'/data/i18n/'+locale+'.json','utf8'))]));
const php=`define('ROOT_DIR',${JSON.stringify(root.replaceAll('\\','/'))});define('APP_BASE','');require ROOT_DIR.'/src/Autoloader.php';(new \\Conquer\\Autoloader(ROOT_DIR.'/src'))->register();$session=['username'=>'Fixture ruler'];require ROOT_DIR.'/views/game.php';`;
let template=execFileSync(process.env.PHP_BINARY||'php',['-r',php],{encoding:'utf8',maxBuffer:3*1024*1024}).replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'');
const end='2099-01-01 00:00:00',start='2026-09-11 12:00:00';
const progression={mastery:{available:2,spent:1,rule:'Jede Burgstufe gibt einen Meisterschaftspunkt.',nodes:[{code:'builder',name:'Baumeister',level:1,max_level:5,description:'2 % schneller bauen je Stufe.'},{code:'guardian',name:'Wächter',level:5,max_level:5,description:'Mehr Verteidigung für deine Stadt.'}]},account:{has_recovery_code:true,sessions:[{user_agent:'Chrome Fixture <img src=x onerror=window.xss=1>',expires_at:end},{user_agent:'Mobile Fixture Device',expires_at:end}]},events:{chapter:3,invasions:[{id:1,chapter:3,state:'active',starts_at:start,ends_at:end,target:10000,contribution:3500,mine:20,claimed:0},{id:2,chapter:2,state:'victory',starts_at:start,ends_at:end,target:5000,contribution:5000,mine:100,claimed:1}],missions:[{state:'marching',arrival_at:end,return_at:end}],objectives:[{id:71,shrine_tier:'C',coord_x:128,coord_y:128,alliance_name:'<img src=x onerror=window.xss=1>',garrison_total:5000,can_attack:true,can_garrison:false},{id:72,shrine_tier:'B',coord_x:150,coord_y:120,alliance_name:'Fixture Alliance',garrison_total:2000,can_attack:false,can_garrison:true}],events:[{id:8,phase:2,state:'active',starts_at:start,ends_at:end,leaderboard:[{tag:'TST',name:'Fixture Alliance',points:125}],my_points:25},{id:7,phase:4,state:'ended',starts_at:start,ends_at:end,leaderboard:[],my_points:75,claimed:false,report:{players:[{username:'<script>window.xss=1</script>',points:75}]}}]}};
const worlds={active_world_id:1,worlds:[{id:1,name:'Fixture Grünland',status:'running',map_size:512,owned:true,selected:true,city_name:'My Kingdom',castle_level:10,speed_factor:1,gather_factor:1},{id:2,name:'Forschung <img src=x onerror=window.xss=1>',status:'open',map_size:1024,owned:false,selected:false,can_join:true,speed_factor:2,gather_factor:1.5},{id:3,name:'Frozen Highlands',status:'closed',map_size:512,owned:true,selected:false,can_select:false,can_join:false,city_name:'Another Kingdom',castle_level:4,speed_factor:1,gather_factor:1}]};
const raid={id:9,name:'Fixture Boss',phase:'boss',expires_at:end,completed_at:null,permissions:{invite:false,accept:false,decline:false,cancel:false,supply:false,defenses:false,pass:false,boss:true},host_alliance:{id:1,tag:'ONE',name:'First alliance'},guest_alliance:{id:2,tag:'TWO',name:'Second alliance'},missions:[],participants:[],log:[],supplies:{current:100,target:100},defenses:{current:100,target:100},pass:{current:100,target:100},boss:{name:'The Golem',hp:50000,max_hp:100000},encounter:{image:'golem.png',difficulty_name:'Veteran',strategy:'Koordiniert eure Armeen.'},my_contribution:100,can_claim:false,reward_claimed:false};
const expedition={expeditions:[raid],troops:[{code:50100101,name:'Infanterie',tier:1,type:1,count:500}],alliance:{id:1},can_create:true,available_alliances:[],catalog:{golem:{name:'The Golem',chapter:2,castle:5}},difficulties:{normal:{name:'Normal',castle:1,factor:1}},chapter:3,rules:{march_seconds:30,return_seconds:30,reward:{food:100,gold:1000},min_contribution:10,loss_rule:'Keine permanenten Verluste.',strategy:'Zusammenarbeiten.'}};
progression.mastery={world_id:1,lord:{level:20,max_level:60,xp:25000,xp_into_level:50,xp_next:500},earned:20,spent:1,available:19,revision:0,ranks:{attack_0:1},branches:JSON.parse(fs.readFileSync(root+'/data/lord_talents.json','utf8')).branches,respec_available_at:0,blocked_reason:null};
const script=`<script>window.CONQUER_BASE='';window.CONQUER_I18N=${JSON.stringify({locale:'de',catalogs:localeCatalogs}).replaceAll('<','\\u003c')};</script><script src="/assets/js/localization.js"></script><script src="/assets/js/lord-talents.js"></script><script src="/assets/js/progression-panel.js"></script><script src="/assets/js/world-panel.js"></script><script src="/assets/js/mvp-panels.js"></script><script>
window.fixture=${JSON.stringify(progression).replaceAll('<','\\u003c')};window.worldFixture=${JSON.stringify(worlds).replaceAll('<','\\u003c')};window.expeditionFixture=${JSON.stringify(expedition).replaceAll('<','\\u003c')};window.calls=[];window.messages=[];window.shrineCalls=[];window.xss=0;window.failNext=false;window.holdNext=false;window.releaseRequest=null;
document.querySelector('#content').id='playfield-content';document.querySelector('#panel-content').id='content';
window.context={base:'',esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt:n=>Number(n).toLocaleString('de-DE'),date:v=>Date.parse(v.replace(' ','T')+'Z'),duration:s=>s+' Sek.',countdown:()=>'<span>5 Min.</span>',getState:()=>({city:{castle_level:10,food:50000},player:{name:'Fixture ruler'},troops:{50100101:500},troop_defs:[{code:50100101,name:'Infanterie',tier:1,type:1}]}),getKingdom:()=>({}),getExpeditions:()=>expeditionFixture,getMarket:()=>null,getErrors:()=>({}),toast:m=>messages.push(m),refresh:async()=>{},navigate:tab=>window.showPanel(tab),costHtml:()=>'',openShrine:(id,garrison)=>shrineCalls.push({id,garrison}),api:async(route,payload)=>{if(payload){calls.push({route,payload});if(holdNext){holdNext=false;await new Promise(resolve=>releaseRequest=resolve);}if(failNext||route==='worlds/action'){failNext=false;throw new Error('Fixture request failed');}if(payload.action==='mastery.apply'){fixture.mastery.ranks={...payload.ranks};fixture.mastery.revision++;fixture.mastery.spent=Object.values(payload.ranks).reduce((a,b)=>a+b,0);return {message:'Gespeichert.',mastery:structuredClone(fixture.mastery)};}return {message:'Gespeichert.'};}return structuredClone(route==='worlds/state'?worldFixture:fixture);},action:async(route,payload)=>{calls.push({route,payload});return {};},openDialog:html=>{const d=document.querySelector('#game-dialog');d.querySelector('.popup-heading')?.remove();const body=document.querySelector('#dialog-content');body.innerHTML=html;const title=body.querySelector('h2');if(title){const header=document.createElement('header');header.className='popup-heading';header.append(title);d.insertBefore(header,body);d.classList.add('has-popup-heading');}if(!d.open)d.showModal();}};
window.progression=ConquerProgression(context);window.worldPanel=ConquerWorldPanel(context);window.panels=ConquerPanels(context);
window.showPanel=tab=>{document.querySelector('#game-dialog').close();const d=document.querySelector('#panel-dialog');d.dataset.panel=tab;document.querySelector('#page-title').textContent=tab;document.querySelector('#content').innerHTML='';if(!d.open)d.showModal();if(!progression.render(tab)&&!worldPanel.render(tab))panels.render(tab);};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='close-dialog'){document.querySelector('#game-dialog').close();return;}if(progression.onClick(b.dataset.action,b)||worldPanel.onClick(b.dataset.action,b)||panels.onClick(b.dataset.action,b))return;});
document.addEventListener('submit',async e=>{const f=e.target.closest('form[data-form]');if(!f)return;e.preventDefault();if(!f.reportValidity())return;if(await progression.onSubmit(f))return;await panels.onSubmit(f);});showPanel('events');</script>`;
template=template.replace('</body>',script+'</body>');
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://fixture').pathname;if(pathname.startsWith('/assets/')&&!pathname.includes('..')){const file=root+pathname;if(fs.existsSync(file)&&fs.statSync(file).isFile()){res.setHeader('Content-Type',({'.js':'application/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'})[path.extname(file)]||'application/octet-stream');res.end(fs.readFileSync(file));return;}}res.setHeader('Content-Type','text/html; charset=utf-8');res.end(template);});
(async()=>{await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForSelector('.progression-content');
 // A slow read must survive repeated renders from polling, resize and reopening.
 await page.evaluate(()=>{
   const original=context.api;window.originalTalentAPI=original;window.talentReads=0;
   context.api=async(route,payload)=>{if(route==='progression/state'&&!payload){talentReads++;await new Promise(resolve=>window.releaseTalentRead=resolve);}return original(route,payload);};
   window.progression=ConquerProgression(context);showPanel('mastery');
   progression.render('mastery');showPanel('mastery');progression.render('mastery');
 });
 assert.equal(await page.evaluate(()=>talentReads),1,'Repeated renders share the in-flight talent request');
 await page.evaluate(()=>releaseTalentRead());await page.waitForSelector('.lord-talents');
 await page.evaluate(()=>{context.api=originalTalentAPI;delete window.originalTalentAPI;window.progression=ConquerProgression(context);});
 for(const[width,height]of[[1280,800],[390,844],[844,390],[568,320]])for(const tab of ['events','mastery','account','worlds','expeditions']){
    await page.setViewportSize({width,height});await page.evaluate(tab=>showPanel(tab),tab);await page.waitForFunction(tab=>Boolean(document.querySelector(tab==='worlds'?'.world-selector':tab==='expeditions'?'.hero-expedition':tab==='mastery'?'.lord-talents':'.progression-content')),tab);
    const metrics=await page.evaluate(()=>{const d=document.querySelector('#panel-dialog'),r=d.getBoundingClientRect(),h=document.querySelector('#content');return {outside:r.left<0||r.top<0||r.right>innerWidth+1||r.bottom>innerHeight+1,horizontal:h.scrollWidth>h.clientWidth+2,bodyOverflow:document.documentElement.scrollWidth>innerWidth+1};});
    if(tab==='account'){const visible=await page.evaluate(()=>{const c=document.querySelector('.progression-content').getBoundingClientRect(),h=document.querySelector('#content').getBoundingClientRect();return Math.min(c.bottom,h.bottom)-Math.max(c.top,h.top);});assert.ok(visible>=120,`${width}×${height} language settings must not reduce account content to an unusable strip`);}
    await page.screenshot({path:out+'/'+width+'-'+tab+'.png'});assert.deepEqual(metrics,{outside:false,horizontal:false,bodyOverflow:false},JSON.stringify({width,height,tab,metrics}));
    assert.equal(await page.evaluate(()=>window.xss),0);
    const controls=page.locator('#content .button:not(:disabled),#content .talent-button:not(:disabled):visible');for(let i=0;i<await controls.count();i++){await controls.nth(i).scrollIntoViewIfNeeded();const position=await controls.nth(i).evaluate(e=>{const r=e.getBoundingClientRect(),d=document.querySelector('#panel-dialog').getBoundingClientRect();return {outside:r.left<d.left-1||r.right>d.right+1||r.top<d.top-1||r.bottom>d.bottom+1};});assert.equal(position.outside,false,`${width}×${height} ${tab} button ${i} is clipped`);}if(tab==='account'||tab==='worlds')await page.screenshot({path:out+'/'+width+'-'+tab+'-bottom.png'});
 }
 await page.setViewportSize({width:320,height:568});await page.evaluate(()=>showPanel('mastery'));await page.waitForSelector('.lord-talents');
 assert.equal(await page.locator('.talent-tree-scroll').evaluate(e=>e.scrollWidth>e.clientWidth),false,'narrow phones keep both talent lanes within the window');
 await page.screenshot({path:out+'/320-mastery.png'});
 // Talent controls stay on the board; detail sheets must preserve the draft and scroll position.
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>showPanel('mastery'));await page.waitForSelector('.lord-talents');
 const talentSave=page.locator('[data-action="talent-apply"]'),treeScroll=page.locator('.talent-tree-scroll');
 const saveTop=(await talentSave.boundingBox()).y;
 await page.locator('[data-action="talent-plus"][data-id="attack_0"]').click();
 assert.equal(await page.locator('.talent-points strong').textContent(),'18');
 await page.locator('[data-action="talent-branch"][data-id="gather"]').click();await page.locator('[data-action="talent-branch"][data-id="attack"]').click();
 assert.equal(await page.locator('.talent-points strong').textContent(),'18','switching branches preserves draft');
 await treeScroll.evaluate(e=>e.scrollTop=e.scrollHeight);const treePosition=await treeScroll.evaluate(e=>e.scrollTop);
 assert.equal((await talentSave.boundingBox()).y,saveTop,'save stays visible while exploring the tree');
 await page.locator('[data-action="talent-select"][data-id="attack_8"]').click();await page.waitForSelector('.talent-sheet');
 assert.equal(await page.locator('.talent-workspace').getAttribute('inert'),'');
 assert.equal(await page.locator('.talent-sheet [data-action="talent-plus"]').isDisabled(),true,'locked talent cannot receive points');
 assert.match(await page.locator('.talent-feedback').textContent(),/(?:Lord|Hunter)-Level 40/);
 await page.keyboard.press('Escape');assert.equal(await page.locator('.talent-sheet').count(),0);assert.equal(await treeScroll.evaluate(e=>e.scrollTop),treePosition,'closing details restores tree position');
 assert.equal(await page.locator('#panel-dialog').evaluate(e=>e.open),true,'Escape closes details, not the talent window');
 await page.locator('[data-action="talent-bonuses"]').click();assert.match(await page.locator('.talent-bonus-list').textContent(),/\+2 %/);await page.locator('[data-action="talent-close-sheet"]').click();
 await page.locator('[data-action="talent-options"]').click();await page.locator('[data-action="talent-discard"]').click();assert.equal(await page.locator('.talent-points strong').textContent(),'19');assert.equal(await talentSave.isDisabled(),true);
 await page.locator('[data-action="talent-options"]').click();await page.locator('[data-action="talent-reset"]').click();assert.equal(await page.locator('.talent-points strong').textContent(),'20');
 await page.locator('[data-action="talent-options"]').click();await page.locator('[data-action="talent-discard"]').click();
 await page.setViewportSize({width:1280,height:800});await page.evaluate(()=>showPanel('account'));await page.waitForSelector('[data-form="progress-password"]');await page.locator('[data-form="progress-password"] [name="current_password"]').fill('FixtureCurrent');await page.locator('[data-form="progress-password"] [name="new_password"]').fill('FixtureNewPassword');await page.evaluate(()=>progression.render('account'));assert.equal(await page.locator('[data-form="progress-password"] [name="new_password"]').inputValue(),'FixtureNewPassword','poll preserves account form');
 await page.evaluate(()=>failNext=true);await page.locator('[data-form="progress-password"] button').click();await page.waitForFunction(()=>messages.includes('Fixture request failed'));assert.equal(await page.locator('[data-form="progress-password"] button').isDisabled(),false);assert.equal(await page.locator('[data-form="progress-password"] [name="new_password"]').inputValue(),'FixtureNewPassword','failed password action preserves form');
 await page.evaluate(()=>{messages=[];showPanel('mastery')});await page.waitForSelector('.lord-talents');await page.locator('[data-action="talent-plus"][data-id="attack_0"]').click();await page.evaluate(()=>failNext=true);await page.locator('[data-action="talent-apply"]').click();await page.waitForFunction(()=>messages.includes('Fixture request failed'));assert.equal(await page.locator('[data-action="talent-plus"][data-id="attack_0"]').isDisabled(),false);await page.locator('[data-action="talent-apply"]').click();await page.waitForFunction(()=>calls.filter(c=>c.payload.action==='mastery.apply').length===2);const mastery=await page.evaluate(()=>calls.filter(c=>c.payload.action==='mastery.apply'));assert.equal(mastery[0].payload.operation_key,mastery[1].payload.operation_key);
 await page.evaluate(()=>showPanel('events'));await page.locator('[data-action="progress-event-tab"][data-id="conquest:8"]').click();await page.waitForSelector('[data-action="progress-shrine"]');await page.locator('[data-action="progress-shrine"]').click();await page.locator('[data-action="progress-shrine-garrison"]').click();assert.deepEqual(await page.evaluate(()=>shrineCalls),[{id:71,garrison:false},{id:72,garrison:true}]);
 await page.locator('[data-action="progress-event-tab"][data-id="conquest:7"]').click();await page.locator('[data-action="progress-event-claim"]').click();await page.waitForFunction(()=>calls.some(c=>c.payload.action==='event.claim'&&c.payload.id===7));await page.waitForFunction(()=>!document.querySelector('[data-action="progress-event-tab"]').disabled);
 await page.locator('[data-action="progress-event-tab"][data-id="invasion:1"]').click();await page.locator('[data-action="progress-invasion-supply"]').click();await page.locator('[data-form="progress-supply"] [name="amount"]').fill('200');await page.locator('[data-form="progress-supply"] button').click();await page.waitForFunction(()=>calls.some(c=>c.payload.action==='invasion.supply'));assert.equal((await page.evaluate(()=>calls.find(c=>c.payload.action==='invasion.supply'))).payload.amount,200);
 await page.evaluate(()=>showPanel('worlds'));await page.waitForSelector('.world-selector');await page.locator('[data-world="2"]').click();await page.waitForFunction(()=>calls.some(c=>c.route==='worlds/action'));assert.equal(await page.locator('[data-world="2"]').isDisabled(),false);assert.equal(await page.locator('[data-world="3"]').isDisabled(),true);await page.locator('[data-world="2"]').click();await page.waitForFunction(()=>calls.filter(c=>c.route==='worlds/action').length===2);const world=await page.evaluate(()=>calls.filter(c=>c.route==='worlds/action'));assert.equal(world[0].payload.request_id,world[1].payload.request_id);assert.equal(world[0].payload.world_id,2);assert.equal(world[0].payload.expected_world_id,1);assert.equal(world[0].payload.action,'join');
 await page.evaluate(()=>showPanel('expeditions'));await page.locator('[data-action="raid-open"]').click();await page.waitForSelector('.boss-panel');assert.equal(await page.locator('.boss-panel [data-action="raid-dispatch"]').isDisabled(),false);await page.locator('.boss-panel [data-action="raid-dispatch"]').click();await page.waitForSelector('[data-form="raid-dispatch"]');assert.equal(await page.locator('[data-form="raid-dispatch"]').getAttribute('data-objective'),'boss');
 await page.screenshot({path:out+'/1280-boss-command.png'});await page.locator('[data-form="raid-dispatch"] input[name="troop_50100101"]').fill('25');await page.locator('[data-form="raid-dispatch"] button').click();await page.waitForFunction(()=>calls.some(c=>c.route==='expeditions/action'&&c.payload.action==='dispatch'));const boss=await page.evaluate(()=>calls.find(c=>c.route==='expeditions/action'&&c.payload.action==='dispatch').payload);assert.equal(boss.objective,'boss');assert.equal(boss.expedition_id,9);assert.equal(boss.troops['50100101'],25);await page.locator('#game-dialog .dialog-close').evaluate(e=>e.closest('dialog').close());
 await page.evaluate(()=>{showPanel('mastery');});await page.waitForSelector('.lord-talents');await page.locator('[data-action="talent-plus"][data-id="attack_0"]').click();await page.evaluate(()=>holdNext=true);await page.locator('[data-action="talent-apply"]').click();await page.waitForFunction(()=>typeof releaseRequest==='function');await page.evaluate(()=>showPanel('worlds'));await page.waitForSelector('.world-selector');await page.evaluate(()=>releaseRequest());await page.waitForTimeout(100);assert.equal(await page.locator('.world-selector').count(),1,'late progression action must not overwrite a different active panel');
 assert.deepEqual(errors,[]);console.log('PASS 20 real-shell layouts + 320px talent view, direct ranks, fixed save bar, detail focus/scroll, draft/reset/bonuses, form contracts, idempotent retries and late-response navigation safety. '+out);
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
