'use strict';
const assert=require('node:assert/strict'),path=require('node:path'),net=require('node:net'),{spawn}=require('node:child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
 const port=await new Promise(resolve=>{const server=net.createServer();server.listen(0,'127.0.0.1',()=>{const port=server.address().port;server.close(()=>resolve(port));});});
 const fixture=spawn(process.env.PHP_BINARY||'C:/xampp/php/php.exe',[root+'/tools/preview-feature-fixture.php','--port='+port,'--queue-speedups'],{cwd:root,stdio:['pipe','pipe','pipe'],windowsHide:true});
 let browser,log='';
 try{
  await new Promise((resolve,reject)=>{fixture.stdout.on('data',data=>{log+=data;if(log.includes('Synthetic preview ready'))resolve();});fixture.stderr.on('data',data=>log+=data);fixture.on('error',reject);fixture.on('exit',()=>reject(Error(log)));});
  browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(15000);
  await page.goto('http://127.0.0.1:'+port);await page.locator('[data-mode=login]').click();
  await page.locator('[name=username]').fill('PreviewPlayer');await page.locator('[name=password]').fill('PreviewFixture!2026');
  await Promise.all([page.waitForURL('**/city'),page.locator('#auth-submit').click()]);
  await page.waitForFunction(()=>document.querySelector('#player-hud-name')?.textContent.includes('PreviewPlayer'));
  const api=p=>page.evaluate(async p=>(await(await fetch('/api/'+p)).json()).data,p),state=await api('kingdom/state');
  const item=type=>state.inventory.find(i=>i.category==='speedup'&&i.subcategory===type&&i.duration_seconds===60);
  await page.locator('#navigation [data-id=inventory]').click();await page.locator('[data-action=inventory-category][data-id=speedup]').click();
  const openItem=async type=>{const card=page.locator(`[data-action=inventory-item][data-id="${item(type).item_code}"]`);await card.click();assert.equal(await page.locator('#game-dialog').evaluate(d=>d.open),false,'Item details stay in the inventory');};
  const choose=async queue=>{if(queue)await page.locator('#inventory-queue').selectOption(queue);await page.locator('#inventory-details button[type=submit]').click();};
  const close=()=>page.locator('#game-dialog>.dialog-close').click();
  await openItem('research');
  await choose();
  assert.equal(await page.locator('.queue-speedup-picker').getAttribute('data-type'),'research');
  assert.equal(await page.locator('.queue-speedup-option[aria-pressed=true]').getAttribute('data-id'),String(item('research').item_code));
  assert.notEqual(await page.evaluate(()=>document.activeElement.id),'queue-speedup-quantity','Opening the picker does not focus the phone keyboard');
  const scroll=await page.locator('.inventory-scroll-board').evaluate(e=>e.scrollTop);await close();
  assert.equal(await page.locator('.inventory-scroll-board').evaluate(e=>e.scrollTop),scroll);
  await openItem('generic');assert.equal(await page.locator('#inventory-queue option').count(),state.queues.length);
  await choose('research:'+state.queues.find(q=>q.type==='research').id);
  assert.equal(await page.locator('.queue-speedup-picker').getAttribute('data-type'),'research');
  assert.equal(await page.locator('.queue-speedup-option[aria-pressed=true]').getAttribute('data-id'),String(item('generic').item_code));await close();
  await openItem('building');const target=state.queues.filter(q=>q.type==='building')[1];assert(target);
  await choose('building:'+target.id);await page.locator('[data-action=queue-speedup-one]').click();
  const response=page.waitForResponse(r=>r.url().endsWith('/api/kingdom/action')&&r.request().method()==='POST');await page.locator('[data-action=queue-speedup-use]').click();
  const result=await response;assert.equal(result.status(),200,await result.text());assert.equal(result.request().postDataJSON().queue_id,Number(target.id));
  await page.waitForFunction(()=>document.querySelector('.queue-speedup-feedback')?.textContent.includes('1 verwendet'));
  assert.equal((await api('kingdom/state')).inventory.find(i=>i.item_code===item('building').item_code).quantity,item('building').quantity-1);await close();
  await openItem('research');
  const bulkResponse=page.waitForResponse(r=>r.url().endsWith('/api/kingdom/action')&&r.request().postDataJSON()?.use_all===true);
  await page.locator('#inventory-details [data-action=inventory-use-all]').click();
  const bulk=(await(await bulkResponse).json()).data;
  assert.equal(bulk.result.quantity,item('research').quantity,'Use all consumes the selected speedup stock when the queue has enough time');
  assert.equal(bulk.result.queue_id,Number(state.queues.find(q=>q.type==='research').id));
  await page.waitForFunction(code=>!document.querySelector(`.inventory-page-grid [data-action=inventory-item][data-id="${code}"]`),item('research').item_code);
  assert.equal(await page.locator('#game-dialog').evaluate(d=>d.open),false,'Use all stays in the inventory');
  await openItem('healing');assert.match(await page.locator('#inventory-details').innerText(),/Kein passender Auftrag/);assert.equal(await page.locator('#inventory-details button[type=submit]').isDisabled(),true);
  assert.deepEqual(errors,[]);console.log('PASS inventory speedups: direct single target, generic and same-type target selection, selected item preserved, correct queue/stock consumption, no active job, scroll/focus.');
 }finally{if(browser)await browser.close();if(fixture.exitCode===null){fixture.stdin.end('\n');await new Promise(resolve=>fixture.once('exit',resolve));}}
})().catch(e=>{console.error(e);process.exitCode=1;});
