const fs=require('fs'),path=require('path'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE);
(async()=>{const browser=await chromium.launch({headless:true,channel:'chrome',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));try{
await page.goto('http://127.0.0.1:18949');await page.locator('[name="identifier"]').fill('PreviewPlayer');await page.locator('[name="password"]').fill('PreviewFixture!2026');await Promise.all([page.waitForURL('**/city',{waitUntil:'domcontentloaded',timeout:120000}),page.locator('.play-submit').click()]);await page.waitForFunction(()=>document.querySelector('#player-hud-name')?.textContent.includes('PreviewPlayer'));
const scene=page.locator('#navigation .hud-scene-switch');await scene.waitFor();if(await scene.getAttribute('data-id')==='world')await scene.click();
const out=path.resolve('artifacts/regional-bosses-restored');fs.mkdirSync(out,{recursive:true});
for(const [width,height] of (process.env.BOSS_VIEWPORTS?JSON.parse(process.env.BOSS_VIEWPORTS):[[1280,800],[390,844],[320,568],[568,320]])){await page.setViewportSize({width,height});for(const [zone,name,art] of [['Wald','Grumwald','grumwald'],['Eis','Frostgrimm','frostgrimm'],['Sand','Sandmaul','sandmaul'],['Lava','Glutramm','glutramm']]){
await page.getByRole('button',{name:'Koordinaten und Weltübersicht öffnen',exact:true}).click();await page.locator('#atlas-navigation-panel').getByRole('button',{name:zone,exact:true}).click();const target=page.locator(`.atlas-marker--monsters[data-boss="${art}"]`).first();await target.waitFor({state:'attached'});await page.evaluate(({x,y})=>ConquerWorld.focus(+x,+y),await target.evaluate(el=>({x:el.dataset.x,y:el.dataset.y})));await target.waitFor({state:'visible'});assert((await target.getAttribute('aria-label')).includes(name));assert.equal(await target.getAttribute('data-footprint'),'2');await target.locator(`img[src$="/monsters/storybook-v2/${art}.png"]`).evaluate(i=>i.decode());await page.screenshot({path:path.join(out,`${art}-${width}-map.png`)});
await target.click();const dialog=page.locator('#game-dialog');await dialog.waitFor({state:'visible'});assert((await dialog.textContent()).includes(name));assert(await dialog.locator('.is-monster-rally').count());const targetTab=dialog.locator('[data-action="march-view"][data-id="target"]');if(await targetTab.isVisible())await targetTab.click();const portrait=dialog.locator(`img[src$="/monsters/storybook-v2/${art}.png"]`).first();assert(await portrait.isVisible());await portrait.evaluate(i=>i.decode());const r=await dialog.boundingBox();assert(r.x>=-1&&r.y>=-1&&r.x+r.width<=width+1&&r.y+r.height<=height+1);await page.screenshot({path:path.join(out,`${art}-${width}-rally.png`)});await dialog.getByRole('button',{name:'Fenster schließen',exact:true}).click();console.log(`PASS ${width}x${height} ${name}`);
}}assert.deepEqual(errors,[]);console.log('ALL RESTORED BOSS UI CHECKS PASSED');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
