const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..');
function fixture(){
    window.currentWorld=1;window.calls=[];window.toasts=[];window.opened=[];window.failSettings=false;window.rejectReport=false;window.deferNext=false;
    const p=id=>({player_id:id,username:'Player '+id}),state={friends:[p(2)],requests:{incoming:[p(3)],outgoing:[p(4)]},blocks:[],conversations:[{...p(2),last_message:'Hello <img src=x>',unread:1,last_at:'2026-09-30 10:00:00'}],preferences:{private_messages:'everyone',channels:{world:'all',alliance:'all',private:'all'}}},receipts={};
    window.hub=ConquerSocialHub({esc:value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt:String,getState:()=>({city:{world_id:currentWorld}}),toast:s=>toasts.push(s),navigate:s=>opened.push(s),openPrivate:id=>opened.push(id),openChat:channel=>opened.push(channel),openMailbox:()=>opened.push('mail'),openPublicProfile:id=>opened.push(id),chatChanged:()=>{},openDialog:html=>{const d=document.querySelector('#game-dialog');d.innerHTML=html;d.showModal();},api:async(url,payload)=>{
        if(!payload){const q=new URLSearchParams(url.split('?')[1]),w=Number(q.get('world_id'));let result=url.startsWith('community/news')?{posts:[],discord:null}:{...state,world_id:w,player_id:1,search:q.get('query')?[p(5)]:[]};if(w===2&&url.startsWith('community/social'))result={...result,friends:[],requests:{incoming:[],outgoing:[]},conversations:[]};result=structuredClone(result);if(deferNext&&url.startsWith('community/social')){window.deferNext=false;await new Promise(resolve=>window.resolveDeferred=resolve);}return result;}
        calls.push(structuredClone(payload));if(receipts[payload.request_id])return receipts[payload.request_id];
        if(payload.action==='report.submit'&&rejectReport){window.rejectReport=false;throw new Error('Report connection failed');}
        if(payload.action==='friend.accept'){state.requests.incoming=[];state.friends.push(p(payload.player_id));}
        if(payload.action==='friend.request')state.requests.outgoing.push(p(payload.player_id));
        if(payload.action==='friend.decline')state.requests.outgoing=state.requests.outgoing.filter(p=>p.player_id!==payload.player_id);
        if(payload.action==='preferences.save')state.preferences={private_messages:payload.private_messages,channels:payload.channels};
        receipts[payload.request_id]={message:'Saved.',result:{}};
        if(payload.action==='preferences.save'&&failSettings){window.failSettings=false;throw new Error('Lost save response');}
        return receipts[payload.request_id];
    }});
    document.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(b)hub.onClick(b.dataset.action,b);});
    document.addEventListener('submit',event=>{event.preventDefault();hub.onSubmit(event.target);});
    hub.render('community');
}
(async()=>{
    const temp=fs.mkdtempSync(path.join(os.tmpdir(),'uok-social-hub-')),file=path.join(temp,'fixture.html');
    fs.writeFileSync(file,`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="${pathToFileURL(path.join(root,'assets/css/social-hub.css'))}"><link rel="stylesheet" href="${pathToFileURL(path.join(root,'assets/css/village-theme.css'))}"><style>body{margin:0;background:var(--ui-paper)}#content{padding:10px;max-width:900px;margin:auto;box-sizing:border-box}input,select,textarea{box-sizing:border-box;font-size:16px}dialog{max-width:calc(100vw - 40px)}dialog label{display:grid}dialog button{min-height:44px}</style><main id="content"></main><dialog id="game-dialog"></dialog><script>const catalog=${fs.readFileSync(path.join(root,'data/i18n/en.json'),'utf8')};window.ConquerLocale={locale:'en',t:(key,args={})=>(catalog[key]||key).replace(/\{(\w+)\}/g,(_,k)=>args[k]??'')};</script><script src="${pathToFileURL(path.join(root,'assets/js/social-hub.js'))}"></script><script>(${fixture.toString()})();</script>`);
    const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});
    try{
        const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(pathToFileURL(file).href);await page.waitForSelector('.social-summary');
        await page.locator('.social-tabs [data-id="friends"]').click();await page.locator('[name="query"]').fill('Unsubmitted search');const original=await page.locator('[name="query"]').elementHandle();await page.evaluate(()=>{for(let i=0;i<5;i++)hub.render('community');});assert.equal(await page.locator('[name="query"]').inputValue(),'Unsubmitted search');assert.equal(await original.evaluate(e=>e.isConnected),true,'game refresh keeps the focused form mounted');
        await page.locator('.social-tabs [data-id="settings"]').click();await page.locator('[name="private_messages"]').selectOption('friends');await page.locator('[name="world"]').selectOption('mentions');await page.locator('[data-action="social-refresh"]').click();await page.waitForTimeout(50);assert.equal(await page.locator('[name="private_messages"]').inputValue(),'friends','explicit refresh preserves unsaved preferences');
        await page.locator('.social-tabs [data-id="friends"]').click();assert.equal(await page.locator('[name="query"]').inputValue(),'Unsubmitted search','tab switch preserves search draft');await page.locator('.social-tabs [data-id="settings"]').click();assert.equal(await page.locator('[name="world"]').inputValue(),'mentions');
        await page.evaluate(()=>window.failSettings=true);await page.locator('[data-form="social-settings"] button').click();await page.waitForFunction(()=>toasts.includes('Lost save response'));assert.equal(await page.locator('[name="private_messages"]').isDisabled(),false);assert.equal(await page.locator('[name="private_messages"]').inputValue(),'friends');
        await page.locator('[data-form="social-settings"] button').click();await page.waitForFunction(()=>toasts.includes('Saved.'));const saves=await page.evaluate(()=>calls.filter(c=>c.action==='preferences.save'));assert.equal(saves[0].request_id,saves[1].request_id,'settings retry keeps receipt');
        await page.locator('.social-tabs [data-id="friends"]').click();await page.locator('[data-action="social-decline"][data-id="4"]').click();await page.waitForFunction(()=>!document.querySelector('[data-action="social-decline"][data-id="4"]'));
        await page.locator('[data-action="social-accept"][data-id="3"]').click();await page.waitForSelector('[data-action="social-remove"][data-id="3"]');
        await page.locator('[name="query"]').fill('Player 5');await page.locator('[data-form="social-search"] button').click();await page.waitForSelector('[data-action="social-request"][data-id="5"]');await page.locator('[data-action="social-request"][data-id="5"]').click();await page.waitForSelector('[data-action="social-decline"][data-id="5"]');
        const row=page.locator('.social-contact').filter({has:page.locator('[data-action="social-profile"][data-id="2"]')});await row.locator('summary').click();await row.locator('[data-action="social-report"]').click();await page.locator('[name="details"]').fill('Please review these messages.');await page.evaluate(()=>window.rejectReport=true);await page.locator('[data-form="social-report"] button').click();await page.waitForFunction(()=>toasts.includes('Report connection failed'));assert.equal(await page.locator('#game-dialog').evaluate(e=>e.open),true,'failed report stays open');assert.equal(await page.locator('[name="details"]').inputValue(),'Please review these messages.');await page.locator('[data-form="social-report"] button').click();await page.waitForFunction(()=>!document.querySelector('#game-dialog').open);
        const reports=await page.evaluate(()=>calls.filter(c=>c.action==='report.submit'));assert.equal(reports[0].request_id,reports[1].request_id);assert.equal(reports[1].details,'Please review these messages.');
        await page.evaluate(()=>{window.deferNext=true;hub.onClick('social-refresh',{dataset:{}});});await page.waitForFunction(()=>typeof resolveDeferred==='function');await page.evaluate(()=>{window.currentWorld=2;hub.render('community');resolveDeferred();});await page.waitForFunction(()=>!document.querySelector('[data-action="social-profile"][data-id="2"]'));assert.equal(await page.locator('[name="query"]').inputValue(),'','search drafts are scoped by world');
        const selectedStyles=await page.evaluate(()=>{const panel=document.createElement('dialog');panel.id='panel-dialog';const content=document.querySelector('#content');content.before(panel);panel.append(content);document.body.classList.add('mobile-game');panel.showModal();const selected=getComputedStyle(document.querySelector('.social-tabs [aria-pressed="true"]')),other=getComputedStyle(document.querySelector('.social-tabs [aria-pressed="false"]')),probe=document.createElement('span');probe.style.background='var(--ui-inset)';probe.style.border='1px solid var(--ui-gold)';panel.append(probe);const expected=getComputedStyle(probe);return {selected:selected.backgroundColor,other:other.backgroundColor,border:selected.borderColor,shadow:selected.boxShadow,expected:expected.backgroundColor,expectedBorder:expected.borderColor};});
        assert.equal(selectedStyles.selected,selectedStyles.expected,'selected Community tab uses the shared inset despite global button overrides');assert.equal(selectedStyles.border,selectedStyles.expectedBorder);assert.notEqual(selectedStyles.selected,selectedStyles.other);assert.match(selectedStyles.shadow,/inset/);
        assert.deepEqual(errors,[]);console.log('PASS community hub polling preserves drafts/focus, explicit refresh/tab drafts, settings retry, friend accept/cancel/search/request, failed report retention, stale-world isolation and selected-tab theme styles.');
    }finally{await browser.close();fs.rmSync(temp,{recursive:true,force:true});}
})().catch(error=>{console.error(error);process.exitCode=1;});
