<?php
declare(strict_types=1);
/** Disposable-schema integration tests: real reservations, combat, rewards, reign and retries. */
if(PHP_SAPI!=='cli')exit(1);
define('ROOT_DIR',dirname(__DIR__));date_default_timezone_set('UTC');require ROOT_DIR.'/src/Autoloader.php';(new \Conquer\Autoloader(ROOT_DIR.'/src'))->register();
require __DIR__.'/Support/FeatureDatabase.php';
use Conquer\Db\Connection;
use Conquer\Game\World\{WorldContext,WorldMapProfile};
use Conquer\Game\Territory\{TerritoryService as Territory,TerritoryRules,TerritoryEconomy,TerritoryGarrison,TerritoryCrown};
use Conquer\Game\City\TroopData;

if(($argv[1]??'')==='--worker'){
 $dir=realpath($argv[2]??'');if(!$dir||dirname($dir)!==realpath(sys_get_temp_dir())||!preg_match('/^conquer_feature_test_[a-f0-9]{12}$/D',basename($dir)))exit(2);
 Connection::init($dir);WorldContext::bind(2);try{$body=json_decode($argv[4],true,24,JSON_THROW_ON_ERROR);$result=Territory::action((int)$argv[3],$body,2);echo json_encode(['ok'=>true,'result'=>$result]);}catch(DomainException|RuntimeException $e){echo json_encode(['ok'=>false,'error'=>$e->getMessage()]);}exit;
}
function tc(bool $ok,string $name):void {if(!$ok)throw new RuntimeException($name);echo 'PASS '.$name."\n";}
function td(callable $fn,string $name):void {try{$fn();}catch(DomainException|RuntimeException){tc(true,$name);return;}throw new RuntimeException('Expected rejection: '.$name);}
function cmdt(int $pid,string $action,array $body=[]):array{return Territory::action($pid,['action'=>$action,'world_id'=>2,'expected_world_id'=>2,'request_id'=>bin2hex(random_bytes(16))]+$body,2);}
function finishRally(int $id,int $ago=600):void{ $db=Connection::getInstance();$db->execute('UPDATE rallies SET launch_at=? WHERE id=?',[gmdate('Y-m-d H:i:s',time()-$ago),$id]);Territory::tick(2,time(),1000);}
function cityNear(int $pid,string $target):void{$t=Territory::target(2,$target);Connection::getInstance()->execute('UPDATE cities SET coord_x=?,coord_y=? WHERE id=?',[$t['x']+10+$pid*5,$t['y']+10,$pid]);}
function troops(int $pid,int $count=100000):void{global $code;Connection::getInstance()->execute('INSERT INTO city_troops(city_id,troop_code,count)VALUES(?,?,?) ON DUPLICATE KEY UPDATE count=VALUES(count)',[$pid,$code,$count]);}
$fixture=new \ConquerTests\FeatureDatabase();
try{
 $db=Connection::getInstance();$db->execute("INSERT INTO worlds(id,name,slug,status,map_size)VALUES(2,'Territory fixture','territory-lifecycle','running',768)");WorldMapProfile::configureEmptyWorld(2);WorldContext::bind(2);Territory::ensureWorld(2);
 $code=(int)array_key_first(TroopData::all());
 for($i=1;$i<=8;$i++){$db->execute('INSERT INTO players(id,username,email,password_hash)VALUES(?,?,?,?)',[$i,'TerritoryFixture'.$i,'territory'.$i.'@invalid.test','unused']);$db->execute("INSERT INTO cities(id,player_id,world_id,name,coord_x,coord_y,food,lumber,stone,gold,last_resource_update)VALUES(?,?,2,'Fixture',?,500,1000000,1000000,1000000,1000000,UTC_TIMESTAMP())",[$i,$i,300+$i*6]);foreach(\Conquer\Game\City\CityState::BUILDING_CODES as $b)$db->execute('INSERT INTO city_buildings(city_id,building_code,level)VALUES(?,?,10)',[$i,$b]);troops($i);}
 $db->execute("INSERT INTO alliances(id,world_id,name,tag,leader_id)VALUES(1,2,'First','ONE',1),(2,2,'Second','TWO',4),(3,2,'Third','THR',7)");
 foreach([[1,1,'leader'],[1,2,'member'],[1,3,'officer'],[2,4,'leader'],[2,5,'member'],[2,6,'officer'],[3,7,'leader'],[3,8,'member']] as $m)$db->execute('INSERT INTO alliance_members(world_id,alliance_id,player_id,role)VALUES(2,?,?,?)',$m);
 $rules=Territory::saveProfile(2,['pvp_window_start_hour_utc'=>0,'pvp_window_hours'=>24,'npc_troops'=>['commune'=>20,'canton'=>40,'crown'=>50],'crown_anchor'=>gmdate('Y-m-d 00:00:00'),'crown_period_days'=>1,'crown_duration_hours'=>24],1);
 tc(count(Territory::mapTargets(2))===113,'all 100 communes, 12 cantons and one crown seeded');tc(TerritoryRules::majority(8)===5&&TerritoryRules::majority(9)===5,'strict majority for even and odd canton sizes');
 $target=(string)$db->query("SELECT id FROM territory_targets WHERE world_id=2 AND kind='commune' AND benefit_type='food' ORDER BY id LIMIT 1")->fetchColumn();cityNear(1,$target);cityNear(2,$target);cityNear(4,$target);
 td(fn()=>cmdt(2,'start',['target_id'=>$target,'city_id'=>2,'troops'=>[$code=>1000],'rally_minutes'=>1]),'ordinary member cannot command an attack');
 $body=['action'=>'start','world_id'=>2,'expected_world_id'=>2,'request_id'=>'territory_start_once_0001','target_id'=>$target,'city_id'=>1,'troops'=>[$code=>1000],'rally_minutes'=>1];$r=Territory::action(1,$body,2);$retry=Territory::action(1,$body,2);tc($r===$retry&&(int)$db->query('SELECT count FROM city_troops WHERE city_id=1 AND troop_code=?',[$code])->fetchColumn()===99000,'lost start response reserves one army');
 cmdt(2,'join',['rally_id'=>$r['rally_id'],'city_id'=>2,'troops'=>[$code=>1000]]);$db->execute('UPDATE rally_participants SET arrival_time=? WHERE rally_id=?',[gmdate('Y-m-d H:i:s',time()-601),$r['rally_id']]);finishRally($r['rally_id']);
 tc((int)Territory::target(2,$target)['owner_alliance_id']===1,'NPC victory transfers commune to rally alliance');tc($db->query('SELECT status FROM rallies WHERE id=?',[$r['rally_id']])->fetchColumn()==='complete','offline processing launches fights and returns armies');
 tc((int)$db->query('SELECT count FROM city_troops WHERE city_id=1 AND troop_code=?',[$code])->fetchColumn()===99900&&(int)$db->query('SELECT count FROM hospital_wounded WHERE city_id=1 AND troop_code=?',[$code])->fetchColumn()===30,'actual attack losses and wounded preserved without duplicate troops');
 $before=$db->query('SELECT SUM(food) FROM alliance_treasury WHERE alliance_id=1')->fetchColumn();Territory::tick(2,time(),1000);tc($before==$db->query('SELECT SUM(food) FROM alliance_treasury WHERE alliance_id=1')->fetchColumn(),'repeated offline tick does not duplicate income');
 $reward=(int)$db->query('SELECT id FROM territory_rewards WHERE player_id=2 LIMIT 1')->fetchColumn();$db->execute('UPDATE alliance_members SET alliance_id=2 WHERE player_id=2');$gold=(int)$db->query('SELECT gold FROM cities WHERE id=2')->fetchColumn();cmdt(2,'claim',['reward_id'=>$reward]);cmdt(2,'claim',['reward_id'=>$reward]);tc((int)$db->query('SELECT gold FROM cities WHERE id=2')->fetchColumn()===$gold+500,'personal reward survives alliance switch and claims exactly once');$db->execute('UPDATE alliance_members SET alliance_id=1 WHERE player_id=2');
 $g=cmdt(2,'reinforce',['target_id'=>$target,'city_id'=>2,'troops'=>[$code=>100]]);$db->execute('UPDATE territory_garrisons SET arrival_at=? WHERE id=?',[gmdate('Y-m-d H:i:s',time()-10),$g['garrison_id']]);Territory::tick(2);tc($db->query('SELECT status FROM territory_garrisons WHERE id=?',[$g['garrison_id']])->fetchColumn()==='active','real reinforcements become stationed garrison');
 $t=Territory::target(2,$target);$db->execute('UPDATE territory_targets SET last_income_at=?,owned_since=? WHERE world_id=2 AND id=?',[gmdate('Y-m-d H:i:s',time()-3600),gmdate('Y-m-d H:i:s',time()-3600),$target]);$before=(int)$db->query('SELECT food FROM alliance_treasury WHERE alliance_id=1')->fetchColumn();
 $attack=cmdt(4,'start',['target_id'=>$target,'city_id'=>4,'troops'=>[$code=>3000],'rally_minutes'=>1]);finishRally($attack['rally_id'],120);tc((int)Territory::target(2,$target)['owner_alliance_id']===2,'rival alliance captures owned commune during announced window');
 tc($db->query('SELECT status FROM territory_garrisons WHERE id=?',[$g['garrison_id']])->fetchColumn()==='returned','defeated garrison survivors automatically return');tc((int)$db->query('SELECT COUNT(*) FROM cities')->fetchColumn()===8,'territory loss preserves every personal city');
 $total=$db->query('SELECT alliance_id,SUM(amount) n FROM territory_income_ledger WHERE target_id=? GROUP BY alliance_id',[$target])->fetchAll(PDO::FETCH_KEY_PAIR);tc(isset($total[1],$total[2]),'old and new owners have separate income receipts');
 $g=cmdt(5,'reinforce',['target_id'=>$target,'city_id'=>5,'troops'=>[$code=>20]]);$db->execute('DELETE FROM alliance_members WHERE player_id=5');$db->execute('UPDATE territory_garrisons SET arrival_at=?,travel_seconds=1 WHERE id=?',[gmdate('Y-m-d H:i:s',time()-10),$g['garrison_id']]);Territory::tick(2);tc($db->query('SELECT status FROM territory_garrisons WHERE id=?',[$g['garrison_id']])->fetchColumn()==='returned','departed member arriving garrison returns safely');
 $cantons=$db->query("SELECT * FROM territory_targets WHERE world_id=2 AND kind='canton' ORDER BY id LIMIT 3")->fetchAll();
 foreach($cantons as $c){$ids=$db->query("SELECT id FROM territory_targets WHERE world_id=2 AND kind='commune' AND canton_id=? ORDER BY id",[$c['canton_id']])->fetchAll(PDO::FETCH_COLUMN);foreach(array_slice($ids,0,TerritoryRules::majority(count($ids))) as $id)$db->execute('UPDATE territory_targets SET owner_alliance_id=1,owned_since=UTC_TIMESTAMP(),last_income_at=UTC_TIMESTAMP() WHERE world_id=2 AND id=?',[$id]);}
 $rules=Territory::saveProfile(2,['canton_limit'=>1],$rules['version']);cityNear(1,$cantons[0]['id']);$first=cmdt(1,'start',['target_id'=>$cantons[0]['id'],'city_id'=>1,'troops'=>[$code=>2000],'rally_minutes'=>1]);
 td(fn()=>cmdt(3,'start',['target_id'=>$cantons[1]['id'],'city_id'=>3,'troops'=>[$code=>1000],'rally_minutes'=>1]),'alpha slot reservation blocks simultaneous second canton');
 $db->execute("UPDATE territory_targets SET owner_alliance_id=NULL WHERE world_id=2 AND kind='commune' AND canton_id=?",[$cantons[0]['canton_id']]);finishRally($first['rally_id']);tc((int)Territory::target(2,$cantons[0]['id'])['owner_alliance_id']===1,'campaign retains majority eligibility after later commune loss');
 $rules=Territory::saveProfile(2,['canton_limit'=>2],$rules['version']);cityNear(3,$cantons[1]['id']);$second=cmdt(3,'start',['target_id'=>$cantons[1]['id'],'city_id'=>3,'troops'=>[$code=>2000],'rally_minutes'=>1]);finishRally($second['rally_id']);td(fn()=>cmdt(1,'start',['target_id'=>$cantons[2]['id'],'city_id'=>1,'troops'=>[$code=>1000],'rally_minutes'=>1]),'regular world limit forbids third canton');
 td(fn()=>cmdt(4,'start',['target_id'=>'crown:krounbuerg','city_id'=>4,'troops'=>[$code=>2000],'rally_minutes'=>1]),'crown rejects alliance without a canton');
 cityNear(1,'crown:krounbuerg');foreach(['gate','arsenal','throne'] as $objective){troops(1);$cr=cmdt(1,'start',['target_id'=>'crown:krounbuerg','city_id'=>1,'troops'=>[$code=>2000],'rally_minutes'=>1,'objective'=>$objective]);finishRally($cr['rally_id'],120);}
 $cycle=(int)$db->query('SELECT MAX(id) FROM territory_crown_cycles')->fetchColumn();$db->execute('UPDATE territory_crown_cycles SET ends_at=? WHERE id=?',[gmdate('Y-m-d H:i:s',time()-1),$cycle]);Territory::tick(2);tc((int)Territory::target(2,'crown:krounbuerg')['owner_alliance_id']===1,'all three objectives plus accumulated control award persistent crown');
 $rules=Territory::saveProfile(2,['income_per_hour'=>0],$rules['version']);
 cmdt(1,'appoint',['player_id'=>2,'title'=>'grande_duchesse']);tc($db->query("SELECT title FROM territory_crown_offices WHERE office='ruler'")->fetchColumn()==='grande_duchesse','victorious leadership appoints Grande-Duchesse');
 foreach(['marshal','treasurer','builder','mage'] as $office)cmdt(1,'appoint',['player_id'=>1,'office'=>$office]);
 cmdt(1,'office_use',['office'=>'treasurer','city_id'=>1]);td(fn()=>cmdt(1,'office_use',['office'=>'treasurer','city_id'=>1]),'crown office ability has shared daily cap');
 $db->execute('UPDATE hospital_wounded SET healing_count=count,healing_ends_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 3600 SECOND) WHERE city_id=1');$healingBefore=(int)$db->query('SELECT UNIX_TIMESTAMP(MAX(healing_ends_at)) FROM hospital_wounded WHERE city_id=1')->fetchColumn();cmdt(1,'office_use',['office'=>'marshal','city_id'=>1]);tc($healingBefore-(int)$db->query('SELECT UNIX_TIMESTAMP(MAX(healing_ends_at)) FROM hospital_wounded WHERE city_id=1')->fetchColumn()===300,'marshal shortens actual paid healing by configured five minutes');
 $db->execute("INSERT INTO building_queue(city_id,building_code,level_to,started_at,finishes_at)VALUES(1,'farm',11,UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(),INTERVAL 3600 SECOND))");$buildBefore=(int)$db->query('SELECT UNIX_TIMESTAMP(MAX(finishes_at)) FROM building_queue WHERE city_id=1')->fetchColumn();cmdt(1,'office_use',['office'=>'builder','city_id'=>1]);tc($buildBefore-(int)$db->query('SELECT UNIX_TIMESTAMP(MAX(finishes_at)) FROM building_queue WHERE city_id=1')->fetchColumn()===300,'builder shortens one real building queue');
 $db->execute("INSERT INTO research_queue(player_id,world_id,research_code,level_to,finishes_at)VALUES(1,2,'food_production',1,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 3600 SECOND))");$researchBefore=(int)$db->query('SELECT UNIX_TIMESTAMP(MAX(finishes_at)) FROM research_queue WHERE player_id=1')->fetchColumn();cmdt(1,'office_use',['office'=>'mage','city_id'=>1]);tc($researchBefore-(int)$db->query('SELECT UNIX_TIMESTAMP(MAX(finishes_at)) FROM research_queue WHERE player_id=1')->fetchColumn()===300,'mage shortens one real research queue');
 $abbey=$db->query("SELECT id FROM territory_targets WHERE world_id=2 AND benefit_type='abbey' LIMIT 1")->fetchColumn();$db->execute('UPDATE territory_targets SET owner_alliance_id=1 WHERE world_id=2 AND id=?',[$abbey]);cmdt(2,'support',['target_id'=>$abbey,'city_id'=>2,'kind'=>'supply']);$rw=$db->query('SELECT * FROM territory_rewards WHERE player_id=2 ORDER BY id DESC LIMIT 1')->fetch();$grant=json_decode($rw['reward_json'],true);tc(!empty($grant['items'][10203015]),'abbey task grants an actual five-minute research item');cmdt(2,'claim',['reward_id'=>(int)$rw['id']]);
 $db->execute("DELETE FROM territory_support WHERE world_id=2 AND kind='supply'");$bankBefore=(int)$db->query('SELECT food FROM alliance_treasury WHERE alliance_id=1')->fetchColumn();foreach([1,2,3] as $pid)cmdt($pid,'support',['target_id'=>$cantons[0]['id'],'city_id'=>$pid,'kind'=>'supply']);tc((int)$db->query('SELECT food FROM alliance_treasury WHERE alliance_id=1')->fetchColumn()===$bankBefore+500,'three different members complete bounded canton supply mission once');
 $base=['food'=>1000,'lumber'=>1000,'stone'=>1000,'gold'=>1000];$bankBefore=(int)$db->query('SELECT food FROM alliance_treasury WHERE alliance_id=1')->fetchColumn();$supply=$db->transaction(fn()=>TerritoryEconomy::regionalKill(2,1,(int)$cantons[0]['x'],(int)$cantons[0]['y'],'fixture-kill:1',$base,time()));$again=$db->transaction(fn()=>TerritoryEconomy::regionalKill(2,1,(int)$cantons[0]['x'],(int)$cantons[0]['y'],'fixture-kill:1',$base,time()));tc($supply===$again&&$supply['food']===50&&(int)$db->query('SELECT food FROM alliance_treasury WHERE alliance_id=1')->fetchColumn()===$bankBefore+50,'regional PvE grants five percent once per actual kill receipt');
 $rune=$db->query("SELECT * FROM territory_targets WHERE world_id=2 AND benefit_type='rune' ORDER BY id LIMIT 1")->fetch();$db->execute('UPDATE territory_targets SET owner_alliance_id=1 WHERE world_id=2 AND id=?',[$rune['id']]);$place=$db->transaction(function()use($db,$rune){\Conquer\Game\Map\WorldPlacement::lockWorld($db,2);return \Conquer\Game\Map\WorldPlacement::findNear($db,2,'city',(int)$rune['x'],(int)$rune['y'],3,10);});tc($place!==null,'rune teleport locates a dry fully free city footprint');
 $runeBody=['action'=>'rune_teleport','target_id'=>$rune['id'],'city_id'=>3,'x'=>$place[0],'y'=>$place[1],'world_id'=>2,'expected_world_id'=>2,'request_id'=>'territory_rune_replay_001'];$teleported=Territory::action(3,$runeBody,2);$replayed=Territory::action(3,$runeBody,2);tc($teleported===$replayed&&(int)$db->query("SELECT used FROM territory_benefit_usage WHERE world_id=2 AND alliance_id=1 AND benefit='rune' AND day_key=UTC_DATE()")->fetchColumn()===1,'rune teleport moves city and retries spend one shared charge');
 td(fn()=>cmdt(4,'rune_teleport',['target_id'=>$rune['id'],'city_id'=>4,'x'=>$place[0]+5,'y'=>$place[1]]),'rival cannot consume another alliance rune charge');
 // Identical simultaneous commands must replay one shared reservation/receipt.
 $rp=new ReflectionProperty($fixture,'directory');$dir=$rp->getValue($fixture);$raceBody=['action'=>'set_goal','world_id'=>2,'expected_world_id'=>2,'request_id'=>'territory_concurrent_goal_1','target_id'=>$target];$jobs=[];
 for($i=0;$i<2;$i++){$process=proc_open([PHP_BINARY,__FILE__,'--worker',$dir,'1',json_encode($raceBody)],[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,ROOT_DIR,null,['bypass_shell'=>true]);fclose($pipes[0]);$jobs[]=[$process,$pipes];}
 $answers=[];foreach($jobs as [$process,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$codeExit=proc_close($process);if($codeExit!==0)throw new RuntimeException($err);$answers[]=json_decode($out,true);}
 tc($answers[0]['ok']&&$answers[1]['ok']&&$answers[0]['result']===$answers[1]['result'],'concurrent lost-response retries return one committed result');
 // Admit a valid journey first; the persisted timestamps below model an already-travelling late army.
 $neutral=(string)$db->query("SELECT id FROM territory_targets WHERE world_id=2 AND kind='commune' AND owner_alliance_id IS NULL ORDER BY id LIMIT 1")->fetchColumn();cityNear(1,$neutral);$db->execute('UPDATE cities SET coord_x=300,coord_y=100 WHERE id=2');troops(1);troops(2);$late=cmdt(1,'start',['target_id'=>$neutral,'city_id'=>1,'troops'=>[$code=>1000],'rally_minutes'=>30]);cmdt(2,'join',['rally_id'=>$late['rally_id'],'city_id'=>2,'troops'=>[$code=>100]]);$at=time();
 $db->execute('UPDATE rallies SET launch_at=? WHERE id=?',[gmdate('Y-m-d H:i:s',$at-5),$late['rally_id']]);$db->execute('UPDATE rally_participants SET joined_at=?,arrival_time=? WHERE rally_id=?',[gmdate('Y-m-d H:i:s',$at-20),gmdate('Y-m-d H:i:s',$at+200),$late['rally_id']]);Territory::tick(2,$at);
 tc((int)$db->query('SELECT count FROM city_troops WHERE city_id=2 AND troop_code=?',[$code])->fetchColumn()===99900&&Territory::hasDetachedArmy(2,2),'late joiner turns around and remains reserved while travelling home');Territory::tick(2,$at+9);tc((int)$db->query('SELECT count FROM city_troops WHERE city_id=2 AND troop_code=?',[$code])->fetchColumn()===99900,'late joiner cannot be reused before actual return');Territory::tick(2,$at+10);Territory::tick(2,$at+10);tc((int)$db->query('SELECT count FROM city_troops WHERE city_id=2 AND troop_code=?',[$code])->fetchColumn()===100000,'late joiner returns once at scheduled turnaround travel end');Territory::tick(2,$at+2000);
 $neutral=(string)$db->query("SELECT id FROM territory_targets WHERE world_id=2 AND kind='commune' AND owner_alliance_id IS NULL ORDER BY id LIMIT 1")->fetchColumn();cityNear(3,$neutral);troops(3);$cancel=cmdt(3,'start',['target_id'=>$neutral,'city_id'=>3,'troops'=>[$code=>1000],'rally_minutes'=>30]);cmdt(2,'join',['rally_id'=>$cancel['rally_id'],'city_id'=>2,'troops'=>[$code=>100]]);$at=time();$db->execute('UPDATE rally_participants SET joined_at=?,arrival_time=? WHERE rally_id=?',[gmdate('Y-m-d H:i:s',$at-20),gmdate('Y-m-d H:i:s',$at+200),$cancel['rally_id']]);cmdt(3,'cancel',['rally_id'=>$cancel['rally_id']]);tc((int)$db->query('SELECT count FROM city_troops WHERE city_id=2 AND troop_code=?',[$code])->fetchColumn()===99900,'cancelling rally preserves travelling participant return route');Territory::tick(2,$at+21);tc((int)$db->query('SELECT count FROM city_troops WHERE city_id=2 AND troop_code=?',[$code])->fetchColumn()===100000,'cancelled participant arrives home with all reserved troops');
 tc((int)$db->query('SELECT COUNT(*) FROM cities')->fetchColumn()===8,'complete commune-canton-crown cycle never resets personal cities');
 echo "ALL TERRITORY LIFECYCLE CHECKS PASSED\n";
}finally{$fixture->close();}
