'use strict';
// Disposable HTTP fixture: exercises the live renderer/controller without an account/database.
const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),assert=require('assert');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'uok-territory-ui-'));
const planStrings=Object.fromEntries(Object.entries(JSON.parse(fs.readFileSync(path.join(root,'data/i18n/de.json'),'utf8'))).filter(([key])=>key.startsWith('alliance.plan.')||key.startsWith('territory.ui.')||key.startsWith('report.')||key.startsWith('events.')));
const geo=JSON.parse(fs.readFileSync(path.join(root,'assets/world-lux-preview/game-geography.json'),'utf8'));
const targets=[...geo.communes.map((c,i)=>({id:'commune:'+c.id,kind:'commune',name:'Commune '+c.name,canton_id:c.canton,commune_id:c.id,x:c.point[0],y:c.point[1],benefit_type:['food','lumber','stone','gold','abbey','rune'][i%6],owner_alliance_id:i===0?7:null,owner_name:i===0?'Testallianz':null,active:true,can_attack:i!==0,blocked_reason:i===0?'Deine Allianz kontrolliert das Gebiet':null,next_window:{starts_at:'2026-10-01T17:00:00Z',ends_at:'2026-10-01T21:00:00Z'},campaigns:[],garrisons:[]})),...geo.cantons.map(c=>({id:'canton:'+c.id,kind:'canton',name:'Shrine of '+c.name,canton_id:c.id,x:c.point[0],y:c.point[1],can_attack:false,blocked_reason:'Gemeindemehrheit fehlt'})),{id:'crown:krounbuerg',kind:'crown',name:'Royal Castle',x:400,y:600,can_attack:false,blocked_reason:'Mindestens ein Shrine erforderlich'}];
let commands=[],responsesLost=new Set();
const fixture=`<!doctype html><html lang="de"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
${['fantasy-fonts','game','world-atlas','map-overlay','castle-skins','world-encounters','world-map','mobile-shell','combat-report','territory','village-theme'].map(n=>`<link rel="stylesheet" href="/assets/css/${n}.css">`).join('')}
<style>body{margin:0}#map{height:100dvh}.atlas-shell{height:100%!important}#launch{position:fixed;top:45%;left:10px;z-index:1000}dialog{max-width:95vw}</style><body class="mobile-game"><button id="launch">Allianzgebiete</button><div id="map"></div><dialog id="game-dialog" class="mobile-detail-page"><button class="dialog-close">×</button><div id="dialog-content"></div></dialog>
<script>window.ConquerTerrainData=${fs.readFileSync(path.join(root,'data/world_terrain.json'),'utf8')};</script>
${['browser-compat','castle-skins','world-landscape','world-encounters','world-lux','territory-art','world-map','territory-panel','combat-report'].map(n=>`<script src="/assets/js/${n}.js"></script>`).join('')}
<script>
const profile={key:'luxembourg',version:1,width:768,height:1100,geography_url:'assets/world-lux-preview/game-geography.json',hydrology_url:'assets/world-lux-preview/game-hydrology.json'};
window.gameState={world:{id:92,map_profile:profile},city:{id:5,player_id:4,world_id:92,name:'Teststadt',coord_x:400,coord_y:690,castle_level:3,city_skin:'default'},player:{id:4,name:'Test'},troops:{1:400},troop_defs:[{code:1,name:'Infanterie',tier:1,type:1}],players:[],nodes:[],monsters:[],charms:[],marches:[],territory:{alliance_id:7,map_targets:${JSON.stringify(targets)}}};
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const planStrings=${JSON.stringify(planStrings)},t=(key,parameters={})=>Object.entries(parameters).reduce((text,[name,value])=>text.replaceAll('{'+name+'}',String(value)),planStrings[key]||key);
window.ConquerLocale={locale:'de',t,text:value=>value};
window.controller=ConquerTerritory({base:'',getState:()=>gameState,getKingdom:()=>({}),esc,t,fmt:n=>Number(n).toLocaleString('de'),unitName:r=>r.name,toast:m=>window.lastToast=m,refresh:async()=>{},navigate:()=>{},openDialog:html=>{document.querySelector('#dialog-content').innerHTML=html;const d=document.querySelector('dialog');if(!d.open)d.showModal()},api:async(p,b)=>{const r=await fetch('/api/'+p,{method:b?'POST':'GET',headers:{'Content-Type':'application/json'},body:b?JSON.stringify(b):undefined});if(!r.ok)throw new Error('Verbindung unterbrochen');return r.json()}});
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)controller.onClick(b.dataset.action,b)});document.addEventListener('submit',e=>{if(e.target.matches('[data-form]')){e.preventDefault();controller.onSubmit(e.target)}});document.querySelector('#launch').onclick=()=>controller.open();
window.options={host:document.querySelector('#map'),base:'',esc,now:()=>Date.now(),state:gameState,monsterArt:()=>'orc',onTerritory:id=>controller.open(id)};ConquerWorld.render(options);
</script></body></html>`;
const server=http.createServer(async(req,res)=>{
 const url=new URL(req.url,'http://localhost');res.setHeader('Content-Type','application/json');
 if(url.pathname==='/'){res.setHeader('Content-Type','text/html');res.end(fixture);return;}
 if(url.pathname==='/api/territory/state'){res.end(JSON.stringify({world_id:92,enabled:true,alliance_id:7,role:'leader',profile:{version:1,canton_limit:2,support_cost:1000,income_per_hour:1200,crown_objectives:['gate','arsenal','throne'],crown_tie_rule:'first_to_control'},targets,progress:[{canton_id:'01',name:'Capellen',held:1,total:9,required:5}],history:[],rewards:[],crown:null}));return;}
 if(url.pathname==='/api/territory/target'){const t=targets.find(t=>t.id===url.searchParams.get('id'));res.end(JSON.stringify({...t,npc_power:1300,garrison_count:0,profile:{support_cost:1000,income_per_hour:1200},rewards:[],garrisons:[],campaigns:[]}));return;}
 if(url.pathname==='/api/territory/action'){let raw='';for await(const chunk of req)raw+=chunk;const command=JSON.parse(raw);commands.push(command);if(command.action==='start'&&!responsesLost.has(command.request_id)){responsesLost.add(command.request_id);res.writeHead(503);res.end('{}');return;}res.end(JSON.stringify({message:'Auftrag bestätigt.'}));return;}
 const file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}
 res.setHeader('Content-Type',/\.m?js$/.test(file)?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.webp')?'image/webp':file.endsWith('.png')?'image/png':'application/octet-stream');res.end(fs.readFileSync(file));
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});
 for(const viewport of [{width:1280,height:800},{width:390,height:844},{width:320,height:568},{width:844,height:390},{width:568,height:320}]){
  const page=await browser.newPage({viewport}),errors=[];page.setDefaultTimeout(8000);page.setDefaultNavigationTimeout(30000);page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);await page.waitForFunction(()=>document.querySelector('.atlas-biome-label').textContent.includes('Kanton'));
  assert.equal(await page.locator('[data-kind="territory"]').count(),113,'all live landmarks rendered from server state');
  await page.waitForFunction(()=>[...document.querySelectorAll('[data-kind="territory"] img')].every(img=>img.complete&&img.naturalWidth>0));
  const artSources=await page.locator('[data-kind="territory"] img').evaluateAll(imgs=>[...new Set(imgs.map(img=>img.getAttribute('src')))]);
  assert.equal(artSources.length,8,'six commune benefits, a canton fortress and the crown have distinct art');
  assert(artSources.every(src=>src.startsWith('/assets/art/territory-v2/')),'map uses the shared painted territory set');
  await page.evaluate(()=>ConquerWorld.focus(700,1030));assert.deepEqual(await page.evaluate(()=>({x:ConquerWorld.getCenter().x,y:ConquerWorld.getCenter().y})),{x:700,y:1030});
  await page.locator('[data-atlas="navigation"]').click();assert.equal(await page.locator('.atlas-jump [name="x"]').getAttribute('max'),'767');assert.equal(await page.locator('.atlas-jump [name="y"]').getAttribute('max'),'1099');assert.equal(await page.locator('.atlas-zone-jumps').first().getByText('Kongress').count(),0);
  await page.locator('#atlas-navigation-panel [data-atlas="clear"]').click();await page.locator('#launch').click();await page.waitForSelector('.territory-overview');assert.equal(await page.locator('.territory-route-step').count(),3,'Overview starts with three clear conquest steps');await page.locator('[data-action=territory-tab][data-id=territories]').click();await page.waitForSelector('.territory-row');assert.equal(await page.locator('.territory-row').count(),113,'All objectives remain available as compact rows');
  for(const tab of ['goal','history','crown','territories']){await page.locator(`[data-action="territory-tab"][data-id="${tab}"]`).click();await page.waitForTimeout(90);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);const actions=await page.locator('.territory-heading button,.territory-tabs button,.territory-footer button').evaluateAll(els=>els.map(e=>{const b=e.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height}}));assert(actions.every(b=>b.x>=-1&&b.y>=-1&&b.x+b.w<=viewport.width+1&&b.y+b.h<=viewport.height+1),'Fixed actions stay inside viewport '+JSON.stringify({viewport,actions}));}
  const search=page.locator('[name=territory-search]');await search.fill('Capellen');assert(await page.locator('.territory-row').count()>0&&await page.locator('.territory-row').count()<113,'Search narrows targets');assert.equal(await search.evaluate(el=>el===document.activeElement),true,'Search retains focus after filtering');
  const resultTarget=await page.locator('.territory-row [data-action=territory-target]').first().getAttribute('data-id');await page.locator('.territory-row [data-action=territory-target]').first().click();await page.waitForSelector('.territory-target-summary');assert.equal(await page.locator('[data-disclosure=facts]').getAttribute('open'),null,'Reference details start folded');await page.locator('[data-disclosure=facts] summary').click();await page.locator('[data-action=territory-reload]').click();await page.waitForTimeout(100);assert.equal(await page.locator('[data-disclosure=facts]').evaluate(el=>el.open),true,'Refresh preserves disclosure state');await page.locator('[data-action=territory-back]').click();await page.waitForSelector('[name=territory-search]');assert.equal(await search.inputValue(),'Capellen','Back preserves search');
  await page.locator(`[data-action=territory-target][data-id="${resultTarget}"]`).click();await page.waitForSelector('.territory-target-summary');assert.equal(await page.locator('[data-disclosure=facts]').evaluate(el=>el.open),true,'Returning to a target preserves expanded details');await page.locator('[data-action=territory-back]').click();await page.waitForSelector('[name=territory-search]');await search.fill('');await page.locator('[name=territory-scope]').selectOption('owned');assert.equal(await page.locator('.territory-row').count(),1,'Ownership filter shows the one allied Commune');await page.locator('[name=territory-scope]').selectOption('all');
  await page.locator('.territory-body').evaluate(el=>el.scrollTop=400);const oldScroll=await page.locator('.territory-body').evaluate(el=>el.scrollTop);await page.locator('[data-action=territory-reload]').click();await page.waitForTimeout(100);assert.equal(await page.locator('.territory-body').evaluate(el=>el.scrollTop),oldScroll,'Refresh preserves list scroll');
  await page.locator('[data-action="territory-filter"][data-id="commune"]').click();await page.locator('[data-action="territory-target"]').nth(1).click();await page.waitForSelector('[data-action="territory-army"][data-mode="start"]');await page.locator('[data-action="territory-army"][data-mode="start"]').click();await page.locator('[data-territory-troop="1"]').fill('10');assert.match(await page.locator('.territory-army-total').innerText(),/10 Truppen/);
  await page.screenshot({path:path.join(out,`${viewport.width}x${viewport.height}.png`)});
  if(viewport.width===1280){await page.locator('[data-form="territory-army"] [type="submit"]').click();await page.waitForSelector('[data-action="territory-retry"]');const first=commands.at(-1);assert.equal(first.world_id,92);assert.equal(first.expected_world_id,92);assert.equal(first.troops['1'],10);assert(first.request_id);await page.reload();await page.locator('#launch').click();await page.waitForSelector('[data-action="territory-retry"]');await page.locator('[data-action="territory-retry"]').click();await page.waitForFunction(()=>!document.querySelector('[data-action="territory-retry"]'));assert.equal(commands.at(-1).request_id,first.request_id,'Retry after reload preserves request ID');}
  await page.evaluate(()=>{
    document.querySelector('#game-dialog').close();
    const army={name:'Testangreifer',x:400,y:690,avatar:'knight',troops:[],equipment:null,talents:null,totals:{sent:10,dead:0,injured:1,survived:9,power_lost:1}};
    const report={id:42,target_x:401,target_y:690,created_at:'2026-09-28 19:00:00',outcome:'attacker_wins',details:{battle_kind:'territory',perspective:'attacker',target_name:'Commune Test',npc_troops:120,combat:{attacker:{armies:[army],totals:army.totals,types:{},score:400},defender:{armies:[],totals:{},types:{},score:120},npc_troops:120}}};
    window.testReport=report;window.testCombat=ConquerCombatReport({base:'',esc:s=>String(s).replaceAll('<','&lt;'),fmt:n=>String(n),toast:()=>{},unitName:r=>r.name,getState:()=>({...gameState,reports:[report]}),openReport:()=>{},openDialog:html=>{document.querySelector('#dialog-content').innerHTML=html;document.querySelector('#game-dialog').showModal()}});testCombat.open(report);
  });
  assert.match(await page.locator('#game-dialog').innerText(),/Gebiets-Kampfbericht/);assert.match(await page.locator('.cr-versus').innerText(),/NPC-Besatzung/);assert.match(await page.locator('.cr-result strong').innerText(),/Sieg/);
  await page.locator('[data-combat="details"]').click();assert.match(await page.locator('#combat-details').innerText(),/120 Truppen/);await page.locator('[data-combat="close-details"]').click();
  await page.evaluate(()=>{document.querySelector('#game-dialog').close();testReport.details.perspective='defender';testCombat.open(testReport)});assert.match(await page.locator('.cr-result strong').innerText(),/Niederlage/);
  if(viewport.width===1280){
   await page.addScriptTag({path:path.join(root,'assets/js/progression-panel.js')});
   await page.evaluate(()=>{document.querySelector('#game-dialog').close();window.ConquerTalents=()=>({onClick:()=>false});const panel=document.createElement('aside');panel.id='panel-dialog';panel.dataset.panel='events';panel.innerHTML='<div id="content"></div>';document.body.append(panel);window.testEvents=ConquerProgression({getState:()=>gameState,esc:s=>String(s),fmt:n=>String(n),api:async()=>({events:{chapter:1,invasions:[],events:[{id:8,state:'active',starts_at:'2026-09-01',ends_at:'2099-01-01'}]}})});testEvents.render('events')});
   await page.waitForSelector('.event-reference-calendar',{state:'attached'});assert.equal(await page.locator('.progression-content [data-id="conquest:8"],.progression-content [data-action=shrine-open]').count(),0,'Luxembourg does not expose stale legacy shrine events');assert.equal(await page.locator('.progression-content [data-action="territory-open"]').count(),1);
  }
  assert.deepEqual(errors,[]);await page.close();console.log(`PASS ${viewport.width}×${viewport.height}: Luxembourg map, 113 targets, goals/history/crown, army actions and reachable controls`);
 }
 console.log('Screenshots: '+out);
}finally{await browser?.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
