<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit(1);
define('ROOT_DIR',dirname(__DIR__));require ROOT_DIR.'/src/Bootstrap.php';\Conquer\Bootstrap::init(ROOT_DIR);require __DIR__.'/Support/FeatureDatabase.php';
use Conquer\Db\Connection;use Conquer\Game\Trading\TradingShopService as Shop;use Conquer\Game\World\WorldContext;use Conquer\Game\Inventory\InventoryService;use Conquer\Game\Kingdom\KingdomInventory;
$fixture=new \ConquerTests\FeatureDatabase();$db=Connection::getInstance();$checks=0;$failed=false;$server=null;$httpFiles=[];
function checkShop(bool $ok,string $message):void{global$checks;if(!$ok)throw new RuntimeException($message);$checks++;}
function rejectShop(callable $fn,string $message):void{try{$fn();}catch(DomainException $e){checkShop(true,$message);return;}throw new RuntimeException($message);}
function buyShop(string $mode,array $offer,int $qty=1):array{$s=Shop::state(1);return Shop::buy(1,$mode,$offer['id'],$qty,($mode==='vip'?$s['vip']:$s)['rotation']);}
try{
 \Conquer\Db\MigrationSql::apply($db->getPdo(),file_get_contents(ROOT_DIR.'/migrations/0078_trading_shop.sql'));
 $db->execute("UPDATE worlds SET status='open',speed_factor=1 WHERE id=1");$db->execute("INSERT INTO worlds(id,name,slug,status)VALUES(2,'ShopTwo','shop-two','open')");
 $db->execute("INSERT INTO players(id,username,email,password_hash,gems,vip_points)VALUES(1,'ShopFixture','shop@tests.invalid','unused',100000000,0),(2,'ShopOther','shopother@tests.invalid','unused',100000000,0)");
 $db->execute("INSERT INTO cities(id,player_id,world_id,name,coord_x,coord_y,food,lumber,stone,gold,castle_level)VALUES(1,1,1,'ShopFixture',30,40,100000000,100000000,100000000,100000000,30),(2,1,2,'ShopOtherWorld',30,40,100000000,100000000,100000000,100000000,30)");
 foreach([1,2]as$cid)foreach(\Conquer\Game\City\CityState::BUILDING_CODES as$code)$db->execute('INSERT INTO city_buildings(city_id,building_code,level)VALUES(?,?,?)',[$cid,$code,$code==='trading_post'?0:1]);
 WorldContext::bind(1);$s=Shop::state(1);checkShop($s['offers']===[]&&$s['market_level']===0,'unbuilt market has no caravan');checkShop(count($s['vip']['offers'])===52,'all reference VIP offers are visible');rejectShop(fn()=>buyShop('vip',$s['vip']['offers'][0]),'unbuilt market cannot buy VIP');
 $db->execute("UPDATE city_buildings SET level=1 WHERE building_code='trading_post'");$s=Shop::state(1);checkShop(count($s['offers'])===4,'level1 four offers');$first=array_column($s['offers'],'id');
 for($lvl=2;$lvl<=30;$lvl++){$db->execute("UPDATE city_buildings SET level=? WHERE city_id=1 AND building_code='trading_post'",[$lvl]);$next=Shop::state(1);checkShop(count($next['offers'])>=count($first),'stock expands monotonically');checkShop(array_slice(array_column($next['offers'],'id'),0,count($first))===$first,'upgrade preserves existing offerings');$first=array_column($next['offers'],'id');}
 checkShop(count($next['offers'])===20,'level30 shows all20 eligible offers');$s=Shop::state(1);rejectShop(fn()=>buyShop('vip',$s['vip']['offers'][0]),'VIP0 deniesVIP1');
 $db->execute('UPDATE players SET vip_points=3000000 WHERE id=1');$s=Shop::state(1);checkShop($s['vip']['level']===16,'VIP derived from real points');
 $gemOffer=array_values(array_filter($s['vip']['offers'],fn($o)=>$o['price']['resource']==='gems'))[0];$db->execute('UPDATE players SET gems=0 WHERE id=1');rejectShop(fn()=>buyShop('vip',$gemOffer),'VIP points still require sufficient crystals');$db->execute('UPDATE players SET gems=100000000 WHERE id=1');
 $vip=$s['vip']['offers'];foreach($vip as$o){
  checkShop($o['remaining']===$o['limit']&&$o['price']['amount']*$o['limit']===$o['reference_total'],'reference BuyAll price '.$o['id']);
  $resource=$o['price']['resource'];$table=$resource==='gems'?'players':'cities';$old=(int)$db->query("SELECT $resource FROM $table WHERE id=1")->fetchColumn();$oldQty=(int)$db->query('SELECT quantity FROM player_inventory WHERE player_id=1 AND item_code=?',[$o['item_code']])->fetchColumn();
  $r=buyShop('vip',$o,$o['limit']);$new=(int)$db->query("SELECT $resource FROM $table WHERE id=1")->fetchColumn();
  checkShop($old-$new===$o['reference_total'],'exact real currency payment '.$o['id']);checkShop((int)$db->query('SELECT quantity FROM player_inventory WHERE player_id=1 AND item_code=?',[$o['item_code']])->fetchColumn()===$oldQty+$o['limit'],'exact inventory credit '.$o['id']);
  checkShop($r['remaining']===0,'weekly depleted '.$o['id']);rejectShop(fn()=>buyShop('vip',$o),'cannot exceed weekly stock '.$o['id']);
 }
 $s=Shop::state(1);checkShop(array_sum(array_column($s['vip']['offers'],'remaining'))===0,'allVIPstock consumed');
 WorldContext::bind(2);$s2=Shop::state(1);checkShop(array_sum(array_column($s2['vip']['offers'],'remaining'))===0,'VIP weekly stock shared across worlds');rejectShop(fn()=>buyShop('vip',$vip[0]),'otherworld cannot refreshVIP');WorldContext::bind(1);
 $o=$s['offers'][0];$rotation=$s['rotation'];rejectShop(fn()=>Shop::buy(1,'caravan',$o['id'],1,'caravan-0'),'stale8h rejected');rejectShop(fn()=>Shop::buy(1,'vip',$vip[0]['id'],1,'vip-0'),'staleweek rejected');rejectShop(fn()=>Shop::buy(1,'caravan','unknown',1,$rotation),'unknownoffer rejected');rejectShop(fn()=>Shop::buy(1,'caravan',$o['id'],0,$rotation),'zeroquantity rejected');rejectShop(fn()=>Shop::buy(1,'caravan',$o['id'],101,$rotation),'hugequantity rejected');rejectShop(fn()=>Shop::buy(2,'caravan',$o['id'],1,$rotation),'missingcity rejected');
 $resourceOffer=array_values(array_filter($s['offers'],fn($x)=>$x['price']['resource']!=='gems'))[0];$resource=$resourceOffer['price']['resource'];$db->execute("UPDATE cities SET $resource=0,last_resource_update=UTC_TIMESTAMP() WHERE id=1");$before=(int)$db->query('SELECT SUM(quantity) FROM trading_shop_purchases WHERE player_id=1')->fetchColumn();rejectShop(fn()=>buyShop('caravan',$resourceOffer),'insufficient resource rejected');checkShop((int)$db->query('SELECT SUM(quantity) FROM trading_shop_purchases WHERE player_id=1')->fetchColumn()===$before,'failed purchase preserves stock');$db->execute("UPDATE cities SET $resource=100000000 WHERE id=1");
 checkShop(count(array_filter($s['offers'],fn($x)=>$x['price']['resource']==='gems'))===0,'caravan has no crystal-priced non-VIP items');
 foreach($s['offers']as$o){$old=$o['treasure_code']??null;$qty=$old?(int)$db->query('SELECT fragments FROM player_treasures WHERE player_id=1 AND treasure_code=?',[$old])->fetchColumn():0;$r=buyShop('caravan',$o);checkShop($r['remaining']===0,'normal purchase depletes onlyslot');if($old)checkShop((int)$db->query('SELECT fragments FROM player_treasures WHERE player_id=1 AND treasure_code=?',[$old])->fetchColumn()===$qty+1,'targetedfragment real grant');rejectShop(fn()=>buyShop('caravan',$o),'normal cannotbuytwice');}
 WorldContext::bind(2);checkShop(array_sum(array_column(Shop::state(1)['offers'],'remaining'))===4,'normal caravan stock belongs toworld');WorldContext::bind(1);
 $t=strtotime('2026-09-14 00:00:00 UTC');checkShop(Shop::period('vip',$t)['start']===$t&&Shop::period('vip',$t-1)['end']===$t,'UTC Monday weekly rollover');foreach([0,8,16]as$h){$t=strtotime('2026-09-14 '.sprintf('%02d',$h).':00:00 UTC');checkShop(Shop::period('caravan',$t)['start']===$t&&Shop::period('caravan',$t-1)['end']===$t,'8h rollover '.$h);}
 // Old rows are ignored after rotation, without deleting purchase history.
 $db->execute("UPDATE trading_shop_purchases SET rotation='old-rotation' WHERE player_id=1");$s=Shop::state(1);checkShop(array_sum(array_column($s['vip']['offers'],'remaining'))===array_sum(array_column($s['vip']['offers'],'limit')),'newweek restocks');checkShop(array_sum(array_column($s['offers'],'remaining'))===20,'new8h restocks');
 // Outer transaction rollback leaves neither the item, currency nor stock changed.
 $o=$s['offers'][0];$gemBefore=(int)$db->query('SELECT gems FROM players WHERE id=1')->fetchColumn();try{$db->transaction(function()use($o){buyShop('caravan',$o);throw new RuntimeException('rollback fixture');});}catch(RuntimeException $e){}
 checkShop(Shop::state(1)['offers'][0]['remaining']===1,'outerTX rollback restores stock');checkShop((int)$db->query('SELECT gems FROM players WHERE id=1')->fetchColumn()===$gemBefore,'outerTX rollback restores gems');
 $drops=json_decode(file_get_contents(ROOT_DIR.'/data/chest_drops.json'),true)['chests'];foreach(['silver','gold']as$type)foreach($vip as$o)checkShop(count(array_filter($drops[$type]['drop_table'],fn($d)=>($d['item_code']??0)===$o['item_code']&&$d['weight']>0))>0,'VIP item obtainable from '.$type.' '.$o['id']);
 $orb=InventoryService::getItemDef(10300003);InventoryService::addItems(1,10300003,1);$old=(int)$db->query('SELECT fragments FROM player_treasures WHERE player_id=1 AND treasure_code=60300115')->fetchColumn();$db->transaction(fn()=>KingdomInventory::use(1,['city'=>['id'=>1]],['item_code'=>$orb['code']]));checkShop((int)$db->query('SELECT fragments FROM player_treasures WHERE player_id=1 AND treasure_code=60300115')->fetchColumn()===$old+1,'VIPOrb item targets correcttreasure');
 $s=Shop::state(1);$o=$s['offers'][0];$body=['action'=>'trading.buy','mode'=>'caravan','offer_id'=>$o['id'],'quantity'=>1,'rotation'=>$s['rotation'],'expected_world_id'=>1];
 foreach([['quantity'=>'1.5'],['quantity'=>1.5],['quantity'=>[1]],['offer_id'=>[]],['rotation'=>[]],['mode'=>[]]]as$bad)rejectShop(fn()=>\Conquer\Game\Kingdom\KingdomService::action(1,array_replace($body,$bad)),'malformed Kingdom action rejected');
 $r=\Conquer\Game\Kingdom\KingdomService::action(1,$body);checkShop($r['result']['remaining']===0,'real Kingdom trading action');
 $afterOffer=array_values(array_filter($r['state']['trading']['offers'],fn($x)=>$x['id']===$o['id']))[0];checkShop($afterOffer['remaining']===0,'real Kingdom action returns updated trading state');
 rejectShop(fn()=>\Conquer\Game\Kingdom\KingdomService::action(1,array_replace($body,['expected_world_id'=>2])),'Kingdom action rejects wrongworld');
 // Real HTTP adapter with a disposable DB/session and loopback-only server.
 $httpDir=sys_get_temp_dir().DIRECTORY_SEPARATOR.$db->query('SELECT DATABASE()')->fetchColumn();$token=bin2hex(random_bytes(32));
 $db->execute("INSERT INTO sessions(player_id,token,csrf_token,ip_address,user_agent,expires_at,active_world_id)VALUES(1,?,'shop-test','127.0.0.1','isolated shop test',DATE_ADD(UTC_TIMESTAMP(),INTERVAL 10 MINUTE),1)",[$token]);
 $router="<?php define('ROOT_DIR',".var_export(ROOT_DIR,true).");require ROOT_DIR.'/src/Autoloader.php';(new \\Conquer\\Autoloader(ROOT_DIR.'/src'))->register();date_default_timezone_set('UTC');\\Conquer\\Db\\Connection::init(".var_export($httpDir,true).");\\Conquer\\Logger::init(".var_export($httpDir.'/http.log',true).");if(str_ends_with(parse_url(\$_SERVER['REQUEST_URI'],PHP_URL_PATH),'/buy'))\\Conquer\\Api\\Handlers\\TradingHandler::buy([]);else \\Conquer\\Api\\Handlers\\TradingHandler::caravan([]);";
 file_put_contents($httpDir.'/router.php',$router);$httpFiles=[$httpDir.'/router.php',$httpDir.'/http.log',$httpDir.'/server.log'];$socket=stream_socket_server('tcp://127.0.0.1:0',$errno,$error);$address=stream_socket_get_name($socket,false);fclose($socket);
 $server=proc_open([PHP_BINARY,'-S',$address,$httpDir.'/router.php'],[0=>['pipe','r'],1=>['file',$httpDir.'/server.log','a'],2=>['file',$httpDir.'/server.log','a']],$pipes,$httpDir);fclose($pipes[0]);
 $ready=false;for($i=0;$i<40;$i++){$probe=@fsockopen('127.0.0.1',(int)substr(strrchr($address,':'),1),$errno,$error,.1);if($probe){fclose($probe);$ready=true;break;}usleep(50000);}if(!$ready)throw new RuntimeException('HTTP test server unavailable');
 $http=static function(?array $body=null,int $status=200,bool $csrf=true,bool $auth=true)use($address,$token):array{
  $ch=curl_init('http://'.$address.'/api/trading/caravan'.($body!==null?'/buy':''));$headers=['Content-Type: application/json','X-CSRF-Token: '.($csrf?'shop-test':'invalid')];if($auth)$headers[]='Cookie: conquer_session='.$token;
  curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>$headers,CURLOPT_TIMEOUT=>15]);if($body!==null)curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>json_encode($body)]);
  $raw=curl_exec($ch);$actual=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);$json=json_decode((string)$raw,true);checkShop($actual===$status&&is_array($json),'HTTP expected'.$status.' got'.$actual.' '.($actual!==$status?$raw:''));return$json;
 };
 $h=$http();checkShop(count($h['data']['offers'])===20&&count($h['data']['vip']['offers'])===52,'HTTP state exposes same authoritative shop');$http(null,401,true,false);
 $candidate=array_values(array_filter($h['data']['offers'],fn($x)=>$x['remaining']>0))[0];$payload=['mode'=>'caravan','offer_id'=>$candidate['id'],'quantity'=>1,'rotation'=>$h['data']['rotation'],'expected_world_id'=>1];
 $http($payload,403,false);$http($payload,401,true,false);$http(['slot_idx'=>0],400);$http(array_replace($payload,['quantity'=>'1.5']),400);$http(array_replace($payload,['quantity'=>[]]),400);$http(array_replace($payload,['rotation'=>[]]),400);$http(array_replace($payload,['expected_world_id'=>2]),409);$http(array_replace($payload,['rotation'=>'caravan-0']),409);
 $h=$http($payload);checkShop($h['data']['result']['remaining']===0&&isset($h['data']['state']['vip']['offers']),'HTTP actual purchase returns updated shop');$http($payload,422);
 $db->execute("UPDATE worlds SET status='paused' WHERE id=1");rejectShop(fn()=>buyShop('caravan',$o),'paused world denies shop');$http($payload,409);
 echo "PASS $checks trading-shop checks:52 VIP,20 caravan,UTC resets,currency,rollback,worldscope and chests.\n";
}catch(Throwable $e){$failed=true;fwrite(STDERR,'FAIL '.$e->getMessage()."\n".$e->getTraceAsString()."\n");}finally{if(is_resource($server)){proc_terminate($server);proc_close($server);}foreach($httpFiles as$file)if(is_file($file))unlink($file);$fixture->close();}exit($failed?1:0);
