'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),fixture=require('./fixtures/world_march_motion.cjs'),output=path.join(root,'artifacts/world-march-follow-20260913');fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'index.html'),fixture(root,'/conquer'));
(async()=>{
 const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(name==='/'){res.setHeader('Content-Type','text/html');res.end(fixture(root));return;}const file=path.resolve(root,'.'+name);if(!name.startsWith('/assets/')||!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.webp')?'image/webp':'application/octet-stream');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{
  browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(()=>{demoAuto=false;window.groundCalls=0;const ground=ConquerLandscape.ground;ConquerLandscape.ground=(...args)=>{groundCalls++;return ground(...args)};});
  const actor=page.locator('.atlas-march-party'),card=page.locator('.world-march-card'),row=page.locator('.world-march-row');
  await page.waitForSelector('.atlas-march-party.is-skinned');assert.match(await actor.locator('.atlas-party-skin img').getAttribute('src'),/flight-phoenix.webp/);
  await page.evaluate(()=>{startMarch(5,12000);ConquerWorld.followMarch(options.state.marches[0].id)});await page.waitForTimeout(1400);assert(await card.isVisible());
  const sample=await page.evaluate(()=>new Promise(resolve=>{const points=[],ground=groundCalls,center=[...document.querySelector('.atlas-march-party').worldPoint],start=performance.now(),actor=document.querySelector('.atlas-march-party');function tick(t){const m=new DOMMatrix(getComputedStyle(actor).transform);points.push([m.m41,m.m42]);if(t-start<1600)requestAnimationFrame(tick);else resolve({points,ground:groundCalls-ground,center,end:actor.worldPoint});}requestAnimationFrame(tick)}));
  assert(sample.points.length>20);assert(Math.max(...sample.points.map(p=>p[0]))-Math.min(...sample.points.map(p=>p[0]))<4,'Following keeps march steady on screen');const travelled=Math.hypot(sample.end[0]-sample.center[0],sample.end[1]-sample.center[1]);assert(travelled>.4,'World position advances while the camera holds the march: '+travelled);assert(sample.ground<sample.points.length*.15,'Following reuses scenery between occasional terrain rebases');
  await page.evaluate(()=>ConquerWorld.render(options));assert(await card.isVisible(),'Server refresh preserves selected march');
  await page.locator('[data-march-command="details"]').click();assert.match(await page.locator('.world-march-details').innerText(),/Infanterie/);
  const before=await actor.evaluate(el=>[...el.worldPoint]);await page.locator('[data-march-command="recall"]').click();await page.waitForTimeout(70);const after=await actor.evaluate(el=>el.worldPoint);assert(Math.hypot(after[0]-before[0],after[1]-before[1])<.25,'Early recall turns at the actual location: '+JSON.stringify({before,after}));assert.match(await card.innerText(),/Rückkehr/);
  await page.keyboard.press('Escape');assert(!(await card.isVisible()));
  await page.evaluate(()=>{startMarch(5,20000);options.state.marches[0].target_x+=50;ConquerWorld.render(options);ConquerWorld.followMarch(options.state.marches[0].id)});await page.waitForTimeout(1300);
  const rebases=await page.evaluate(()=>new Promise(resolve=>{const actor=document.querySelector('.atlas-march-party'),start=performance.now(),ground=groundCalls,points=[];function tick(t){const m=new DOMMatrix(getComputedStyle(actor).transform);points.push(m.m41);if(t-start<2200)requestAnimationFrame(tick);else resolve({points,ground:groundCalls-ground})}requestAnimationFrame(tick)}));
  assert(rebases.ground>0&&rebases.ground<rebases.points.length*.2,'Long follow reuses scenery and periodically rebases');assert(Math.max(...rebases.points)-Math.min(...rebases.points)<5,'Terrain rebases do not jolt the followed unit');console.log('PASS long follow: '+rebases.ground+' terrain rebases across '+rebases.points.length+' frames');
  await page.keyboard.press('Escape');
  await page.evaluate(()=>startMarch(5,20000));await page.waitForTimeout(350);const earlyBefore=await actor.evaluate(el=>[...el.worldPoint]);await page.evaluate(()=>options.onMarchRecall(options.state.marches[0].id));const earlyAfter=await actor.evaluate(el=>el.worldPoint);assert(Math.hypot(earlyAfter[0]-earlyBefore[0],earlyAfter[1]-earlyBefore[1])<.15,'Two-second minimum return does not jump an immediate recall');
  await page.evaluate(()=>startMarch(5,20000));await page.waitForTimeout(100);await page.locator('.atlas-march-hit').click();assert(await card.isVisible(),'Direct army tap follows');
  await page.locator('[data-march-command="destination"]').click();assert(!(await card.isVisible()));assert.equal(await page.evaluate(()=>ConquerWorld.getCenter().x),67);
  await row.locator('.world-march-main').click();assert(await page.locator('.atlas-target-actions').isVisible(),'March row opens and focuses the current target');assert.equal(await page.locator('.atlas-marker--monsters').getAttribute('aria-pressed'),'true');await page.locator('.atlas-target-actions [data-atlas="clear"]').click();
  for(const [width,height]of [[1280,800],[390,844],[320,568],[844,390]]){
   await page.setViewportSize({width,height});await page.evaluate(()=>{startMarch(5,30000);ConquerWorld.followMarch(options.state.marches[0].id)});await page.waitForTimeout(900);
   const reachable=await card.locator('button').evaluateAll(buttons=>buttons.filter(b=>!b.hidden).map(b=>{const r=b.getBoundingClientRect();return {name:b.dataset.marchCommand,inside:r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight,hit:b.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2))}}));assert(reachable.every(b=>b.inside&&b.hit),JSON.stringify({width,height,reachable}));
   await page.screenshot({path:path.join(output,`${width}x${height}-follow.png`)});
   const {x,y}=await page.evaluate(()=>{const r=document.querySelector('.atlas-viewport').getBoundingClientRect();for(const fy of [.3,.5,.7])for(const fx of [.35,.65,.8]){const x=r.x+r.width*fx,y=r.y+r.height*fy,el=document.elementFromPoint(x,y);if(el?.closest('.atlas-viewport')&&!el.closest('.atlas-zoom,.atlas-minimap'))return {x,y};}throw new Error('No free map area');});await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x+35,y+25,{steps:4});await page.mouse.up();assert(!(await card.isVisible()),'Dragging stops follow '+width);
   console.log('PASS touch layout, follow and manual pan '+width+'x'+height);
  }
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{startMarch(5,30000);const m=options.state.marches[0];options.state.nodes.push({id:77,coord_x:m.target_x,coord_y:m.target_y,object_type:2,level:4,resource_amount:12000,resource_max:20000,gatherer_march_id:900,is_own_gathering:true});options.state.marches.push({...m,id:900,march_type:9,target_type:5,target_id:77,target_resource:'lumber',state:'arrived',gathering_finishes_at:new Date(options.now()+60000).toISOString()},{...m,id:901,state:'returning',return_time:new Date(options.now()+45000).toISOString()});ConquerWorld.render(options)});assert.equal(await row.count(),3);assert.equal(await page.locator('.world-march-list').evaluate(el=>getComputedStyle(el).overflowY),'visible','Compact march list has no internal scrolling');assert.match(await page.locator('.world-march-heading').innerText(),/3\/3/);assert.match(await row.nth(1).innerText(),/Sammelt/);assert.match(await row.nth(1).innerText(),/X 66 · Y 64/);assert.match(await row.nth(2).innerText(),/Rückkehr/);assert.match(await row.nth(1).locator('.world-march-icon img').getAttribute('src'),/ui-resources\/lumber\.png/);
  const gatheringTime=await row.nth(1).locator('time').textContent();await page.waitForTimeout(2200);assert.notEqual(await row.nth(1).locator('time').textContent(),gatheringTime,'Gathering countdown updates live');
  const centerBeforeRecall=await page.evaluate(()=>ConquerWorld.getCenter());await row.nth(1).locator('.world-march-recall').click();assert.equal(await page.evaluate(()=>options.state.marches.find(m=>m.id===900).state),'returning');assert.match(await row.nth(1).innerText(),/Rückkehr/,'Recall immediately changes the row to return state');assert(!(await card.isVisible()),'Recall button does not also follow or focus the march');assert.deepEqual(await page.evaluate(()=>ConquerWorld.getCenter()),centerBeforeRecall,'Recall button does not move the camera');
  await page.evaluate(()=>{const m=options.state.marches.find(m=>m.id===900);m.state='arrived';m.gathering_finishes_at=new Date(options.now()+60000).toISOString();ConquerWorld.render(options)});await row.nth(1).locator('.world-march-main').click();assert.equal(await page.locator('.atlas-marker--nodes').getAttribute('aria-pressed'),'true','Gathering row focuses the occupied resource node');await page.evaluate(()=>{options.state.marches=options.state.marches.filter(m=>m.id!==900);ConquerWorld.render(options)});assert.equal(await row.count(),2,'Finished gathering march disappears from the compact list');
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>startMarch(5,20000));await page.waitForTimeout(100);assert.match(await actor.locator('.atlas-party-skin img').getAttribute('src'),/flight-phoenix.png/);
  await page.emulateMedia({reducedMotion:'no-preference'});await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});assert.match(await actor.locator('.atlas-party-skin img').getAttribute('src'),/flight-phoenix.png/);await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'))});
  assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',frames:sample.points.length,terrainPasses:sample.ground,errors,output}));
 }catch(e){console.error(e);throw e;}finally{if(browser)await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
