'use strict';
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'),fixture=require('./fixtures/world_march_motion.cjs'),output=path.join(root,'artifacts/world-march-motion-20260913');fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'index.html'),fixture(root,'/conquer'));
(async()=>{
 const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(name==='/'){res.setHeader('Content-Type','text/html');res.end(fixture(root));return;}const file=path.resolve(root,'.'+name);if(!name.startsWith('/assets/')||!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.webp')?'image/webp':'application/octet-stream');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{
  browser=await chromium.launch({headless:true,channel:'chrome'});const page=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error(e.message)});
  await page.goto('http://127.0.0.1:'+server.address().port);await page.evaluate(()=>{demoAuto=false;window.groundCalls=0;const ground=ConquerLandscape.ground;ConquerLandscape.ground=(...args)=>{groundCalls++;return ground(...args)};});
  const actor=page.locator('.atlas-march-party');await page.waitForSelector('.atlas-march-party.is-skinned');
  assert.match(await actor.locator('.atlas-party-skin img').getAttribute('src'),/flight-phoenix.webp/);assert.equal(await actor.locator('.atlas-party-skin img').evaluate(el=>getComputedStyle(el).animationName),'none','Articulated flight does not also bounce the entire picture');
  const sample=()=>page.evaluate(()=>new Promise(resolve=>{const samples=[],el=document.querySelector('.atlas-march-party'),ground=groundCalls;let start;function tick(t){start??=t;const m=new DOMMatrix(getComputedStyle(el).transform);samples.push({t,x:m.m41});if(t-start<700)requestAnimationFrame(tick);else resolve({samples,ground:groundCalls-ground});}requestAnimationFrame(tick);}));
  console.log('Sampling motion');const motion=await sample(),moving=motion.samples.filter((p,i,a)=>i&&p.x>a[i-1].x).length;console.log(JSON.stringify({frames:motion.samples.length,moving,first:motion.samples[0],last:motion.samples.at(-1)}));assert(moving>motion.samples.length*.8,'Travel advances on >80% of display frames');assert.equal(motion.ground,0,'Movement never repaints terrain or minimap');
  await page.evaluate(()=>{clockShift-=600;ConquerWorld.render(options)});const correction=await sample();assert(correction.samples.every((p,i,a)=>!i||p.x>=a[i-1].x-.01),'Rounded clock poll cannot reverse the army');assert(correction.samples.filter((p,i,a)=>i&&p.x>a[i-1].x).length>correction.samples.length*.8,'Clock correction keeps moving without a visible pause');
  console.log('PASS motion and clock correction');const route=await page.locator('.atlas-routes').innerHTML();await sample();assert.equal(await page.locator('.atlas-routes').innerHTML(),route,'Route is stable between snapshots');
  assert.equal(await page.evaluate(()=>{const before=groundCalls;options.state.marches[0].troops={1:249};ConquerWorld.render(options);return groundCalls-before}),0,'Troop-only server refresh reuses the terrain');assert.match(await actor.getAttribute('aria-label'),/249 Truppen/);
  // Coordinate updates in one input burst are coalesced into a display frame.
  const bounds=await page.locator('.atlas-viewport').boundingBox();await page.mouse.move(bounds.x+100,bounds.y+100);await page.mouse.down();
  const drag=await page.evaluate(()=>{const el=document.querySelector('.atlas-viewport'),r=el.getBoundingClientRect(),before=groundCalls;for(let i=1;i<=8;i++)el.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,pointerId:1,clientX:r.x+100+i*3,clientY:r.y+100}));return groundCalls-before;});await page.mouse.up();assert(drag<=1,'No repeated synchronous terrain passes for pointer events');
  for(const [width,height,biome,id]of [[1280,800,'forest','phoenix'],[390,844,'ice','winterhold'],[320,568,'sand','sandspire'],[844,390,'lava','eclipse']]){
   await page.setViewportSize({width,height});await page.evaluate(({biome,id})=>{document.querySelector('#skin').value=id;document.querySelector('#region').value=biome;startMarch(5,2400)}, {biome,id});
   await page.waitForSelector('.atlas-march-party.is-skinned');await page.waitForTimeout(700);await page.screenshot({path:path.join(output,`${width}x${height}-${biome}-march.png`)});
   await page.waitForSelector('.atlas-march-impact',{state:'attached'});assert.equal(await page.locator('.atlas-march-impact').count(),1);assert.equal(await actor.getAttribute('class').then(c=>c.includes('is-moving')),false,'Feet stop on arrival');await page.waitForTimeout(240);await page.screenshot({path:path.join(output,`${width}x${height}-${biome}-impact.png`)});
   await page.evaluate(()=>ConquerWorld.render(options));assert.equal(await page.locator('.atlas-march-impact').count(),1,'Poll cannot replay the impact');await page.waitForTimeout(2300);assert.equal(await page.locator('.atlas-march-impact').count(),0,'Burst is cleaned up');await page.evaluate(()=>ConquerWorld.render(options));assert.equal(await page.locator('.atlas-march-impact').count(),0);
   console.log('PASS '+width+'x'+height+' '+biome+': animated skin, contact, single burst, cleanup');
  }
  for(const kind of [6,8,9,10,14]){await page.evaluate(kind=>startMarch(kind,140),kind);await page.waitForTimeout(300);assert.equal(await page.locator('.atlas-march-impact').count(),0,'No attack effect for noncombat '+kind);}
  await page.evaluate(()=>{startMarch(5,140);options.state.marches[0].state='returning';ConquerWorld.render(options)});await page.waitForTimeout(350);assert.equal(await page.locator('.atlas-march-impact').count(),0,'No burst for return');
  await page.evaluate(()=>{startMarch(5,4000);const m=options.state.marches[0];clockShift+=4200;m.state='returning';ConquerWorld.render(options)});assert.equal(await page.locator('.atlas-march-impact').count(),1,'Arrival from server transition is caught between frames');await page.waitForTimeout(2300);
  await page.evaluate(()=>{startMarch(5,4000);window.fakeHidden=true;Object.defineProperty(document,'hidden',{configurable:true,get:()=>fakeHidden});document.dispatchEvent(new Event('visibilitychange'));clockShift+=4200;fakeHidden=false;document.dispatchEvent(new Event('visibilitychange'))});await page.waitForTimeout(200);assert.equal(await page.locator('.atlas-march-impact').count(),0,'Returning to a tab does not replay a missed attack');await page.evaluate(()=>{delete document.hidden});
  await page.evaluate(()=>{startMarch(5,140);options.state.marches.push(...Array.from({length:7},(_,i)=>({...options.state.marches[0],id:'crowd-'+i})));ConquerWorld.render(options)});await page.waitForTimeout(300);assert.equal(await page.locator('.atlas-march-impact').count(),4,'Simultaneous effects have a fixed mobile budget');await page.waitForTimeout(2300);
  await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>startMarch(5,140));await page.waitForTimeout(350);assert.equal(await page.locator('.atlas-march-impact').count(),0);assert.equal(await actor.locator('.atlas-party-skin img').evaluate(el=>getComputedStyle(el).animationName),'none');
  assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',frameSamples:motion.samples.length,movingFrames:moving,terrainPaintsDuringMotion:motion.ground,errors,output}));
 }finally{if(browser)await browser.close();server.closeAllConnections();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
