-- Reconcile the early field_objects table with the gathering service, preserving rows.
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'field_objects' AND column_name = 'object_type') = 0, 'ALTER TABLE field_objects ADD COLUMN object_type TINYINT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE repair_stmt FROM @ddl;
EXECUTE repair_stmt;
DEALLOCATE PREPARE repair_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'field_objects' AND column_name = 'level') = 0, 'ALTER TABLE field_objects ADD COLUMN level TINYINT UNSIGNED NOT NULL DEFAULT 1', 'SELECT 1');
PREPARE repair_stmt FROM @ddl;
EXECUTE repair_stmt;
DEALLOCATE PREPARE repair_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'field_objects' AND column_name = 'resource_amount') = 0, 'ALTER TABLE field_objects ADD COLUMN resource_amount INT UNSIGNED NOT NULL DEFAULT 10000', 'SELECT 1');
PREPARE repair_stmt FROM @ddl;
EXECUTE repair_stmt;
DEALLOCATE PREPARE repair_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'field_objects' AND column_name = 'resource_max') = 0, 'ALTER TABLE field_objects ADD COLUMN resource_max INT UNSIGNED NOT NULL DEFAULT 10000', 'SELECT 1');
PREPARE repair_stmt FROM @ddl;
EXECUTE repair_stmt;
DEALLOCATE PREPARE repair_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'field_objects' AND column_name = 'expires_at') = 0, 'ALTER TABLE field_objects ADD COLUMN expires_at DATETIME NOT NULL DEFAULT ''2030-01-01 00:00:00''', 'SELECT 1');
PREPARE repair_stmt FROM @ddl;
EXECUTE repair_stmt;
DEALLOCATE PREPARE repair_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'field_objects' AND column_name = 'gatherer_march_id') = 0, 'ALTER TABLE field_objects ADD COLUMN gatherer_march_id BIGINT UNSIGNED NULL', 'SELECT 1');
PREPARE repair_stmt FROM @ddl;
EXECUTE repair_stmt;
DEALLOCATE PREPARE repair_stmt;
SET @ddl = IF((SELECT COUNT(*) FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'field_objects' AND column_name = 'object_code') > 0, 'ALTER TABLE field_objects MODIFY COLUMN object_code INT NOT NULL DEFAULT 0, MODIFY COLUMN remaining INT NOT NULL DEFAULT 0', 'SELECT 1');
PREPARE repair_stmt FROM @ddl;
EXECUTE repair_stmt;
DEALLOCATE PREPARE repair_stmt;
