CREATE TABLE IF NOT EXISTS bug_reports (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 operation_key VARCHAR(64) NOT NULL,
 player_id INT NOT NULL,
 world_id INT NOT NULL,
 category ENUM('gameplay','interface','performance','account','other') NOT NULL,
 severity ENUM('minor','normal','blocking') NOT NULL DEFAULT 'normal',
 title VARCHAR(120) NOT NULL,
 description TEXT NOT NULL,
 reproduction_steps TEXT NOT NULL,
 expected_result VARCHAR(1000) NOT NULL DEFAULT '',
 page_path VARCHAR(160) NOT NULL DEFAULT '',
 client_context JSON NULL,
 user_agent VARCHAR(255) NOT NULL DEFAULT '',
 ip_address VARCHAR(45) NOT NULL DEFAULT '',
 status ENUM('new','in_progress','resolved','closed') NOT NULL DEFAULT 'new',
 priority ENUM('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
 admin_note TEXT NOT NULL,
 handled_by BIGINT UNSIGNED NULL,
 handled_at DATETIME NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY uq_bug_report_player_operation (player_id, operation_key),
 INDEX idx_bug_reports_world_status (world_id, status, created_at),
 INDEX idx_bug_reports_player (player_id, created_at),
 CONSTRAINT fk_bug_reports_player FOREIGN KEY (player_id) REFERENCES players(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
