-- Deliberately no gameplay foreign keys: diagnostics must survive a rejected transaction.
CREATE TABLE IF NOT EXISTS operational_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_uid VARCHAR(64) NOT NULL,
    category VARCHAR(24) NOT NULL,
    severity VARCHAR(12) NOT NULL DEFAULT 'info',
    origin VARCHAR(12) NOT NULL DEFAULT 'server',
    code VARCHAR(96) NOT NULL,
    message VARCHAR(512) NOT NULL DEFAULT '',
    outcome VARCHAR(24) NOT NULL DEFAULT 'observed',
    occurred_at DATETIME(3) NOT NULL,
    received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    player_id BIGINT UNSIGNED NULL,
    world_id BIGINT UNSIGNED NULL,
    request_id VARCHAR(64) NOT NULL DEFAULT '',
    operation_id VARCHAR(64) NOT NULL DEFAULT '',
    release_id VARCHAR(64) NOT NULL DEFAULT '',
    route VARCHAR(160) NOT NULL DEFAULT '',
    duration_ms INT UNSIGNED NULL,
    context_json TEXT NOT NULL,
    group_hash CHAR(64) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_operational_uid (event_uid),
    KEY idx_operational_world_time (world_id, occurred_at),
    KEY idx_operational_player_time (player_id, occurred_at),
    KEY idx_operational_category_time (category, occurred_at),
    KEY idx_operational_group_time (group_hash, occurred_at),
    KEY idx_operational_code_time (code, occurred_at),
    KEY idx_operational_retention (received_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
