<?php
declare(strict_types=1);
/** Included by defense_lifecycle.php only after its disposable database is created. */
use Conquer\Game\World\WorldContext as W;
use Conquer\Game\City\{CityState as CS,TroopTrainer as TT,BuildingUpgrader as BU,ResourceTick as RT};
use Conquer\Game\Research\{ResearchProcessor as RP,BuffEngine as BE};
use Conquer\Game\Defense\DefenseService as DS;
use Conquer\Game\March\{MarchDispatcher as MD,MarchTick as MT};
use Conquer\Game\Hospital\HospitalService as HS;
use Conquer\Game\Rally\RallyService as RS;
use Conquer\Game\WorldRules as WR;

if(!isset($name)||!preg_match('/^conquer_defense_test_[a-f0-9]{12}$/D',$name))throw new RuntimeException('Disposable defense fixture required.');
foreach([101=>1,102=>2] as $cityId=>$pid){
    $db->execute("INSERT INTO cities(id,player_id,world_id,name,coord_x,coord_y,food,lumber,stone,gold,last_resource_update) VALUES(?,?,2,'Second world',?,70,2000000,2000000,2000000,2000000,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 HOUR))",[$cityId,$pid,$cityId===101?250:270]);
    foreach(CS::BUILDING_CODES as $code)$db->execute('INSERT INTO city_buildings(city_id,building_code,level) VALUES(?,?,30)',[$cityId,$code]);
    $db->execute('INSERT INTO city_troops(city_id,troop_code,count) VALUES(?,50100101,1000)',[$cityId]);
}
$db->execute("INSERT INTO alliances(id,world_id,name,tag,leader_id) VALUES(3,2,'Other world','OW',1)");
$db->execute("INSERT INTO alliance_members(alliance_id,player_id,world_id,role) VALUES(3,1,2,'leader'),(3,4,2,'member')");
$first=CS::loadForPlayer(1);W::bind(2);
checkD(CS::loadForPlayer(1)['city']['id']===101&&DS::state(1)['world_id']===2,'selected world resolves the same player second city');
checkD(WR::alliance(1)===3&&WR::alliance(1,1)===1,'one player has independent alliance membership in each world');
rejectD(fn()=>DS::action(1,['action'=>'wall.repair','city_id'=>1,'hp_amount'=>1]),'own city from another world is rejected');
rejectD(fn()=>TT::train($first['city'],$first['buildings'],50100101,1),'training cannot use own city from another world');
rejectD(fn()=>BU::start(1,'farm',$first['city'],$first['buildings']),'construction cannot use own city from another world');
rejectD(fn()=>MD::dispatchScout(1,1,0,0,270,70),'marches cannot originate in another selected world');
rejectD(fn()=>MD::dispatchReinforce(1,101,0,0,95,40,3,3,[50100101=>1]),'reinforcement target cannot belong to another world');
$db->execute("INSERT INTO player_research(player_id,world_id,research_code,level) VALUES(1,1,'food_production',5),(1,2,'food_production',1)");
checkD((BE::getBuffs(1)['food_production']??0)<(BE::getBuffs(1,1)['food_production']??0),'research buffs use selected world or explicit persisted world');
$db->execute("INSERT INTO research_queue(player_id,world_id,research_code,level_to,started_at,finishes_at) VALUES(1,1,'lumber_production',1,UTC_TIMESTAMP(),DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND)),(1,2,'lumber_production',2,UTC_TIMESTAMP(),DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND))");
RP::processQueue(1);RP::processQueue(1);
checkD((int)$db->query("SELECT level FROM player_research WHERE player_id=1 AND world_id=2 AND research_code='lumber_production'")->fetchColumn()===2&&(int)$db->query("SELECT COUNT(*) FROM research_queue WHERE player_id=1 AND world_id=1 AND is_processed=0")->fetchColumn()===1,'research completion credits only selected world exactly once');
RP::processQueue(1,1);
checkD((int)$db->query("SELECT level FROM player_research WHERE player_id=1 AND world_id=1 AND research_code='lumber_production'")->fetchColumn()===1,'background research explicitly settles a different world');
$db->execute("UPDATE city_buildings SET level=12 WHERE city_id=101 AND building_code='barrack'");
rejectD(fn()=>DS::promote(1,101,50100101,1),'school level in world one does not unlock promotion in world two');
$db->execute("UPDATE city_buildings SET level=13 WHERE city_id=101 AND building_code IN ('castle','barrack')");
$p2=DS::promote(1,101,50100101,2);W::bind(1);
rejectD(fn()=>DS::cancelPromotion(1,$p2['promotion_id']),'promotion cancellation cannot reach own queue in another world');
$stock1=stockD(1);$db->execute('UPDATE defense_promotions SET finishes_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND) WHERE id=?',[$p2['promotion_id']]);
DS::processPromotions(101);DS::processPromotions(101);checkD(stockD(101,50100201)===2&&stockD(1)===$stock1,'promotion settlement uses persisted city while another world is selected');
$db->execute('UPDATE cities SET food=0,last_resource_update=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 HOUR) WHERE id=101');
$db->execute('UPDATE worlds SET speed_factor=3 WHERE id=2');$city=rowD('cities',101);$buildings=CS::loadForPlayer(1,2)['buildings'];
RT::persist($city,$buildings);$gained=(int)rowD('cities',101)['food'];
$buffs=BE::getBuffs(1,2);$base=\Conquer\Game\City\BuildingData::getHourlyRate('farm',30,array_merge(\Conquer\Game\Vip\VipService::status(1)['bonuses'],['food_prod_pct'=>$buffs['food_production']??0]));
$elapsed=strtotime(rowD('cities',101)['last_resource_update'])-strtotime($city['last_resource_update']);
$expected=$base*3*$elapsed/3600;
checkD($gained>=floor($expected)-2&&$gained<=ceil($expected)+5,'resource settlement derives speed and research from persisted city world: '.json_encode(compact('gained','expected','base','elapsed')));
$db->execute("INSERT INTO player_research(player_id,world_id,research_code,level) VALUES(1,2,'hospital_capacity',1)");
// Capacity derives actual city research; the active request may belong elsewhere.
$hospital2=HS::getStatus(101);$hospital1=HS::getStatus(1);
checkD($hospital2['capacity']>$hospital1['capacity'],'hospital capacity uses each city own world research');
W::bind(2);$city=CS::loadForPlayer(1);TT::train($city['city'],$city['buildings'],50100101,3);
$queue=(int)$db->query('SELECT id FROM troop_queue WHERE city_id=101 AND is_processed=0')->fetchColumn();
$m=MD::dispatchReinforce(1,101,0,0,280,40,4,4,[50100101=>10]);
checkD(count(MD::listActive(1))===1&&MD::listActive(1)[0]['id']===$m,'march list contains only active world armies');
W::bind(1);checkD(count(MD::listActive(1))===0,'armies in second world do not leak into first world list');
arriveD($m);checkD(rowD('marches',$m)['state']==='arrived'&&W::id()===1,'reinforcement arrival uses persisted world and restores request context');
rejectD(fn()=>DS::recallReinforcement(1,(int)$db->query('SELECT id FROM reinforcements WHERE march_id=?',[$m])->fetchColumn()),'foreign world reinforcement recall is rejected');
W::bind(2);$r=(int)$db->query('SELECT id FROM reinforcements WHERE march_id=?',[$m])->fetchColumn();
$db->execute("UPDATE worlds SET status='paused' WHERE id=2");
foreach([fn()=>DS::activateShield(1,101,600),fn()=>DS::repairWall(1,101,10),fn()=>MD::dispatchScout(1,101,0,0,270,70),fn()=>TT::train($city['city'],$city['buildings'],50100101,1),fn()=>BU::start(101,'farm',$city['city'],$city['buildings'])] as $action)rejectD($action,'paused world blocks a new paid city or army action');
DS::recallReinforcement(1,$r);$stock=stockD(101);$db->execute('UPDATE troop_queue SET finishes_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND) WHERE id=?',[$queue]);
W::bind(1);TT::processQueue($db,101);homeD($m);homeD($m);
checkD(stockD(101)===$stock+13&&stockD(1)===$stock1,'paused world still settles training and recalled army exactly once into origin city');
$db->execute("UPDATE worlds SET status='running' WHERE id=2");W::bind(2);
$db->execute("INSERT INTO field_objects(world_id,coord_x,coord_y,object_type,level,resource_amount,resource_max,expires_at) VALUES(2,310,90,1,1,10000,10000,DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 HOUR))");
$object=$db->lastInsertId();$m=MD::dispatchGather(1,101,310,90,0,[50100101=>5]);W::bind(1);$food=(int)rowD('cities',1)['food'];arriveD($m);$db->execute('UPDATE marches SET arrival_time=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 DAY),gathering_finishes_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND) WHERE id=? AND state=?',[$m,'arrived']);\Conquer\Game\March\GatherService::finish($m);$haul=json_decode(rowD('marches',$m)['haul_json'],true);homeD($m);
checkD((int)rowD('marches',$m)['world_id']===2&&array_sum($haul['loot'])>0&&(int)rowD('cities',1)['food']===$food,'gather target loot and return remain in persisted second world');
$db->execute("INSERT INTO field_monsters(world_id,coord_x,coord_y,monster_code,hp_current) VALUES(2,312,90,20209901,30)");
W::bind(2);$m=MD::dispatchMonster(1,101,0,0,312,90,[50100101=>50]);W::bind(1);arriveD($m);
checkD((int)$db->query('SELECT world_id FROM battle_reports WHERE march_id=?',[$m])->fetchColumn()===2,'monster report uses persisted world during crossworld lazy tick');homeD($m);
$xpReport=json_decode($db->query('SELECT data_json FROM battle_reports WHERE march_id=?',[$m])->fetchColumn(),true);
$xpReceipt=(int)$db->query('SELECT xp FROM lord_xp_receipts WHERE player_id=1 AND world_id=2 AND source=?',['monster-march:'.$m])->fetchColumn();
checkD($xpReceipt>0&&$xpReceipt===(int)$xpReport['lord_xp'],'confirmed monster kill atomically awards reported hunting XP in origin world');
$xpBefore=\Conquer\Game\Player\LordLevel::snapshot(1,2)['xp'];arriveD($m);homeD($m);
checkD(\Conquer\Game\Player\LordLevel::snapshot(1,2)['xp']===$xpBefore,'repeated monster settlement cannot duplicate hunting XP');
$db->execute("INSERT INTO map_charms(world_id,coord_x,coord_y,charm_code,grade,stat_category,expires_at) VALUES(2,313,90,999,'normal','construction_speed',DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 HOUR))");
$charm=$db->lastInsertId();$stock=stockD(101);W::bind(2);$m=MD::dispatchCharm(1,101,0,0,313,90,$charm,[50100101=>3]);W::bind(1);arriveD($m);homeD($m);homeD($m);
checkD(stockD(101)===$stock&&(int)$db->query('SELECT collected_by FROM map_charms WHERE id=?',[$charm])->fetchColumn()===1,'charm collection preserves world and returns reserved army exactly once');
W::bind(2);$db->execute('UPDATE cities SET anti_spy_until=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 HOUR) WHERE id=102');$m=MD::dispatchScout(1,101,0,0,270,70);W::bind(1);arriveD($m);
$report=json_decode((string)$db->query('SELECT data_json FROM battle_reports WHERE march_id=?',[$m])->fetchColumn(),true);homeD($m);
checkD(($report['blocked']??false)&&!isset($report['resources'],$report['troops'],$report['wall'],$report['treasures']),'active anti-spy hides sensitive scout data at arrival');
W::bind(2);$db->execute('UPDATE cities SET anti_spy_until=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND) WHERE id=102');$m=MD::dispatchScout(1,101,0,0,270,70);arriveD($m);$report=json_decode((string)$db->query('SELECT data_json FROM battle_reports WHERE march_id=?',[$m])->fetchColumn(),true);homeD($m);
checkD(isset($report['resources'],$report['troops'],$report['wall']),'expired anti-spy restores real scout reports');
$rally=RS::start(1,101,2,270,70,[50100101=>2],1,'World two');W::bind(1);rejectD(fn()=>RS::cancel($rally,1),'rally cancellation cannot target another selected world');
$db->execute('UPDATE rallies SET launch_at=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND) WHERE id=?',[$rally]);RS::tick();checkD(rowD('rallies',$rally)['status']==='marching'&&W::id()===1,'rally background launch uses persisted world and restores context');
$db->execute('UPDATE cities SET is_shielded=1,shield_expires_at=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 HOUR) WHERE id=102');$db->execute('UPDATE rallies SET arrival_time=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND),return_time=DATE_ADD(UTC_TIMESTAMP(),INTERVAL 1 HOUR) WHERE id=?',[$rally]);RS::tick();$stock=stockD(101);
$db->execute('UPDATE rallies SET return_time=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 1 SECOND) WHERE id=?',[$rally]);RS::tick();RS::tick();checkD(stockD(101)===$stock+2&&rowD('rallies',$rally)['status']==='complete','shielded second world rally returns troops exactly once');
W::bind(1);
