'use strict';
// Transparent game sprites and independent close/map-scale style review.
const fs=require('fs'),path=require('path'),http=require('http'),os=require('os'),assert=require('assert'),{execFileSync}=require('child_process');
const{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const root=path.resolve(__dirname,'..');
const fixture=`<!doctype html><html><link rel="icon" href="data:,"><body style="margin:0"><script type="module">
import * as T from '/assets/city3d/vendor/three.module.js';import{buildShrine,SHRINE_BIOMES}from'/assets/city3d/shrines.js';
const scene=new T.Scene(),renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setClearColor(0,0);renderer.outputColorSpace=T.SRGBColorSpace;document.body.append(renderer.domElement);scene.add(new T.HemisphereLight('#e8f5ff','#736943',2.25));const sun=new T.DirectionalLight('#fff1cb',3.5);sun.position.set(-12,20,14);scene.add(sun);
const camera=new T.OrthographicCamera(-2.72,2.72,2.72,-2.72,.1,100);camera.position.set(10,12,18);camera.lookAt(0,1.42,0);const shrines=new Map(SHRINE_BIOMES.map(id=>{const model=buildShrine(id);model.visible=false;scene.add(model);return[id,model];}));
window.renderShrine=(id,time=0,size=640)=>{for(const[key,value]of shrines)value.visible=key===id;const model=shrines.get(id);model.userData.animate(time);renderer.setSize(size,size);renderer.render(scene,camera);let invalid=0;model.traverse(o=>{if(o.geometry)for(const p of o.geometry.attributes.position.array)if(!Number.isFinite(p))invalid++;});return{png:renderer.domElement.toDataURL('image/png'),stats:model.userData.modelStats,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,invalid};};window.ready=true;
</script></body></html>`;
(async()=>{const server=http.createServer((req,res)=>{const name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(name==='/'){res.setHeader('Content-Type','text/html');res.end(fixture);return;}const file=path.resolve(root,'.'+name);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':'application/octet-stream');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
const temp=fs.mkdtempSync(path.join(os.tmpdir(),'conquer-shrines-')),errors=[];
try{browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'||m.type()==='warning')errors.push(m.text());});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready);
for(const id of['forest','ice','sand','lava']){const still=await page.evaluate(id=>window.renderShrine(id),id);assert.equal(still.invalid,0);const output=path.join(root,'assets/art/map',`shrine-${id}.png`);fs.writeFileSync(output,Buffer.from(still.png.split(',')[1],'base64'));const small=await page.evaluate(id=>window.renderShrine(id,0,132),id);fs.writeFileSync(path.join(temp,id+'-map-scale.png'),Buffer.from(small.png.split(',')[1],'base64'));
const frames=path.join(temp,id);fs.mkdirSync(frames);for(let frame=0;frame<32;frame++){const image=await page.evaluate(({id,frame})=>window.renderShrine(id,frame/8,480),{id,frame});fs.writeFileSync(path.join(frames,String(frame).padStart(2,'0')+'.png'),Buffer.from(image.png.split(',')[1],'base64'));}
const python=process.env.PYTHON_IMAGE_RUNTIME||'C:/Users/svenm/.cache/codex-runtimes/codex-primary-runtime/dependencies/python/python.exe',webp=path.join(root,'assets/art/map',`shrine-${id}.webp`);execFileSync(python,['-c',"from PIL import Image; from pathlib import Path; import sys; frames=[Image.open(p).convert('RGBA') for p in sorted(Path(sys.argv[1]).glob('*.png'))]; assert len(frames)==32; frames[0].save(sys.argv[2],save_all=True,append_images=frames[1:],duration=125,loop=0,quality=80,method=4); im=Image.open(sys.argv[2]); assert im.n_frames==32 and im.size==(480,480); assert frames[0].tobytes()!=frames[8].tobytes()",frames,webp]);console.log(JSON.stringify({id,...still.stats,renderDrawCalls:still.drawCalls,renderTriangles:still.triangles,webpKB:Math.round(fs.statSync(webp).size/1024)}));}
if(errors.length)console.error(JSON.stringify(errors));assert.deepEqual(errors,[],'renderer errors/warnings');console.log('PASS all four: finite geometry, no JS/WebGL warnings, 32-frame animations; map-scale review '+temp);
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
